### ISSUE TITLE
issue about accuracy

### ISSUE THREAD

**Issue by zguo008** [cardwing/Codes-for-Lane-Detection#101]
Hi,

I believe there are some issue raised on accuray==nan, this is because accuracy=pred/truth, when there is no lane in the training image accuracy = pred/0 which will throw Nan. Also when calculating the running avg np.mean(bag), if there is nan in bag, the running avg will be nan as well.

My question is that if in ground truth there are no lane pixels,
 (case 1). ground truth: no lane; pred: no lane. Accuracy becomes 100%
 (case 2). ground truth: no lane; pred: some lane pixels 
 how to calculate accuracy in case 2? will the accuracy be zero?

**Comment by cardwing** [comment]
A proper way to calculate accuracy is: (pred == truth) / (W * H), where W and H is the width and height of the image.

**Comment by zguo008** [comment]
Great! That makes a lot sense:) Thanks!

**Comment by cardwing** [comment]
^_^
