### ISSUE TITLE
测试图片路径问题？image_path指test_img.txt的路径吗 windows pycharm环境

### ISSUE THREAD

**Issue by yinhai86924** [cardwing/Codes-for-Lane-Detection#102]
test setup failed
file E:\Codes-for-Lane-Detection-master\SCNN-Tensorflow\lane-detection-model\tools\test_lanenet.py, line 49
  def test_lanenet(image_path, weights_path, use_gpu, image_list, batch_size, save_dir):
E       fixture 'image_path' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, monkeypatch, pytestconfig, record_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.
![QQ截图20190507122838](https://user-images.githubusercontent.com/45553479/57271921-de2dfc00-70c3-11e9-9750-aac21bd1aff7.jpg)
主要是哪里出了问题？下面是设置的路径以及测试集的修改后的绝对路径
def init_args():
    """

    :return:
    """
    parser = argparse.ArgumentParser()
    parser.add_argument('--image_path', type=str, help='The image path or the src image save dir',default=r"E:\Codes-for-Lane-Detection-master\SCNN-Tensorflow\lane-detection-model\tools\test_img.txt")
    parser.add_argument('--weights_path', type=str, help='The model weights path', default= r"E:\Codes-for-Lane-Detection-master\SCNN-Tensorflow\lane-detection-model\model_culane-71-3\culane_lanenet_vgg_2018-12-01-14-38-37.ckpt-10000")
    parser.add_argument('--is_batch', type=str, help='If test a batch of images', default='True')
    parser.add_argument('--batch_size', type=int, help='The batch size of the test images', default=2)
    parser.add_argument('--save_dir', type=str, help='Test result image save dir', default=r"E:\Codes-for-Lane-Detection-master\SCNN-Tensorflow\lane-detection-model\result")
    parser.add_argument('--use_gpu', type=int, help='If use gpu set 1 or 0 instead', default=1)

    return parser.parse_args()
![QQ截图20190507155052](https://user-images.githubusercontent.com/45553479/57282593-f3188880-70df-11e9-9907-6d2af7b8de33.jpg)

**Comment by yinhai86924** [comment]
Testing started at 15:23 ...
F:\new-Lanenet\lib\Scripts\python.exe "D:\Pycharm\PyCharm Community Edition 2018.2.4\helpers\pycharm\_jb_pytest_runner.py" --path E:/Codes-for-Lane-Detection-master/SCNN-Tensorflow/lane-detection-model/tools/test_lanenet.py
Launching pytest with arguments E:/Codes-for-Lane-Detection-master/SCNN-Tensorflow/lane-detection-model/tools/test_lanenet.py in E:\Codes-for-Lane-Detection-master\SCNN-Tensorflow\lane-detection-model\tools

============================= test session starts =============================
platform win32 -- Python 3.5.4, pytest-4.3.0, py-1.8.0, pluggy-0.9.0
rootdir: E:\Codes-for-Lane-Detection-master\SCNN-Tensorflow\lane-detection-model\tools, inifile:collected 1 item

test_lanenet.py E
test setup failed
file E:\Codes-for-Lane-Detection-master\SCNN-Tensorflow\lane-detection-model\tools\test_lanenet.py, line 49
  def test_lanenet(image_path, weights_path, use_gpu, image_list, batch_size, save_dir):
E       fixture 'image_path' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, monkeypatch, pytestconfig, record_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

主要是哪里出了问题？

**Comment by cardwing** [comment]
Please check the image path carefully since it is not difficult to debug.
