### ISSUE TITLE
how to load model

### ISSUE THREAD

**Issue by Hrhythm** [cardwing/Codes-for-Lane-Detection#104]
I download the pretrained model,it contains three files. .data , .meta, .index., and I run as this way:
--weights_path /home/Net/Codes-for-Lane-Detection-master/SCNN-Tensorflow/lane-detection-model/model_culane-71-3
and met this error: The passed save_path is not a valid checkpoint. However your pretrained folder does not have .checkpoint
Can you help me,thanks.

**Comment by cardwing** [comment]
It should be "--weights_path /home/Net/Codes-for-Lane-Detection-master/SCNN-Tensorflow/lane-detection-model/model_culane-71-3/culane_lanenet_vgg_2018-12-01-14-38-37.ckpt-10000"
