### ISSUE TITLE
evaluation script

### ISSUE THREAD

**Issue by zguo008** [cardwing/Codes-for-Lane-Detection#105]
Hi,

May i know do you have the evaluation script in Python?

Could you please share it?

Best,

ZX

**Comment by cardwing** [comment]
After running test_lanenet.py, you get the probability maps from the model. To get the final performance, you just need to follow instructions in [SCNN-Torch](https://github.com/XingangPan/SCNN). More specifically, follow step 3 and 4 (Get curve line from probability map and Calculate precision, recall, and F-measure) in the testing phase.

**Comment by zguo008** [comment]
Thank you:) it works now! 

Another question is about the F measure you calculated. Do you use threshold 0.3 or 0.5 at Run.sh?

Best,

ZX

**Comment by zguo008** [comment]
Thank you! it works now:)

**Comment by harryhan618** [comment]
The evaluation for CULane is quite slow. It takes tens of minutes to finish all the evaluation (9 different test list). I wanna check if this is normal.

**Comment by cardwing** [comment]
It is normal since there are 30k images in the testing set.

**Comment by harryhan618** [comment]
@cardwing Thanks! Pardon me for inquiring the details. May I ask what parameters do you use for evaluation? Do you use the default setup that `width_lane: 30` and `iou_threshold: 0.5`?

**Comment by cardwing** [comment]
Yes. You can just check the details in scripts of ENet-Label-Torch. The performance of the released model (F1-measure: 72.0) is higher than the reported value (F1-measure: 70.8).
