### ISSUE TITLE
The "ENet-Label-Torch" is a light-weight of scnn?   ENet+scnn?

### ISSUE THREAD

**Issue by SuperPengXue** [cardwing/Codes-for-Lane-Detection#108]

**Comment by cardwing** [comment]
ENet-Label-Torch is based on SCNN, but replaces VGG-16 and removes message passing. Besides, attention distillation is adopted. Please refer to the codes to check the details.

**Comment by SuperPengXue** [comment]
thanks for your reply.

**Comment by harryhan618** [comment]
Sorry for bothering you again. 
1. I scan the code in `ENet-Label-Torch`. It seems IOU loss is not used in the lua torch code, right?
2. I' m a little confused by the stucture of the repo. It seems `ENet-Label-Torch` and `ENet-TuSimple-Torch` both implement the attention distillation. Why two directories?

Thanks!

**Comment by cardwing** [comment]
1. Yes. Since it only brings marginal performance gains.
2. The codes for TuSimple also contain the postprocessing to extract lane points from probability maps and the evaluation script to calculate Accuracy, FP and FN. I release the codes of ENet to facilitate the reproduction process in TuSimple.
