### ISSUE TITLE
undefined reference to `cv::imread(cv::String const&, int)'

### ISSUE THREAD

**Issue by hellosher** [cardwing/Codes-for-Lane-Detection#112]
我在用seg_label工具自己尝试生成标签的时候，make之后提示opencv错误,请问这个问题要怎么解决呢

**Comment by cardwing** [comment]
You may try building opencv from source.

**Comment by BoSeal** [comment]
@hellosher ,你好，我是在评估SCNN性能的时候，输入make之后，出现了与你相同的问题，请问，最后这个问题你是怎么解决的？希望你可以告诉我，谢谢!
