### ISSUE TITLE
How to use CULane dataset in SCNN-Tensorflow

### ISSUE THREAD

**Issue by Leviou** [cardwing/Codes-for-Lane-Detection#113]
Hi,when I use CULane dataset in SCNN-Tensorflow, I create the folder  lane-detection_mode/dataset and put CULane dataset into it, just like this, dataset/CULane/xxxxframe.when I run the code with  dataset_dir  dataset/CULane/list/ ,because list folder contains train_gt.txt and val_gt.txt, but I always get error of not found  some files, I don't know   I don't know if my configuration is correct? Could you give me a hand?

**Comment by ryl1122** [comment]
try to
cp CULane/list/*  CULane/

**Comment by Leviou** [comment]
> 
>

**Comment by Leviou** [comment]
I try to do it as you said,but it can't work. not found xxxx
I copy  all  dataset file to  /lane-deteciton-mode/xxxxframe, but train_gt.txt and val_gt.txt  in dataset/CULane/,bu this way,The program can run correctly, I don‘t konw why?
