### ISSUE TITLE
SCNN输入输出节点的问题

### ISSUE THREAD

**Issue by ryl1122** [cardwing/Codes-for-Lane-Detection#117]
我在从ckpt转pb的时候，以及pb转C代码时，转换的脚本需要明确 输入输出的节点。我尝试了很多节点，但是都不对。请问下这个输入输出的节点如何查看？

**Comment by ycdhqzhiai** [comment]
你好，你输入输出节点选取的是什么啊，我输出节点选择的是lanenet_loss/inference/encode/relu6，还没有测试，不知道你试过没有

**Comment by cardwing** [comment]
Have a try of the following codes:
`checkpoint_dir = 'path/to/culane_lanenet_vgg_2018-10-24-22-40-59.ckpt-17000'`
`for var_name, _ in tf.contrib.framework.list_variables(checkpoint_dir):`
    `# Load the variable`
    `var = tf.contrib.framework.load_variable(checkpoint_dir, var_name)`
    `print(var_name)`

**Comment by ycdhqzhiai** [comment]
@ryl1122 可以参考下https://github.com/ycdhqzhiai/SCNN_PB，对tf不是很熟，瞎折腾出来的可以参考下

**Comment by ycdhqzhiai** [comment]
@ryl1122  可以参考下https://github.com/ycdhqzhiai/SCNN_PB
