### ISSUE TITLE
Got several issues while testing newly released ENet-Label-Torch.

### ISSUE THREAD

**Issue by zoeveryday** [cardwing/Codes-for-Lane-Detection#118]
Thanks for the awesome work!

I am trying to test the new ENet model, and the following are the issues I've met.

1.  an error occurred in testLane.lua:124 while run `test.sh` script
https://github.com/cardwing/Codes-for-Lane-Detection/blob/fce40451813150d986d994cfb55be2c1bc36b651/ENet-Label-Torch/testLane.lua#L124
The debug info indicated the `exist[b][i]` is [torch.FloatTensor of size 4]. So I changed this line into `if exist[i] > 0.5 then`, and the default testing script will work.

2. another issue occurred while testing my own data (1280x720 image), and the modified `test.sh` will throw the error as blow:

> **/**/torch/install/share/lua/5.1/threads/threads.lua:183: [thread 2 callback] /home/**/**/torch/install/share/lua/5.1/image/init.lua:569: image.crop: crop goes outside bounds of src
> stack traceback:
> 	[C]: in function 'cropNoScale'
> 	/home/**/**/torch/install/share/lua/5.1/image/init.lua:569: in function 'crop'
> 	./datasets/transforms.lua:57: in function 'transform'
> 	./datasets/transforms.lua:19: in function 'preprocess'
> 	./dataloader.lua:99: in function <./dataloader.lua:92>
> 	[C]: in function 'xpcall'
> 	.../**/torch/install/share/lua/5.1/threads/threads.lua:234: in function 'callback'
> 	...**/**/torch/install/share/lua/5.1/threads/queue.lua:65: in function <...**/**/torch/install/share/lua/5.1/threads/queue.lua:41>
> 	[C]: in function 'pcall'
> 	...**/**/torch/install/share/lua/5.1/threads/queue.lua:40: in function 'dojob'
> 	[string "  local Queue = require 'threads.queue'..."]:15: in main chunk
> stack traceback:
> 	[C]: in function 'error'
> 	.../**/torch/install/share/lua/5.1/threads/threads.lua:183: in function 'dojob'
> 	./dataloader.lua:157: in function '(for generator)'
> 	testLane.lua:66: in main chunk
> 	[C]: in function 'dofile'
> 	.../**/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
> 	[C]: at 0x00406670

It seems to be the input image size I used is not compatible with the new model.  I had to resize my test images to 1640x590 to make it work. However, as for the original SCNN torch repo, the `test.sh` script works fine for the 1280x720 images. Any suggestion?

Thanks in advance.

**Comment by cardwing** [comment]
@zoeveryday I crop the original images of the CULane images (1640 x 590) and remove the part which only contains background. And the image after cropping is 1640 x 350. And that's why the second problem occurs (the new image is 1280 x 720). You can just remove 'input = image.crop(input, 0, 230, 1640, 590)' in transforms.lua and the testing script should work.

**Comment by zoeveryday** [comment]
@cardwing actually, I can get better results if I resize the 1280x720 images into 1640x590 ones. 

Another question, I noticed that the prob map size now is 208x976 (which used to be 288x800). So if I want to overlap the prob map to the test images, shall I resize it back to 1640x350 first, and then pad 1640x240 to the top? (if I don't change anything within the transforms.lua)

**Comment by cardwing** [comment]
@zoeveryday If you just use the main.m to obtain the coordinates of lane points, nothing should be changed and the current scripts can already achieve that.

**Comment by zoeveryday** [comment]
@cardwing thanks for the reply, I'll close the issue now.
