### ISSUE TITLE
Notes for installation

### ISSUE THREAD

**Issue by Jeremy26** [cardwing/Codes-for-Lane-Detection#121]
Hello,

As I tested the installation, here are some things I encountered :

- If running Anaconda environment, tensorflow-gpu installation should be with ```conda install tensorflow-gpu``` otherwise CUDA and CUDNN will report errors
- You might have this error caused by python3.5 and conda.
```ImportError: /home/jeremy/miniconda2/envs/tensorflow_gpu/lib/python3.5/site-packages/google/protobuf/pyext/_message.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZNK6google8protobuf10TextFormat17FieldValuePrinter9PrintBoolEb```
However, tensorflow_gpu doesn't work with python 3.5 so it seems that there is a blocking point.

--> Installing protobuf version 3.6.1 solved it for me : ```conda install protobuf==3.6.1```

- For some reason, you can also have an error ModuleNotFoundError: No module named 'glog'
even though the requirement.txt file installed it.
I found the solution here : https://github.com/benley/python-glog/issues/8

- If you want to run this with ROS (Robot Operating System); it will be very difficult given that python 3 and ROS are not great of a match. I will post a comment on what I did to solve the ROS issues. 

Also, if module not found "lanenet_model" : add it to PYTHONPATH
https://github.com/MaybeShewill-CV/lanenet-lane-detection/issues/15

**Comment by cardwing** [comment]
@Jeremy26 Thanks for sharing the installation process with us.
