### ISSUE TITLE
关于label的生成

### ISSUE THREAD

**Issue by Cverlpeng** [cardwing/Codes-for-Lane-Detection#125]
你好，作者！
感谢你工作，这里有一些生成label的问题急需请教你一下。
1.官方提供下载的CULane数据集中laneseg_label_w16是不是使用老版本的标注文件生成的呢？
2.我自己使用下载的标注文件，使用官方提供的生成程序，生成的label会比下载好的以及的生成的label每张图片中的车道线都要短一截，不太清楚是什么原因！官网说过中途换过一次标注。
![vis_label](https://user-images.githubusercontent.com/46803558/62349211-afdc8300-b531-11e9-91c7-ca7c25cf46d6.png)

期待你的回复！
非常感谢！

**Comment by cardwing** [comment]
我是直接下载官方提供的label，并没有试着自己去生成label。

**Comment by Cverlpeng** [comment]
> 我是直接下载官方提供的标签，并没有试着去生成标签。

谢谢你，期待你的新paper早点放出来！
