### ISSUE TITLE
pred.json

### ISSUE THREAD

**Issue by jiaofang1222** [cardwing/Codes-for-Lane-Detection#126]
您好，请教一下，在pred_json.py中我想将自己的数据集的不同车道线的坐标保存在.json文件中，用于拟合车道线参数。我应该怎么去做？在你给出的程序中，没有太多的注释，我不太清楚一些数字的含义，例如：curve = [1030, 1430, 1440, 1470, 1530, 1640, 2390, 2720, 2780]；maxArea中800,1500；我imshow了label，发现是有车道线的，不过生成的lane值都为-2，希望能得到您的帮助。

**Comment by cardwing** [comment]
这里curve保存的应该是有问题的图片的序号，我当时用来调performance的，所以不用考虑。至于maxArea，是指图片中包含车道线的区域的大小，这个是考虑了TuSimple数据集的特点才选择这么大的，如果你用自己采集的数据，这个area大小需要自己去定。lane的值是-2就说明这里没有车道线，这和TuSimple数据集的标注定义方式是一致的。具体的定义方式见[这里](https://github.com/TuSimple/tusimple-benchmark/tree/master/doc/lane_detection)。

**Comment by jiaofang1222** [comment]
恩，谢谢您的回复。其实我现在想在AugCULane数据集上去跑那个鲁汶大学端到端检测模型，之前我用np.where（）和np.polyfit()得到的曲线参数用于训练时候，误差很大并且最终结果不好，所以我想尝试通过获得分割图中车道线坐标然后再拟合车道线参数，我也不确定能不能起到作用。因为我在评论区看到你评论了，所以想冒昧的问一下你用其他数据集跑过那个端到端车道线检测模型吗？

**Comment by cardwing** [comment]
I have not tested that end-to-end lane detection model.

**Comment by jiaofang1222** [comment]
好，谢谢您！
