### ISSUE TITLE
Problem when test image (256*512)

### ISSUE THREAD

**Issue by ashergaga** [cardwing/Codes-for-Lane-Detection#128]
I changed the cofig.py to 256*512 to test the model. But I got some problems:

InvalidArgumentError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [2560,128] rhs shape= [4500,128]
	 [[node save/Assign_82 (defined at SCNN-Tensorflow/lane-detection-model/test_lanenet.py:66)  = Assign[T=DT_FLOAT, _class=["loc:@lanenet_loss/inference/encode/dense/kernel"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](lanenet_loss/inference/encode/dense/kernel, save/RestoreV2/_165)]]

**Comment by cardwing** [comment]
The trained model is intended for CULane and hence the size of the input image is 288 x 800 instead of 256 x 512.
