### ISSUE TITLE
Outputs from SCNN-Tensorflow!

### ISSUE THREAD

**Issue by sicarioakki** [cardwing/Codes-for-Lane-Detection#129]

**Comment by sicarioakki** [comment]
@cardwing Please post the output results you have derived from the current implementation?

**Comment by cardwing** [comment]
Sorry that I have not saved the output results. But you can just obtain the output probability maps from the trained SCNN-Tensorflow model.

**Comment by sicarioakki** [comment]
Okay. Yes, I have got the outputs from the trained model you have shared. But the lanes are very vaguely mapped in the binary image. That is why i wanted to see the ideal results which you might have got. Thanks for your prompt reply! @cardwing
