### ISSUE TITLE
How to know the curve parameters?

### ISSUE THREAD

**Issue by TonightGo** [cardwing/Codes-for-Lane-Detection#130]
Hello Yuenan,

The network outputs the lanes points according to the probability map every 20 rows. Then you use the cubic splines to connect these position to generate the curves. If I want to know the curvature of lanes, I need to fit the curve and get the parameters. Whether or not?

**Comment by cardwing** [comment]
Yes. You can calculate the curvature of lanes according to the fitted splines.

**Comment by k-nayak** [comment]
Hello @TonightGo  I would like to know if you implemented the fitted splines method to find curvature. If yes, Can you share the implementation? Thanks
