### ISSUE TITLE
Attention maps in paper

### ISSUE THREAD

**Issue by Cverlpeng** [cardwing/Codes-for-Lane-Detection#131]
你好，你的论文中的Attention maps是使用 什么工具可视化的呢？它是每个E阶段中卷积的输出再经过softmax再可视化的吗？
谢谢你
![image](https://user-images.githubusercontent.com/46803558/62999540-58c79e00-bea1-11e9-9166-f101ddc4f6a7.png)

**Comment by cardwing** [comment]
These attention maps are obtained via using self multiplication and channel-wise addition to process feature maps. Then, you can use matplotlib.pyplot.plot to visualize these maps.

**Comment by Cverlpeng** [comment]
> These attention maps are obtained via using self multiplication and channel-wise addition to process feature maps. Then, you can use matplotlib.pyplot.plot to visualize these maps.

你好，我不太明白matplotlib.pyplot.plot怎么用来可视化attention map？你能提供 一小段代码吗？
非常感谢！

**Comment by cardwing** [comment]
You can refer to [this site](https://matplotlib.org/3.1.0/gallery/images_contours_and_fields/matshow.html#sphx-glr-gallery-images-contours-and-fields-matshow-py) or use seaborn.
`import seaborn as sns
import matplotlib.pylab as plt
import scipy.misc

uniform_data = scipy.misc.imread('sample_14_img/2_ori_4.png')
img = scipy.misc.imresize(uniform_data, (288, 800), 'bilinear')
ax = sns.heatmap(img, linewidth=0, cmap="jet")
plt.show()`
