### ISSUE TITLE
tusimple数据集评估

### ISSUE THREAD

**Issue by whz1994** [cardwing/Codes-for-Lane-Detection#132]
您好，请问怎么在tusimple数据集上评估模型的准确性，能不能请您给我说一下，谢谢

**Comment by cardwing** [comment]
See [this file](https://github.com/cardwing/Codes-for-Lane-Detection/blob/master/ENet-TuSimple-Torch/evaluate/lane.py).

**Comment by whz1994** [comment]
这个文件是怎么用的啊，怎么生成pred.json文件,基础不好麻烦您了




发自网易邮箱大师
在2019年08月15日 16:42，HOU Yuenan 写道：

See this file.

**Comment by cardwing** [comment]
Please refer to the README in each repo which contains step-by-step instructions.

**Comment by whz1994** [comment]
Thank you for your prompt reply.





At 2019-08-16 09:39:34, "HOU Yuenan" <notifications@github.com> wrote:


Please refer to the README in each repo which contains step-by-step instructions.

**Comment by whz1994** [comment]
您好，您的这个评估是适用于scnn的，您尝试过评估lanenet吗？

**Comment by cardwing** [comment]
You can refer to [this issue](https://github.com/MaybeShewill-CV/lanenet-lane-detection/issues/183).

**Comment by whz1994** [comment]
您好，我想问的是在tusimple数据集上评估lanenet训练模型准确率，scnn里提供的代码在lanenet上不适用





At 2019-08-31 17:30:25, "HOU Yuenan" <notifications@github.com> wrote:


You can refer to this issue.

**Comment by cardwing** [comment]
I have not tested LaneNet in TuSimple. But you can use the codes in [this repo](https://github.com/cardwing/Codes-for-Lane-Detection/tree/master/ENet-TuSimple-Torch) to test LaneNet in TuSimple.

**Comment by whz1994** [comment]
好吧，这个代码去测试lanenet需要改一些东西，但是我不知道怎么改，如果您方便的话能不能请您修改一个在lanenet上适用的代码，非常感谢！






At 2019-08-31 21:28:02, "HOU Yuenan" <notifications@github.com> wrote:


I have not tested LaneNet in TuSimple. But you can use the codes in this repo to test LaneNet in TuSimple.
