### ISSUE TITLE
is there any demo video?

### ISSUE THREAD

**Issue by mengzhibin** [cardwing/Codes-for-Lane-Detection#133]
from the paper, we can see the great progress of this method on culane. are there any demo videos output by this model trained with culane dataset? what's more, I mean the demo videos are not from culane videos for which we can know the model's generalization. Thanks very much.

**Comment by cardwing** [comment]
Performance on CULane video sequences:
https://drive.google.com/open?id=1EGH1Yhyrh62uW9aEqusdMtxGVv8niu4c

Performance on BDD100K:
https://drive.google.com/open?id=1tcYOtXOGSlpAjwy_rtVUocrFpp9fWmG_

**Comment by ycdhqzhiai** [comment]
@cardwing CULane 测试原始视频能发一份给我吗？感谢！！
