### ISSUE TITLE
test my our images with scnn-tf culane model

### ISSUE THREAD

**Issue by mengzhibin** [cardwing/Codes-for-Lane-Detection#134]
I test the ckpt you uploaded using my own images and the results are very bad as shown below. I dont know it's because culane dataset or scnn model.
![sence_0_2019-7-23-15-17-12_100](https://user-images.githubusercontent.com/16495929/63336196-4fdb3e80-c371-11e9-8ec3-1901ffad755f.png)
![sence_0_2019-7-23-15-17-12_100_1_avg](https://user-images.githubusercontent.com/16495929/63336198-4fdb3e80-c371-11e9-9998-6dd5f2588da0.png)
![sence_0_2019-7-23-15-17-12_100_2_avg](https://user-images.githubusercontent.com/16495929/63336199-5073d500-c371-11e9-8cc1-b12934619638.png)
![sence_0_2019-7-23-15-17-12_100_3_avg](https://user-images.githubusercontent.com/16495929/63336200-5073d500-c371-11e9-97da-15f65f18cb09.png)
![sence_0_2019-7-23-15-17-12_100_4_avg](https://user-images.githubusercontent.com/16495929/63336201-5073d500-c371-11e9-8911-3e51247b4ad9.png)
![sence_0_2019-7-23-15-17-12_120](https://user-images.githubusercontent.com/16495929/63336211-58337980-c371-11e9-83e2-561f06e4f72d.png)
![sence_0_2019-7-23-15-17-12_120_1_avg](https://user-images.githubusercontent.com/16495929/63336213-58cc1000-c371-11e9-910d-43366e35a89d.png)
![sence_0_2019-7-23-15-17-12_120_2_avg](https://user-images.githubusercontent.com/16495929/63336214-58cc1000-c371-11e9-9aba-fb7cc90e983f.png)
![sence_0_2019-7-23-15-17-12_120_3_avg](https://user-images.githubusercontent.com/16495929/63336215-58cc1000-c371-11e9-98c5-2e0c6bda3483.png)
![sence_0_2019-7-23-15-17-12_120_4_avg](https://user-images.githubusercontent.com/16495929/63336216-5964a680-c371-11e9-9b7c-3ad308553432.png)
![sence_0_2019-7-23-15-17-12_140](https://user-images.githubusercontent.com/16495929/63336229-5f5a8780-c371-11e9-87fc-00388b22a012.png)
![sence_0_2019-7-23-15-17-12_140_1_avg](https://user-images.githubusercontent.com/16495929/63336231-5ff31e00-c371-11e9-85fc-2edd2a442849.png)
![sence_0_2019-7-23-15-17-12_140_2_avg](https://user-images.githubusercontent.com/16495929/63336233-5ff31e00-c371-11e9-967a-c871e1f1f2ea.png)
![sence_0_2019-7-23-15-17-12_140_3_avg](https://user-images.githubusercontent.com/16495929/63336234-5ff31e00-c371-11e9-83a3-7633e0c37fa9.png)
![sence_0_2019-7-23-15-17-12_140_4_avg](https://user-images.githubusercontent.com/16495929/63336236-608bb480-c371-11e9-980c-64e40e529700.png)

**Comment by mengzhibin** [comment]
I doubt culane trained model can only perform good on culane dataset. Appreciate demo videos(for example the above images that are not from culane dataset, tusimple, bdd) can show generalization of this method. Thank very much.

**Comment by cardwing** [comment]
Maybe you need to handle the dataset gap by using adversarial learning methods.
