### ISSUE TITLE
Getting lane markings on test images!

### ISSUE THREAD

**Issue by sicarioakki** [cardwing/Codes-for-Lane-Detection#135]

**Comment by amarsaroj** [comment]
getting inconsistent/incorrect results when tested the model against road images. 

How to create own dataset annotations ? Any help/link please. Thank you.

**Comment by cardwing** [comment]
@sicarioakki @amarsaroj Can you specify the problem you met?

**Comment by sicarioakki** [comment]
I have generated the probability map by running test_lanenet.py.
Then later, I run main.m to get lane coordinates under tools/prob2lines/output/ 
But, how to produce lane markings on images as shown in the paper??

**Comment by cardwing** [comment]
Just modify the source codes in `tools/lane_evaluation/src` to save output predictions and then make again. Another solution is just set variable `show` be true in `main.m`. As to the attention maps, please refer to [this issue](https://github.com/cardwing/Codes-for-Lane-Detection/issues/131).

**Comment by sicarioakki** [comment]
Okay will try doing that..Thanks!

**Comment by sicarioakki** [comment]
How do i save the lane marking images and corresponding probmaps?

**Comment by sicarioakki** [comment]
I want to save all the resulting images of CULane dataset at once

**Comment by cardwing** [comment]
Please refer to [testLane.lua](https://github.com/cardwing/Codes-for-Lane-Detection/blob/master/ENet-Label-Torch/testLane.lua) for more details.
