### ISSUE TITLE
cuda_visible_device problem

### ISSUE THREAD

**Issue by imaneelhg** [cardwing/Codes-for-Lane-Detection#138]
i have cuda installed but anstill have error  : cuda_visible_device is not recognized .
im on windows and i work with conda prompt .
i did some online search and i added set in front of cuda_visible_device . the error is not there anymore but nothing happens after i write that .

(tensorflow_gpu) C:\Users\lane-detection-model>CUDA_VISIBLE_DEVICES="0" python tools/test_lanenet.py --weights_path /model_culane-71-3/culane_lanenet_vgg_2018-12-01-14-38-37.ckpt-10000 --image_path /demo_file/test_img.txt
'CUDA_VISIBLE_DEVICES' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.

(tensorflow_gpu) C:\Users\lane-detection-model>set CUDA_VISIBLE_DEVICES="0" python tools/test_lanenet.py --weights_path /model_culane-71-3/culane_lanenet_vgg_2018-12-01-14-38-37.ckpt-10000 --image_path /demo_file/test_img.txt

here what happens after:
(tensorflow_gpu) C:\Users\lane-detection-model>

**Comment by cardwing** [comment]
I have not tested SCNN-Tensorflow in Windows.

**Comment by imaneelhg** [comment]
okey thank you for your response .
can u give me a brief explanation on the probability maps that u used or what are the output of your CNN . thank you again

**Comment by cardwing** [comment]
Please refer to [our paper](http://personal.ie.cuhk.edu.hk/~ccloy/files/iccv_2019_sad.pdf) for more details.
