### ISSUE TITLE
ImportError: No module named utils.transforms

### ISSUE THREAD

**Issue by sicarioakki** [cardwing/Codes-for-Lane-Detection#139]
How to solve this issue?

**Comment by cardwing** [comment]
Please add `export PYTHONPATH=/path/to/Codes-for-Lane-Detection/ERFNet-CULane-PyTorch` in your .bashrc (use your path).

**Comment by sicarioakki** [comment]
Thank you very much! Will try it out and let you know..
Btw is the given implementation if ERFNET only GPU compatible??

**Comment by cardwing** [comment]
Yes.

**Comment by khan958** [comment]
@cardwing 
  File "C:/Users/Jayden/Human_Pose_Estimation/lib/dataset/JointsDataset.py", line 20, in <module>
    from utils.transforms import get_affine_transform

ModuleNotFoundError: No module named 'utils.transforms'
