### ISSUE TITLE
ERFNet pretrained model

### ISSUE THREAD

**Issue by jcdubron** [cardwing/Codes-for-Lane-Detection#140]
Thanks for your codes for lane detection. I wonder where the ERFNet pretrained model comes from or could you provide more details about pretraining setting?

In `train_erfnet.sh`, the image shape is (208, 976) that does not correspond to the ratio of (590, 1640). Why?

**Comment by cardwing** [comment]
I just use the original ERFNet model as the pretrained model, which is trained on Cityscape dataset. As to the image size, I crop the original image to remove the upper part which is totally background and then resize the cropped image to (208, 976).

**Comment by jcdubron** [comment]
Thank you for your reply.
