### ISSUE TITLE
Can't find the "self attention" module in pytorch version

### ISSUE THREAD

**Issue by Vincent-Hoo** [cardwing/Codes-for-Lane-Detection#141]
I've read the code of "train_erfnet.py". I couldn't find any clue of self attention network. The total loss is just the sum of segmentation loss and existence loss, which is not what the paper states.

**Comment by cardwing** [comment]
Yes. The PyTorch code does not have the self-attention module but the original torch code has. You can add the self-attention module to the PyTorch code.
