### ISSUE TITLE
Not the expected outcome when using a pre-trained model in ERFnet-CULane-pytorch

### ISSUE THREAD

**Issue by zhoufeng2** [cardwing/Codes-for-Lane-Detection#143]
Thank you for you  lane-detection code. When i test your pre-trained model in ERFnet-CULane-pytorch , i found the precision is not the expected result, the precision in the normal sence is just 35%, is there some parameters i should be adjusted?

**Comment by cardwing** [comment]
Do you use the ERFNet_trained.tar? It runs well in my local server.

**Comment by zhoufeng2** [comment]
yes, it is  ERFNet_trained.tar.  But the result is not the same as the reported one.  Could it be because it's a single gpu in my local?

**Comment by cardwing** [comment]
I don't think so. The performance should be the same even if you use just one GPU. The following is the snapshot of the final performance I have just obtained.

![73_1](https://user-images.githubusercontent.com/23656119/64095867-ab0a2980-cd92-11e9-9ce5-dc0efe5cc38b.png)

**Comment by zhoufeng2** [comment]
I am so confused that the results differ considerably. The following is the final preformance in my local:

anno_dir: ../../dataset/CULane/
detect_dir: ../../tools/prob2lines/output/vgg_SCNN_DULR_w9/
im_dir: ../../dataset/CULane/
list_im_file: ../../list/test.txt
width_lane: 30
iou_threshold: 0.5
im_width: 1640
im_height: 590
-----------------------------------
Evaluating the results...
tp: 45191 fp: 59005 fn: 17319
finished process file
precision: 0.433711
recall: 0.72294
Fmeasure: 0.542164

**Comment by cardwing** [comment]
That's weird. I have not met this problem before. Please find out the cause by yourself.
