### ISSUE TITLE
About SAD Section

### ISSUE THREAD

**Issue by ABexit** [cardwing/Codes-for-Lane-Detection#144]
Thx for you sharing , however, where is the SAD Section in those code??

**Comment by cardwing** [comment]
You can find them in the torch codes, i.e., ENet-Label-Torch.

**Comment by ABexit** [comment]
> You can find them in the torch codes, i.e., ENet-Label-Torch.

Thx a lot, but I'm sorry, I hadn't found which XX.lua contain it, can you tell me specifically?  Best wishes.

**Comment by cardwing** [comment]
See [this file](https://github.com/cardwing/Codes-for-Lane-Detection/blob/master/ENet-Label-Torch/models/init.lua#L162). You can find SAD in the model structure and loss function.

**Comment by ABexit** [comment]
> See this file. You can find SAD in the model structure and loss function.

Thx for your help and kindness. You CUHK really do many awesome work on lane detection.  :)

**Comment by cardwing** [comment]
You are welcome.
