### ISSUE TITLE
what the difference for existence label between [0 1 1 1] and [1 1 1 0] in CULanes?

### ISSUE THREAD

**Issue by zimurui** [cardwing/Codes-for-Lane-Detection#147]
Hi, thank you for your share.  I'm confused about the training data making process. 
when making existence label, what the difference between [0,1,1,1] and [1,1,1,0]  when there are three lanes in training dataset?

**Comment by cardwing** [comment]
The four values in the existence vector denote the existence of four lanes, i.e., most left lane, left lane, right lane and most right lane.
