### ISSUE TITLE
About attention's shape

### ISSUE THREAD

**Issue by fosaken** [cardwing/Codes-for-Lane-Detection#148]
Thx for sharing!
I'm not familiar with lua, so I'm trying to build a model with python, but I got a question:
Assuming I got an output of some block with shape (n, c, h, w), after the mapping function G and the upsampling B, the map should be with shape(n, 1, h, w). The question is how can I perform softmax on a 1-channel map, could it be with dim=0, even 2 or 3?  What shape should the attention map be with in this case?

**Comment by cardwing** [comment]
Please refer to [this issue](https://github.com/cardwing/Codes-for-Lane-Detection/issues/145).

**Comment by fosaken** [comment]
> Please refer to [this issue](https://github.com/cardwing/Codes-for-Lane-Detection/issues/145).

thank u very much.
I did not get the '_spatial_' before.
