### ISSUE TITLE
anyone has the generating line code using  opencv-python ，could share ？ ，thanks！！

### ISSUE THREAD

**Issue by noobliang** [cardwing/Codes-for-Lane-Detection#151]

**Comment by cardwing** [comment]
Please provide more details here.

**Comment by noobliang** [comment]
Sorry, I replied too late.  and thanks you reply!  just  ,,
I dont understand the matlib code  to generate lane coordinates from probablity maps.  About：
` probMaps = uint8(zeros(208,976,3));
        figure(1)
        imshow(img); hold on;
        for j=1:4
            color = ['g','b','r','y'];
            if exist{j}=='1'
                for m=1:pts
                    if coordinates(j,m)>0
                        plot(uint16(coordinates(j,m)*1640/976),590-(m-1)*20,strcat('.',color(j)),'markersize',30);
                    end
                end
            end`
And   `for i=1:18
               lineId = uint16(208-(i-1)*20/350*208);`
I doubt  this  mapping transformation  some error,  why  is  shape  208*976 ..  thanks !!

**Comment by cardwing** [comment]
I crop the upper part of the input image which has no lanes. Then, the resized shape is 208 x 976 instead of 288 x 800.

**Comment by noobliang** [comment]
oh，thanks  !
