### ISSUE TITLE
BDD labels pre-processing

### ISSUE THREAD

**Issue by amrit110** [cardwing/Codes-for-Lane-Detection#152]
Hi, in the paper you mention that for BDD you estimate the middle point of adjacent lane markings because you have 2 lines instead of 1, and then you apply a dilation operation on top of it to make the training targets denser. Could you share the exact implementation of this to be able to reproduce your results?

**Comment by cardwing** [comment]
I have put the generated labels on google drive in ENet-BDD100K-Torch repo.
