### ISSUE TITLE
关于c++代码的make问题

### ISSUE THREAD

**Issue by 2571630192** [cardwing/Codes-for-Lane-Detection#153]
麻烦问一下，关于culane数据集的代码在编译时出现的一个报错  tools/lane-evaluation/src/lane_compare文件里的43 47行的line我好像没有找到在哪声明的

**Comment by cardwing** [comment]
Line function belongs to OpenCV. You can find details [here](https://docs.opencv.org/2.4/modules/core/doc/drawing_functions.html#line).
