### ISSUE TITLE
about  ERFNet   ， test_erfnet.py

### ISSUE THREAD

**Issue by noobliang** [cardwing/Codes-for-Lane-Detection#155]
why  I  run the test_erfnet.py ,it has no response，and no displaying error , , I check it ，its stuck in ` model = torch.nn.DataParallel(model, device_ids=range(args.gpus)).cuda()` .., , ,

**Comment by cardwing** [comment]
What is your video memory? It may be caused by inefficient video memory.

**Comment by noobliang** [comment]
> What is your video memory? It may be caused by insufficient video memory.

I had set gpus  0, imagesize  256*512,batchsize 1,,, but   I found  it just use my  cpu, a core is 100% 
,,,,the using rate of  gpu is 0% ... I dont know why..

**Comment by cardwing** [comment]
You may need to check if pytorch-GPU is correctly installed.

**Comment by noobliang** [comment]
> You may need to check if pytorch-GPU is correctly installed.

but `if torch.cuda.is_available():` is  ok,   　　thanks for your reply  ,, let me ponder it then..
