### ISSUE TITLE
Generate pred_json file using pred_json.py

### ISSUE THREAD

**Issue by nikhilbv** [cardwing/Codes-for-Lane-Detection#157]
Hi, 
Referring to this issue https://github.com/MaybeShewill-CV/lanenet-lane-detection/issues/286#issuecomment-523752395, I am trying to run `ENet-TuSimple-Torch` so that I will be able to modify the `pred_json.py` to generate the pred_json file for the custom dataset in lanenet.
I have a couple of doubts-
1. I see that in `list6/list6_train.txt`, it has `/clips/0313-1/6040/20.jpg /segGT6/0313-1/6040/20.png 0 1 1 1 1 0` and original tusimple dataset has `/image/0000.png /gt_image_binary/0000.png /gt_image_instance/0000.png`. 
a. What is `0 1 1 1 1 0`?
b. Is there a script to generate data in `/clips/0313-1/6040/20.jpg /segGT6/0313-1/6040/20.png 0 1 1 1 1 0` format?

**Comment by cardwing** [comment]
`0 1 1 1 1 0` are the existence value of each lane (1 denotes exist and 0 denotes not exist). You can just use a script to judge whether a specific lane exists in the label map.
