### ISSUE TITLE
Installation instructions unclear - "vgg.npy" missing

### ISSUE THREAD

**Issue by zorrobyte** [cardwing/Codes-for-Lane-Detection#158]
"    Download VGG-16:

Download the vgg.npy here and put it in SCNN-Tensorflow/lane-detection-model/data.

* There isn't a vgg.npy file in the repo "https://github.com/machrisaa/tensorflow-vgg" - which file do I use?
![image](https://user-images.githubusercontent.com/7257172/65329949-8f22c800-db87-11e9-929d-1871d68556e7.png)

**Comment by zorrobyte** [comment]
I found the file. It's linked to a MEGA repo in the readme and isn't immediately clear 
https://mega.nz/#!YU1FWJrA!O1ywiCS2IiOlUCtCpI6HTJOMrneN-Qdv3ywQP5poecM

**Comment by cardwing** [comment]
Thanks for pointing it out. I will fix it soon.
