### ISSUE TITLE
the error when run the ENet-TuSimple-Torch

### ISSUE THREAD

**Issue by andeyeluguo** [cardwing/Codes-for-Lane-Detection#160]
the error is like this:

data created
data loaded
data created
data loaded
data loaded
/home/zhaodz/program/torch/install/bin/lua: .../program/torch/install/share/lua/5.2/threads/threads.lua:183: [thread 1 callback] ./dataloaderE.lua:90: bad argument #1 to 'size' (dimension 3 out of range of 2D tensor at /home/zhaodz/program/torch/pkg/torch/generic/Tensor.c:19)
stack traceback:
        [C]: in function 'size'
        ./dataloaderE.lua:90: in function <./dataloaderE.lua:77>
        (...tail calls...)
        [C]: in function 'xpcall'
        .../program/torch/install/share/lua/5.2/threads/threads.lua:234: in function 'callback'
        ...dz/program/torch/install/share/lua/5.2/threads/queue.lua:65: in function <...dz/program/torch/install/share/lua/5.2/threads/queue.lua:41>
        [C]: in function 'pcall'
        ...dz/program/torch/install/share/lua/5.2/threads/queue.lua:40: in function 'dojob'
        [string "  local Queue = require 'threads.queue'..."]:15: in main chunk
stack traceback:
        [C]: in function 'error'
        .../program/torch/install/share/lua/5.2/threads/threads.lua:183: in function 'dojob'
        ./dataloaderE.lua:141: in function 'for iterator'
        testLaneE.lua:75: in main chunk
        [C]: in function 'dofile'
        ...gram/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
        [C]: in ?

it seems that when it cannot resize 3 to 2. I do not know why other people did not meet this problem.

**Comment by andeyeluguo** [comment]
to install torch on cuda9.0, I add this code in .bashrc file

export TORCH_NVCC_FLAGS="-D__CUDA_NO_HALF_OPERATORS__"

**Comment by cardwing** [comment]
What is your batch size? It seems that the segmentation label only has two dimensions.

**Comment by andeyeluguo** [comment]
I just use your code and change nothing.....

**Comment by cardwing** [comment]
That's weird. Everything runs ok in my local server.

**Comment by andeyeluguo** [comment]
when I 

print(sample.input:size())

it shows
3
720
1280
[torch.LongStorage of size 3
]

when I 
print(sample.segLabel)
it prints
[111....111]matrix,whose size is 720*1280

Is it the right phenomenon?

**Comment by andeyeluguo** [comment]
it seems the segLabel only has two size

**Comment by andeyeluguo** [comment]
I change the code
segLabel: resize(segLabel:size(1),segLabel:size(2))
to
segLabel: resize(segLabel:size(0),segLabel:size(1))

it can run, why

**Comment by cardwing** [comment]
Quite weird. I have not met this before.
