### ISSUE TITLE
evaluate problem

### ISSUE THREAD

**Issue by xuchengggg** [cardwing/Codes-for-Lane-Detection#162]
您好，我下载了预训练权重在CULane test跑出来最终的F1 measure是70.94，在lanenet_data_processor_test.py中在`img_casted = tf.cast(img_resized, tf.float32` 下面加了`img_casted = img_casted[:,:,::-1]` 并且将mean从RGB改为了BGR，那这个和71.3的差距是由于tensorflow引起的嘛， 我的tensorflow版本是1.12。 或者是哪里还存在错误？

**Comment by cardwing** [comment]
If you do not change the code (i.e., do not add `img_casted = img_casted[:,:,::-1]` and change the mean), what is your performance? The image read by tensorflow should be in the order of RGB instead of BGR.

**Comment by xuchengggg** [comment]
我刚开始没有改的时候，没有计算整个训练集的F1 measure, 但是在normal数据集上是82左右，改了以后是89.9，然后我看一些issure里您说训练是基于BGR的，所以输入数据要转成BGR？

**Comment by cardwing** [comment]
Yes. The trained TensorFlow model is based on BGR. As to the drop in performance, I don't know the reason. But you may try our ERFNet model or ENet model which achieve much better performance and have much faster convergence speed.

**Comment by xuchengggg** [comment]
Thank you. I will try that one, have a good night!

**Comment by BoSeal** [comment]
> 
> 
> 您好，我下载了预训练权重在CULane test跑出来最终的F1 measure是70.94，在lanenet_data_processor_test.py中在`img_casted = tf.cast(img_resized, tf.float32` 下面加了`img_casted = img_casted[:,:,::-1]` 并且将mean从RGB改为了BGR，那这个和71.3的差距是由于tensorflow引起的嘛， 我的tensorflow版本是1.12。 或者是哪里还存在错误？

@xuchengggg ,您好，我和你遇到相同的问题，请问最后你知道什么原因？
