### ISSUE TITLE
The lane evaluation in CULane is accelerated about 20 x

### ISSUE THREAD

**Issue by cardwing** [cardwing/Codes-for-Lane-Detection#163]
The newly added code for the lane evaluation in CULane can fasten the evaluation process about 20 x. Just compile with make in `ERFNet-CULane-PyTorch/tools/lane_evaluation/` (make clean first). If you use OpenCV 2.4.8, please remove opencv_imgcodecs in `ERFNet-CULane-PyTorch/tools/lane_evaluation/Makefile` and change `#include <opencv2/imgproc.hpp>` to `#include <opencv2/imgproc/imgproc.hpp>` in `ERFNet-CULane-PyTorch/tools/lane_evaluation/include/lane_compare.hpp`. Thanks @atranitell

**Comment by atranitell** [comment]
Yeah, the newest lane evaluation tool could directly used in OpenCV 3 above.
Thank @cardwing points that.
