### ISSUE TITLE
Matrix dimensions must agree error when running prob2lines/main.m in show mode.

### ISSUE THREAD

**Issue by snarb** [cardwing/Codes-for-Lane-Detection#164]
I am getting 

> Matrix dimensions must agree.
> 
> Error in main (line 52)
>             probMaps(:,:,mod(j,3)+1) = probMaps(:,:,mod(j,3)+1) + probMap;

error if setting 

> show = true;  % set to true to visualize

flag. Without this flag everything works without errors.

> size(probMaps)
>    208   976     3

**Comment by cardwing** [comment]
Maybe you can print the shape of `probMap` and `probMaps` to debug when setting `show` to be true.
