### ISSUE TITLE
SCNN tensorflow 模型输出节点

### ISSUE THREAD

**Issue by ycdhqzhiai** [cardwing/Codes-for-Lane-Detection#166]
您好，我使用CULData数据集重新跑了下trian_vgg.sh，查看了下保存的模型节点名称，跟您上传到goole盘里面的模型节点名称对比了下发现完全不同。
![image](https://user-images.githubusercontent.com/12273405/66617909-a181a600-ec09-11e9-94ae-dff4e1459a09.png)

左边是train_vgg.sh保存的模型，右边是google盘里面的模型，自己训练的这个多了很多op，我看了下模型大小，google盘里面的.meta文件只有3M多，而自己训练的.meta文件却有100多M，我想问下是不是模型进过了什么处理，tf小白希望得到回复，谢谢！！！

**Comment by cardwing** [comment]
The .meta file mainly stores the graph and the original model is saved as usual. However, the code of the trained model is slightly different from the latest version. And you can find that version (Commits on Dec 12, 2018, 53b79fd) in the commit history.

**Comment by ycdhqzhiai** [comment]
非常感谢！！！
