### ISSUE TITLE
where is SAD module in ERFNet-CULane-PyTorch？I don't find it.

### ISSUE THREAD

**Issue by hewumars** [cardwing/Codes-for-Lane-Detection#169]
where is SAD module in ERFNet-CULane-PyTorch？I don't find it.

**Comment by cardwing** [comment]
SAD module is in ENet-Label-Torch. You can add SAD in ERFNet-CULane-PyTorch to get better performance.

**Comment by github-luffy** [comment]
Excuse me, how to add SAD?,thanks

**Comment by wangzeyu135798** [comment]
Which file contains SAD modules in ENet-Label-Torch？
