### ISSUE TITLE
How to annotate other lane markings like zebra lines and stop lines

### ISSUE THREAD

**Issue by chenchaohui** [cardwing/Codes-for-Lane-Detection#17]
Hi, cardwing.
     As I know, you have also studied VPGNet.  I would like to ask you a quetion. After reading his paper, we can know, the author use spline to annotate the lane first, ang the convert it to grid cell annotation.  However, how to annotate other marks like zebra line, stop line direct arrow and so on. waiting for your answer.

**Comment by cardwing** [comment]
@chenchaohui , you can refer to [BDD100K](http://bdd-data.berkeley.edu/) to see their annotations (i.e., the lane markings). To be more specific, they use two boundary lines to represent zebra lines, etc. However, I have to say that their annotations are not ideal since it is much difficult to make models learn to segment so many lines.

**Comment by chenchaohui** [comment]
they use two boundary lines to represent zebra lines?  can you give me an example.

**Comment by cardwing** [comment]
See the following picture, the zebra line is labelled via two lines.

![zebra_line](https://user-images.githubusercontent.com/23656119/49789817-dd3cac80-fd67-11e8-8b65-9ee6514655e9.png)

**Comment by chenchaohui** [comment]
Firstly，thanks cardwing very much.  As I know, the method of annotation in VPGNet is grid cell like the picture below.
![34760265-000ad6d4-f61a-11e7-8391-c7d6e3df05fb](https://user-images.githubusercontent.com/11752130/49850542-d6ba3d80-fe18-11e8-93fc-aed85305199e.png)
and  your annotated picture above just finished the first step of annotation ,right? then we shuold convert annotation information to grid cell annotation using the script of vpg_annot_v1.m ?  and if I have converted the annotation to the form of grid cell, How should I visualize it. Is there a script to finish the visualizal step. Besides, How to annotate the arrow marks onthe the surface of roads?

**Comment by cardwing** [comment]
@chenchaohui, I used VPGNet only for a rough test and therefore I am not familiar with the annotation mechanism of it. You can directly raise issues in the VPGNet repo.
