### ISSUE TITLE
Performance on other dastasets

### ISSUE THREAD

**Issue by txytju** [cardwing/Codes-for-Lane-Detection#170]
Thanks for your great work!
I have noticed that this paper focus on lane detection, which can be viewed as a single class semantic segmentation problem. So my question is that have you tried your method on classes in other datasets, like car or pedestrain class in CityScapes? Does this method improve their performance? Thanks!

**Comment by cardwing** [comment]
I have also applied SAD to PSPNet and obtain around 0.6 point performance gains. Besides, using both labels and attention maps of deep layers as distillation targets can further enhance the final performance.

**Comment by txytju** [comment]
> obtain around 0.6 point performance gains
Which class did you mean?

**Comment by cardwing** [comment]
The overall mIoU.
