### ISSUE TITLE
Models failing to learn in a extremely curved road scenario

### ISSUE THREAD

**Issue by snarb** [cardwing/Codes-for-Lane-Detection#173]
When training on my toy data-set,  I have notices that for scenario with high curved road models(both ENet and SCNN) are learning extremely bad they are almost cant learn effectively for this scenario.  Please take a look at the picture of such curve. 

![Screenshot from 2019-10-17 04-43-58](https://user-images.githubusercontent.com/4518007/66994122-c3ac7580-f09a-11e9-98a0-d396ff8f632e.png)

I think this corner case reflects one models limitations. What do you think about this? I understand that higher resolution can helps, but results with such curve results are so bad that I think that this is not a good solution to a problem and we need some architecture changes in segmentation part.

**Comment by cardwing** [comment]
Yes. I also find that almost all models struggle in curved road prediction. A naive solution is hard example mining or curved-road-oriented data augmentation (e.g., random cropping, rotation, flipping). As to architecture changes, you may add FPN to the backbone model to combine low-level details with high-level semantics to enhance the performance.
