### ISSUE TITLE
torch / cuda / cudnn version

### ISSUE THREAD

**Issue by TommyTang930** [cardwing/Codes-for-Lane-Detection#176]
Thank you for your contribution ^_*
it is really helpful. 
I read the README file, I am confused why the torch, cuda, cudnn version is so low ? 
Can I test all of these projects on pytorch => 1.0 ,cuda =>9.0, cudnn => 7.0 ?

**Comment by cardwing** [comment]
Because the sync BN only works for PyTorch 0.3.0. If you test on higher versions, you need to replace the original sync BN module.

**Comment by TommyTang930** [comment]
okay, If I install the pytorch==0.3.0, should I also degrade the cuda and cudnn version ?

**Comment by TommyTang930** [comment]
@cardwing 
您好，向您请教一个问题：近期在看LaneNet项目，在TuSimple的test数据集上测试完后，输出了test数据集的车道线检测效果图。请问如何生成pred json文件，用于计算accuracy, fp, fn ? 这个问题让我纠结很长时间了，麻烦点拨一下，非常感谢 ～

**Comment by cardwing** [comment]
Yes, you need to degrade the version of cuda and cudnn if installing pytorch 0.3.0. As to the generation of pred.json file, you need to find it out by yourself since I only tested LaneNet in CULane.

**Comment by TommyTang930** [comment]
@cardwing 
hi, you tested LaneNet in CULane, how did you transfer the format of CULane into the format of TuSimple ?
