### ISSUE TITLE
TuSimple Accuracy, FP, FN 

### ISSUE THREAD

**Issue by TommyTang930** [cardwing/Codes-for-Lane-Detection#177]
您好，在写脚本文件，遇到问题如下：

问题描述

LaneNet训练完TuSimple的Training数据集后，用模型在TuSimple的test数据集上inference，获得了每一张test数据集上图片的车道线检测效果。通过查看源代码，可以获取检测后得到的每条车道线的坐标，比如：
source image :  ./data/tusimple_test_image/0.jpg
车道线数量 :  4
第1条车道线的shape :  (2522, 2)
第2条车道线的shape :  (2420, 2)
第3条车道线的shape :  (1560, 2)
第4条车道线的shape :  (1001, 2)
原图的shape :  (720, 1280, 3)

不过，我读取了一下TuSimple的test数据集的test_label.json文件，其格式是："lanes", "h_samples", "raw_file"，尤其是lanes字段，其包含的是每条车道线的横坐标，每条车道线的length固定是 56 ，比如：
[-2, -2, -2, -2, -2, -2, -2, 616, 591, 564, 538, 509, 480, 451, 422, 391, 358, 325, 292, 259, 227, 194, 161, 128, 95, 62, 29, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2]

请问：如何将在test数据集上检测得到的车道线的横坐标改成这种格式呢？

非常感谢 ～

**Comment by cardwing** [comment]
More details can be found in the corresponding folder. Please find them out by yourself.
