### ISSUE TITLE
CULane dataset path ( training )

### ISSUE THREAD

**Issue by TommyTang930** [cardwing/Codes-for-Lane-Detection#178]
@cardwing 
Thanks a lot for your contribution ^_^
I got the Error information : 
Not found: driver_23_30frame/05170850_0722.MP4/00290.jpg; No such file or directory
Not found: driver_23_30frame/05170850_0722.MP4/00290.jpg; No such file or directory
	 [[{{node data_augmentation_1/ReadFile}}]]
	 [[data_augmentation_1/DecodePng/_59]]
...............

My solutions:
(1) First, I read all issues about this problem. I have tried many methods. But, it doesn't work.
(2) Here what I did, I wrote a python script to change the relative path to absolute path: (For example)

Before (relative path): 
/driver_23_30frame/05151649_0422.MP4/00000.jpg /laneseg_label_w16/driver_23_30frame/05151649_0422.MP4/00000.png 1 1 1 1

After (absolute path): 
~/Desktop/LaneNet/SCNN-Tensorflow/lane-detection-model/data/CULane~/Desktop/LaneNet/SCNN-Tensorflow/lane-detection-model/data/CULane/driver_23_30frame/05151649_0422.MP4/00000.jpg ~/Desktop/LaneNet/SCNN-Tensorflow/lane-detection-model/data/CULane~/Desktop/LaneNet/SCNN-Tensorflow/lane-detection-model/data/CULane/laneseg_label_w16/driver_23_30frame/05151649_0422.MP4/00000.png 1 1 1 1

Finally : 
I got the same errors. So, what do you suggest me to do ? Thank you very much. 

--------------------------------------------------------------------------------------------------------------------------------
My Python script : 
import argparse
import os

def init_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--root_path', type=str, help='the root path of CULane')
    parser.add_argument('--file1', type=str)
    parser.add_argument('--file2', type=str)
    return parser.parse_args()

def add_content(txt, file1, file2):
	with open(file1) as fr, open(file2, 'w') as fw:
		all_paths = fr.readlines() # 读取每一行
		for path in all_paths:
			index = path.find("/laneseg_label_w16")
			part1 = path[0:index] # 截取前半部分
			print("part1 : ", part1)
			part2 = path[index:] # 截取后半部分
			print("part2 : ", part2)
			new_path = txt+part1+txt+part2 # 拼接新路径
			print("go on processing ...")
			fw.write(new_path)	# 写入新文件		
	os.remove(file1) # 删除原有文件
	os.rename(file2, file1) # 重命名新文件

if __name__ == "__main__":
	args = init_args()

	add_content(args.root_path, args.file1, args.file2)

**Comment by cardwing** [comment]
Can you cd the absolute path? I guess the problem lies in the file path. And have you added the path to the SCNN-Tensorflow in the .bashrc?
