### ISSUE TITLE
ModuleNotFoundError: No module named 'torch.utils.checkpoint'

### ISSUE THREAD

**Issue by sieuwe1** [cardwing/Codes-for-Lane-Detection#184]
Hi

When u try to run python3 test_erfnet.py I get the following error:
```

`Traceback (most recent call last):
  File "test_erfnet.py", line 5, in <module>
    import torchvision
  File "/usr/local/lib/python3.6/dist-packages/torchvision/__init__.py", line 1, in <module>
    from torchvision import models
  File "/usr/local/lib/python3.6/dist-packages/torchvision/models/__init__.py", line 6, in <module>
    from .densenet import *
  File "/usr/local/lib/python3.6/dist-packages/torchvision/models/densenet.py", line 5, in <module>
    import torch.utils.checkpoint as cp
ModuleNotFoundError: No module named 'torch.utils.checkpoint'
```

My PyTorch version is 0.3.0.post4 from the following wheel: http://download.pytorch.org/whl/cu80/torch-0.3.0.post4-cp36-cp36m-linux_x86_64.whl 

I know it has something to do with my pytorch version but 0.3.0 is the right version?

I dont use Conda so i could'nt install pytorch 0.3.0 with that.

Greetings

Sieuwe

**Comment by cardwing** [comment]
The codes run well in my local server with PyTorch 0.3.0. However, you may try PyTorch 0.4.0 and change several lines of codes to check if it works.

**Comment by sieuwe1** [comment]
I am not really an PyTorch expert so that would probably be a lot of work for me. How did you install your PyTorch 0.3.0. Did you do it with Conda? 

Or via a downloaded wheel? If so can you share the link to that wheel then I can install it using pip.

Greetings,

Sieuwe
