### ISSUE TITLE
using with video

### ISSUE THREAD

**Issue by ixtiyoruz** [cardwing/Codes-for-Lane-Detection#185]
Hi, I wanted to use your model with the video that I have.  Here is the code:
```
require 'torch'
require 'nn'
require 'cunn'
require 'cudnn'
require 'lfs'
require 'paths'
local ffi = require 'ffi'
image = require 'image'
local models = require 'models/init_test'
local opts = require 'opts'
local DataLoader = require 'dataloader'
local checkpoints = require 'checkpoints'
local cv = require 'cv'
require 'cv.imgcodecs' -- reading/writing images
require 'cv.imgproc' -- image processing
require 'cv.highgui' -- GUI
require 'cv.videoio' -- Video input/output

opt = opts.parse(arg)
show = true    -- Set show to true if you want to visualize. In addition, you need to use qlua instead of th.

checkpoint, optimState = checkpoints.latest(opt)
model = models.setup(opt, checkpoint)
offset = 0
if opt.smooth then
   offset = 1
end

--print(model)
input = torch.CudaTensor()
function copyInputs(sample)
   input = input or (opt.nGPU == 1
      and torch.CudaTensor()
      or cutorch.createCudaHostTensor())
   print(sample:size())
   input:resize(640, 368, 3):copy(sample:resize(640, 368, 3))
   return input
end
--[[
function copyInputs(sample)
   input = input or (opt.nGPU == 1
      and torch.CudaTensor()
      or cutorch.createCudaHostTensor())
   input:resize(sample.input:size()):copy(sample.input)
   return input
end
]]

function sleep(n)
   os.execute("sleep " .. tonumber(n))
end


function process( scoremap )
   local avg = nn.Sequential()
   avg:add(nn.SpatialSoftMax())
   avg:add(nn.SplitTable(1, 3))
   avg:add(nn.NarrowTable(2, 4))
   local paral = nn.ParallelTable()
   local seq = nn.Sequential()
   seq:add(nn.Contiguous())
   seq:add(nn.View(1, 208, 976):setNumInputDims(2))
   local conv = nn.SpatialConvolution(1, 1, 9, 9, 1, 1, 4, 4)
   conv.weight:fill(1/81)
   conv.bias:fill(0)
   seq:add(conv)
   paral:add(seq)
   for i=1, 3 do
      paral:add(seq:clone('weight', 'bias','gradWeight','gradBias'))
   end
   avg:add(paral)
   avg:add(nn.JoinTable(1, 3))
   avg:cuda()
   return avg:forward(scoremap)
end

model:evaluate()
T = 0
N = 0
local cap = cv.VideoCapture{"test1.mp4"}
if not cap:isOpened() then
    print("Failed to open the default camera")
    os.exit(-1)
end

local _, frame = cap:read{}

print("while gacha keldik")
while(true)
do
   print(n)
   input = copyInputs(frame)
   local timer = torch.Timer()
   output = model:forward(input)
   local t = timer:time().real
   print('time: ' .. t)
   local scoremap = output[1]  --:double()
   if opt.smooth then
      scoremap = process(scoremap):float()
   else
      local softmax = nn.SpatialSoftMax():cuda()
      scoremap = softmax(scoremap):float()
   end
   if n > 1 then
      T = T + t
      N = N + 1
      print('avgtime: ' .. T/N)
   end
   timer:reset()
   local exist = output[2]:float()
   local outputn
   for b = 1, input:size(1) do
      outputn = scoremap[{b,{},{},{}}]
      line1 = outputn[{2-offset,{},{}}]
      line2 = outputn[{3-offset,{},{}}]
      line3 = outputn[{4-offset,{},{}}]
      line4 = outputn[{5-offset,{},{}}]
      lines = torch.FloatTensor(3,outputn:size(2),outputn:size(3)):fill(0)
      lines[{1,{},{}}] = line1
      lines[{2,{},{}}] = line2
      lines[{3,{},{}}] = line3
      lines[{1,{},{}}]:add(line4)
      lines[{3,{},{}}]:add(line4)
      img = frame*0.6 + lines*0.8
      cv.imshow{"images", img}
   end
   if cv.waitKey{30} >= 0 then break end
   cap:read{frame}
end
```

but it is throwing an error : 
```
qlua: /home/ixtiyor/torch/install/share/lua/5.1/nn/Container.lua:67: 
In 1 module of nn.Sequential:
In 1 module of nn.ConcatTable:
...torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:100: input has to contain: 3 feature maps, but received input of size: 1 x 640 x 368 x 3
stack traceback:
	[C]: in function 'assert'
	...torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:100: in function 'checkInputChanged'
	...torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:118: in function 'createIODescriptors'
	...torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:178: in function <...torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:176>
	[C]: in function 'xpcall'
	/home/ixtiyor/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	...e/ixtiyor/torch/install/share/lua/5.1/nn/ConcatTable.lua:11: in function <...e/ixtiyor/torch/install/share/lua/5.1/nn/ConcatTable.lua:9>
	[C]: in function 'xpcall'
	/home/ixtiyor/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	/home/ixtiyor/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	testLane.lua:94: in main chunk

WARNING: If you see a stack trace below, it doesn't point to the place where this error occurred. Please use only the one above.
stack traceback:
	[C]: at 0x7fed1876df50
	[C]: in function 'error'
	/home/ixtiyor/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
	/home/ixtiyor/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	testLane.lua:94: in main chunk

```

Please tell me what is wrong with the code

**Comment by ixtiyoruz** [comment]
if i use 208 and 976 for width and height the situation the same  : 

`...torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:100: input has to contain: 3 feature maps, but received input of size: 1 x 208 x 976 x 3`

**Comment by cardwing** [comment]
It seems that the fourth dimension of the input is not recognized as the channel dimension. I think the problem may lie in the batch size. Is your batch size set as 1? If yes, can you use a larger batch size?

**Comment by ixtiyoruz** [comment]
> It seems that the fourth dimension of the input is not recognized as the channel dimension. I think the problem may lie in the batch size. Is your batch size set as 1? If yes, can you use a larger batch size?

I found the problem it was because of the OpenCV image channel location so I changed it with:

```
local function HWCBGR_2_CHWRGB(im)
   return im:permute(3,1,2):index(1,torch.LongTensor{3,2,1})
end
....

frame = HWCBGR_2_CHWRGB(frame)
```
now I have another problem, which is:
`
 *** stack smashing detected ***: /home/ixtiyor/torch/install/bin/luajit terminated
`

**Comment by china56321** [comment]
> > It seems that the fourth dimension of the input is not recognized as the channel dimension. I think the problem may lie in the batch size. Is your batch size set as 1? If yes, can you use a larger batch size?
> 
> I found the problem it was because of the OpenCV image channel location so I changed it with:
> 
> ```
> local function HWCBGR_2_CHWRGB(im)
>    return im:permute(3,1,2):index(1,torch.LongTensor{3,2,1})
> end
> ....
> 
> frame = HWCBGR_2_CHWRGB(frame)
> ```
> 
> now I have another problem, which is:
> `*** stack smashing detected ***: /home/ixtiyor/torch/install/bin/luajit terminated`

Have you solved this problem ?  Could you paste the complete code ?

**Comment by ixtiyoruz** [comment]
> > > It seems that the fourth dimension of the input is not recognized as the channel dimension. I think the problem may lie in the batch size. Is your batch size set as 1? If yes, can you use a larger batch size?
> > 
> > 
> > I found the problem it was because of the OpenCV image channel location so I changed it with:
> > ```
> > local function HWCBGR_2_CHWRGB(im)
> >    return im:permute(3,1,2):index(1,torch.LongTensor{3,2,1})
> > end
> > ....
> > 
> > frame = HWCBGR_2_CHWRGB(frame)
> > ```
> > 
> > 
> > now I have another problem, which is:
> > `*** stack smashing detected ***: /home/ixtiyor/torch/install/bin/luajit terminated`
> 
> Have you solved this problem ? Could you paste the complete code ?

No, instead I implemented the code in python.

**Comment by china56321** [comment]
Could you paste the complete code ?发自我的华为手机-------- 原始邮件 --------发件人： ixtiyoruz <notifications@github.com>日期： 2020年6月4日周四 12:49收件人： cardwing/Codes-for-Lane-Detection <Codes-for-Lane-Detection@noreply.github.com>抄送： china56321 <china56321@126.com>, Comment <comment@noreply.github.com>主    题： Re: [cardwing/Codes-for-Lane-Detection] using with video (#185)



It seems that the fourth dimension of the input is not recognized as the channel dimension. I think the problem may lie in the batch size. Is your batch size set as 1? If yes, can you use a larger batch size?

I found the problem it was because of the OpenCV image channel location so I changed it with:
local function HWCBGR_2_CHWRGB(im)
   return im:permute(3,1,2):index(1,torch.LongTensor{3,2,1})
end
....

frame = HWCBGR_2_CHWRGB(frame)

now I have another problem, which is:
*** stack smashing detected ***: /home/ixtiyor/torch/install/bin/luajit terminated

Have you solved this problem ? Could you paste the complete code ?

No, instead I implemented the code in python.

**Comment by ixtiyoruz** [comment]
you can try my implementation [here](https://github.com/ixtiyoruz/segmentation_for_road_lines/)
