### ISSUE TITLE
如何在TuSimple测试集上获得Accuracy, FP, FN 参数

### ISSUE THREAD

**Issue by ashergaga** [cardwing/Codes-for-Lane-Detection#190]
请问SCNN-Tensorflow项目中，有可以获得Accuracy, FP, FN 参数的方法吗，生成预测的json文件？

**Comment by cardwing** [comment]
这个是没有的，不过你可以参考一下ENet-TuSimple-Torch里面的代码。那里面是有利用得到的.json文件来计算Accuracy，FP和FN的代码的。
