### ISSUE TITLE
Runtime

### ISSUE THREAD

**Issue by xuxiuzhi2627** [cardwing/Codes-for-Lane-Detection#192]
Hi, Could you tell me the runtime of SAD is testing on one image or 100 images?

**Comment by cardwing** [comment]
The final value of runtime is obtained after averaging the runtime of 100 images.

**Comment by BurkeyLai** [comment]
Hi!
I just ran the _test.sh_ in _ENet-Label-Torch_ for my first inference.
I got the output below:
```
...
...
data created	
data loaded	
data loaded	
1	
time: 2.1559779644012	
img: /driver_100_30frame/05251517_0433.MP4/00030.jpg	
/home/mec-lab/torch/install/bin/luajit: testLane.lua:124: attempt to index a number value
stack traceback:
	testLane.lua:124: in main chunk
	[C]: in function 'dofile'
	...-lab/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50
```
My question is the inference time, which take 2.156 second. 
Seems that it didn't match the runtime result mentioned in literature.
Am I do something wrong or misunderstand something?
