### ISSUE TITLE
SCNN实验问题

### ISSUE THREAD

**Issue by BoSeal** [cardwing/Codes-for-Lane-Detection#197]
**你好，对于SCNN中的CULane数据集，目前我有三个问题，向您请教。**
**问题1：**从test后得到的概率图中，我发现所有的lines.txt中，都存储的是“1”，请问你有了解过这个问题么？
**问题2：**在最后的评估中，我发现对Crossroad情景下车道线评估错误，我想知道为什么会出现这种情况？因为我是遵循您的SCNN训练模型进行的测试，错误评估结果如下：
model/CULane/list/test_split/test7_cross.txt
width_lane: 30
iou_threshold: 0.5
im_width: 1640
im_height: 590
-----------------------------------
Evaluating the results...
tp: 0 fp: 3323 fn: 0
no ground truth positive
finished process file
precision: 0
recall: -1
Fmeasure: 0

**问题3：我发现最后评估得到的F1-measure结果（除了Crossroad情景）都比您给出的结果要低于3%~5%，请问您是否在实验过程中加入了其他的处理方法？**

希望您可以为我解答以上疑惑，谢谢！

**Comment by psychotechTD** [comment]
I've met the same problem above, would be really thankful if got a reply

**Comment by cardwing** [comment]
1. lines.txt中不应该全是1，因为不是所有的场景都包含4条车道线
2. Crossroad场景只统计FP，SCNN的paper里面有提到
3. 有可能是代码重写以后某些函数的功能出现了一些偏差，你可以看一下之前的issue，我记得当时有给出解决措施，应该是使用某个commit的代码来跑就能得到一样的结果

**Comment by BoSeal** [comment]
@cardwing 好的，非常感谢！

**Comment by BoSeal** [comment]
这是我看到的之前的别人的问题：I check the order of VGG-MEAN in test_lanenet.py is [103.939, 116.779, 123.68] and lanenet_data_processor_test.py is [123.68, 116.779, 103.939] ,and lanenet_data_processor.py also is [123.68, 116.779, 103.939],so i think BGR is [123.68, 116.779, 103.939],is right?

@cardwing ,你好，我是直接从你的github里下载的SCNN代码，我看到你回复的消息（@xuefengxiaoyang, BGR is [103.939, 116.779, 123.68] instead of [123.68, 116.779, 103.939].），我的理解是：将lanenet_data_processor_test.py和lanenet_data_processor.py文件中[123.68, 116.779, 103.939]更改为[103.939, 116.779, 123.68]，而test_lanenet.py中[103.939, 116.779, 123.68]保持不变，如果我重新训练模型和测试，请问我这样修改代码，是否正确？
之后，我按照我的想法更改了VGG-MEAN，我发现训练过程得到的精度是没有更改前的1/2左右，所有关于VGG-MEAN 的更改，我有些疑惑，你可以解释的更加清楚些么？

**Comment by cardwing** [comment]
这个我记不太清了，不过如果修改RGB顺序的话，测试的时候应该要和训练的时候保持一致。
