### ISSUE TITLE
training  for SCNN

### ISSUE THREAD

**Issue by BoSeal** [cardwing/Codes-for-Lane-Detection#199]
@cardwing 
对于SCNN，我可以在你给出的预训练模型（model_culane-71-3.zip）的基础上，再对模型进行训练么？假如我把batch_size=4，那么又能否在预训练模型（model_culane-71-3.zip）的基础上进行再训练？

**Comment by cardwing** [comment]
可以的，不过微调的performance可能很难再涨了。

**Comment by BoSeal** [comment]
@cardwing ok,Thanks!
