### ISSUE TITLE
Run test problem

### ISSUE THREAD

**Issue by Endless-Hao** [cardwing/Codes-for-Lane-Detection#20]
hello , i try to run the test,but it still have problem,and i don't where and how to solve.All the need file i have prepared.
when i use this CUDA_VISIBLE_DEVICES="0" python tools/test_lanenet.py --
weights_path /home/pch/test/SCNN/culane_lanenet_vgg_2018-12-01-14-38-37.ckpt-10000  --image_path /home/pch/test/SCNN/test_img.txt

get  the problem 'Segmentation fault (core dumped)' and i don't know how to solve it.

**Comment by cardwing** [comment]
@Endless-Hao, what is the version of your tensorflow, cuda and cudnn?

**Comment by Endless-Hao** [comment]
@cardwing  my tensorflow is 1.10.1  python is 3.6 cuda 9.0 cudnn 7

**Comment by cardwing** [comment]
@Endless-Hao, no other information except 'Segmentation fault (core dumped)'? It is difficult to debug with such limited information. Can you have a try to run a simple tensorflow code which can be downloaded from the official site? I guess it may be caused by the improper installation of tensorflow.

**Comment by Endless-Hao** [comment]
I use deeplab is ok. Just now i delete your some import that not use in your code such as numpy..,the code  can run. The new problem is i change the save_dir, but there are no output .And the code run very fast. 

2018-12-13 11:57:39.641641: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8935 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
INFO:tensorflow:Restoring parameters from /home/pch/test/SCNN/culane_lanenet_vgg_2018-12-01-14-38-37.ckpt-10000
I1213 11:57:39.782603 23581 tf_logging.py:115] Restoring parameters from /home/pch/test/SCNN/culane_lanenet_vgg_2018-12-01-14-38-37.ckpt-10000
pch@pch:~/1-lane detection/3

**Comment by Endless-Hao** [comment]
@cardwing  Yes there are no other information, just there sentence. My environment is ok.I use deeplab is ok. Just now i delete your some import that not use in your code such as numpy..,the code can run. The new problem is i change the save_dir, but there are no output .And the code run very fast.

2018-12-13 11:57:39.641641: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8935 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
INFO:tensorflow:Restoring parameters from /home/pch/test/SCNN/culane_lanenet_vgg_2018-12-01-14-38-37.ckpt-10000
I1213 11:57:39.782603 23581 tf_logging.py:115] Restoring parameters from /home/pch/test/SCNN/culane_lanenet_vgg_2018-12-01-14-38-37.ckpt-10000
pch@pch:~/1-lane detection/3

**Comment by Endless-Hao** [comment]
@cardwing  and the code can not debug ,if you debug at some red point ,it say pydev debugger: process 23699 is connecting

**Comment by cardwing** [comment]
@Endless-Hao, the save_dir is not used in fact (I will clean the code and remove useless codes soon). In the testing phase, it should output a sequence of numbers. Please check the image path since this line `for i in range(int(len(image_list) / batch_size)): print(i)` should at least output a number every episode.

**Comment by Endless-Hao** [comment]
@cardwing  Ok i continue to look look.Thanks
