### ISSUE TITLE
ERFNet-CULane-PyTorch training problem in tensor dimension

### ISSUE THREAD

**Issue by freshfruit930** [cardwing/Codes-for-Lane-Detection#200]
when training the erfnet on CuLane, I always encounter the tensor dimension mismatch problem. I add the ceil_mode = True in the maxpool layer and the problem becomes as follows:

 RuntimeError: invalid argument 2: size '[-1 x 3965]' is invalid for input with 22660 elements at /pytorch/aten/src/TH/THStorage.c:37

I print the shape of some layer's output but still didn't know how the "3965" is calculated.

Does anyone encounter the same problem as mine and has some solutions or suggestions?

Thanks!

**Comment by cardwing** [comment]
What is the size of your input image? It seems that the mismatch problem lies in the flatten operation.

**Comment by freshfruit930** [comment]
Thanks very much for your reply. My input image is resized as 590*1640. 
And after carefully compare my code with the source, I found out that I comment the image transform which cause the above problem. Now I can run the training and testing smoothly.
