### ISSUE TITLE
ENet-Label-Torch testing 

### ISSUE THREAD

**Issue by Mement858** [cardwing/Codes-for-Lane-Detection#201]
Hello
I tried to test ENet-Label-Torch model with other data, but
after executing "sh ./experiments/test.sh", only one image was tested. I changed file paths in data/list/test.txt and /experiments/test.sh.Should I change other things too? Thank you.

**Comment by cardwing** [comment]
Just change the batch size and nGPU to values more than 1.

**Comment by Mement858** [comment]
thank you!
