### ISSUE TITLE
SCNN 

### ISSUE THREAD

**Issue by BoSeal** [cardwing/Codes-for-Lane-Detection#203]
@cardwing 你好，我把SCNN整个流程跑完了，可我没有得到下图所示的图片，请问我要运行哪个文件才能得到下图：
![图片](https://user-images.githubusercontent.com/39556913/71168656-33ed9800-2292-11ea-8f3f-56f238a3be7c.png)

**Comment by cardwing** [comment]
把main.m里面的show变量设为true后再运行main.m就可以得到这种图片了。
