### ISSUE TITLE
About “1 1 1 1 ” in  the exist file of probmap in SCNN

### ISSUE THREAD

**Issue by BoSeal** [cardwing/Codes-for-Lane-Detection#204]
@cardwing In SCNN，i find that when i test it. If there is no line in the picture, the exist.txt also 1 1 1 1,then I checked and found that all the exist.txt files were always 1 1 1 1 . This is also strange thing.you know how to slove it ? I find this part of the code as follows:
![图片](https://user-images.githubusercontent.com/39556913/71171055-d0666900-2297-11ea-956e-1d0a27e1fb0d.png)
 **the example of the exist file of probmap :**
![图片](https://user-images.githubusercontent.com/39556913/71172386-03f6c280-229b-11ea-8be7-213ee1c58663.png)

**Comment by BoSeal** [comment]
@cardwing ,你好，我查看了下代码，添加print，打印出一些信息，如下：
![图片](https://user-images.githubusercontent.com/39556913/71203997-0a585f00-22da-11ea-8310-649bb57d5896.png)

![图片](https://user-images.githubusercontent.com/39556913/71204019-18a67b00-22da-11ea-8a6a-39eb087f2cbc.png)

我猜测应该是existence_output该处出了问题，之后我又反复检查与existence_output相关代码，但没发现什么问题，可以麻烦你再检查下目前SCNN-tensorflow最新版源码么？

**Comment by nolovenolife** [comment]
我这边也是不管放什么图片都是1111
