### ISSUE TITLE
关于SCNN测试图森数据库时得到所有车道线只在第一张图上的问题

### ISSUE THREAD

**Issue by zhangjy2008327** [cardwing/Codes-for-Lane-Detection#205]
你好，请问我在用SCNN测试Tusimple数据库时，test后只能得到4条车道线在第一张图片上，即1_avg.png上，其中2_avg.png, 3_avg.png, 4_avg.png都没有任何内容，请问这是怎么回事，还请给予解答，谢谢。

**Comment by cardwing** [comment]
你可以看一下输入一张图片可以得到几张概率图。所有车道线都在一张图上可能是因为这张图是划分背景和车道线的，其他图片则是划分具体某个车道线的。之所以看不出来可能是图片的值的问题。你可以把图片上所有值乘以50再可视化看看。

**Comment by zhangjy2008327** [comment]
非常感谢在百忙之中给予回复
