### ISSUE TITLE
关于SCNN数据集问题

### ISSUE THREAD

**Issue by BoSeal** [cardwing/Codes-for-Lane-Detection#206]
CULane数据集中，laneseg_label_w16文件中所有图片都是黑色的，如下所示：
![图片](https://user-images.githubusercontent.com/39556913/71304936-0aef1380-2408-11ea-888f-6b023f04497a.png)
之后，我又检查了下train_gt.txt，里面的路径，如下所示：
![图片](https://user-images.githubusercontent.com/39556913/71304964-4be72800-2408-11ea-8281-fd99e17b1ae6.png)

我理解的是，laneseg_label_w16文件中的图片，应该是包含4条车道线+背景，但事实上我看到的都是背景，不包含车道线，所以我猜测，laneseg_label_w16文件中的图片是不是有问题？还是说，我理解错了？麻烦您可以为我答疑么？

**Comment by BoSeal** [comment]
Now，I see

**Comment by cardwing** [comment]
标签图片是由0-4这5个数字组成的。你可视化的时候应该将图片所有值乘以50再做可视化才能看到车道线。
