### ISSUE TITLE
关于SAD使用nn.spatialsoftmax

### ISSUE THREAD

**Issue by ceasorcai** [cardwing/Codes-for-Lane-Detection#207]
您好，非常感谢您的论文和代码，我有一个疑问，在对featuremap(b*c*h*w)计算AttentionMap(b*1*h*w),后，为何要用nn.spatialsoftmax？nn.spatialsoftmax的作用是什么？因为没找到您代码里nn.spatialsoftmax这一段代码，我想知道nn.spatialsoftmax是对AttentionMap(b*1*h*w)哪一个dim计算softmax,输出尺寸是什么，是跟输入尺寸一致吗？非常感谢

**Comment by cardwing** [comment]
处理完的feature和处理前大小一样。nn.spatialsoftmax的作用是从H x W里筛选若干响应比较强的点，同时做归一化。nn.spatialsoftmax在ENet-Label-Torch里。

**Comment by ceasorcai** [comment]
谢谢，您讲的是在ENet-Label-Torch/models/init.lua，这个文件里吗？但是这里面注释掉了啊

**Comment by ceasorcai** [comment]
麻烦再请教一个问题，如果对H x W 做softmax，只有个别值比较大，少个别值较小，大部分为零，用nn.MSECriterion计算loss ，loss值 是非常小，请问我这么理解对吗？谢谢

**Comment by cardwing** [comment]
是的。这时候就不需要除以HW了。测试的时候nn.spatialsoftmax就在模型文件里面，训练的时候你可以自己加一下或者把那几行的注释去掉。

**Comment by ceasorcai** [comment]
谢谢

**Comment by ceasorcai** [comment]
@cardwing 您好，还有一个问题要麻烦您，ENet-Label-Torch，使用您提供的测试模型，block 3 经历了如下操作：nn.Power(2)，nn.Sum(1, 3)，nn.SpatialUpSamplingBilinear(8)，nn.SpatialSoftMax()。但是 ENet-Label-Torch/testLane.lua里面的如下代码
  local scoremap = output[1]  --:double()
   if opt.smooth then
      scoremap = process(scoremap):float()
   else
      local softmax = nn.SpatialSoftMax():cuda()
      scoremap = softmax(scoremap):float()
   end
以及测试结果打印block3 attention的输出（b=1时输出1*208*976 里面的值全为1）和上述测试代码的输出，我发现，nn.SpatialSoftMax()对于b x H x W实在dim=0(即b维度上）计算softmax，对于b x c x H x W是在dim=1（即c 维度上）计算softmax, 直接用nn.SpatialSoftMax()我无法从H x W里筛选若干响应比较强的点，torch7的安装步骤包括cuda版本我也是跟您推荐的一致，我想向您请教一下，这是什么问题，一直没搞明白，是torch7版本变化了吗？谢谢

**Comment by ceasorcai** [comment]
测试结果打印block3 attention的输出（b=1时输出1208976 里面的值全为1）使用的是您的测试model

**Comment by ceasorcai** [comment]
测试结果打印block3 attention的输出（b=1时输出1x 208 x 976 里面的值全为1）使用的是您的测试model。但是如果是因为版本问题的话也不对，因为您ENet-Label-Torch/testLane.lua里面的如下代码
local scoremap = output[1] --:double()
if opt.smooth then
scoremap = process(scoremap):float()
else
local softmax = nn.SpatialSoftMax():cuda()
scoremap = softmax(scoremap):float()
end
目的就是用 nn.SpatialSoftMax()对b x c x H x W在dim=1（即c 维度上）计算softmax获取4条车道线的像素点分类结果
