### ISSUE TITLE
About testing result

### ISSUE THREAD

**Issue by Endless-Hao** [cardwing/Codes-for-Lane-Detection#21]
hello, i test the results use the prerain-model you offered, but i find the result is very worse .In some clear lane mark picture also not good,i want to know why.And is this model your last testing model? And 是否存在坐标的转换问题，我获得的测试结果，利用SCNN的tools生成结果图的。下面是我其中一张。
![00030 results](https://user-images.githubusercontent.com/19277849/49996094-fd1edb00-ffc8-11e8-9b19-7e5ea14710bf.png)

**Comment by Endless-Hao** [comment]
@cardwing Look  the pic is ok ,but in the real world picture is not good.
![qq 20181214180912](https://user-images.githubusercontent.com/19277849/49996998-69024300-ffcb-11e8-965d-b081af8ad6c2.png)

**Comment by cardwing** [comment]
@Endless-Hao, what is the size of your input image? And do you test the pre-trained model and get the final F1-measure (71.3)?

**Comment by Endless-Hao** [comment]
@cardwing input pic is CULane data size 1640*590 ,and get result is from SCNN-tensorflow is 800*288. And then i put them ,use the SCNN-original tools. Get the results like the picture i put in the web.

**Comment by Endless-Hao** [comment]
@cardwing  Do you mean i should change the test input size to from 590 1640 to  288 800?

**Comment by cardwing** [comment]
@Endless-Hao, you should first check if the F1-measure of the pre-trained model is 71.3. The original input image should be ok.

**Comment by Endless-Hao** [comment]
@cardwing  hello! I use SCNN original evalution get these:
file: ./output/vgg_SCNN_DULR_w9_iou0.5.txt
tp: 0 fp: 111702 fn: 0
precision: 0
recall: -1
Fmeasure: 0
All the step i follow your step.Also i change the input to 288 800,i get the result still not good.i don't know why.

**Comment by Endless-Hao** [comment]
The folder are like these:
predicts_SCNN_test_final
        vgg_SCNN_DULR_w9
             home
                  pch
                      test
                         driver_37_30frame
                         driver_100_30frame
                         driver_193_90frame
                                        06042010_0511.MP4
                                                         00000.exist.txt
                                                         00000_1_avg.png
                                                         00000_2_avg.png
                                                         00000_3_avg.png
                                                         00000_4_avg.png

**Comment by cardwing** [comment]
@Endless-Hao, can you attach the original folder here? I need the whole file to check which part is wrong. You can put the link which stores the generated probability maps here.

**Comment by Endless-Hao** [comment]
@cardwing  hello  you are a good 老哥 Thanks.This is my original folder:
[problem.zip](https://github.com/cardwing/Codes-for-Lane-Detection/files/2680483/problem.zip)

**Comment by cardwing** [comment]
@Endless-Hao, I have found that the generated probability maps are different these of mine. You can either test my generated [probability maps](https://drive.google.com/open?id=1mLdX_9NfgcZ2I4tb_SeAPYk42t7Csp6d) or re-train the model and have a test then.

**Comment by Endless-Hao** [comment]
@cardwing  i look all the results, also i change the input ,but get different result which are all not good. Do you konw is it roughly what caused it? I use the data and model the same as you. If there is not solution  at last ,i think  i must retrain it. I just feel strange about this. The steps are same as you.

**Comment by cardwing** [comment]
@Endless-Hao, I have downloaded the pre-trained model and regenerate the probability maps. The results are still good and the F1-measure is exactly the same as what is listed in the table in README. I recommend that you should check the evaluation process as well as the probability map generation process.

**Comment by Endless-Hao** [comment]
@cardwing  i have another problem, can you debug. I want to see the every step. Your code in my computer ,can not debug. When i debug, it just say"pyder debugger: process 26490 is connecting" only this sentence.

**Comment by Endless-Hao** [comment]
@cardwing  i also  find, when i test it. If there is no line in the picture, the exist.txt also  1 1 1 1. This is also strange thing.

**Comment by Endless-Hao** [comment]
@cardwing  i use you result you upload. I find that your results is very good. The last generate picture is very good.
![00000 results](https://user-images.githubusercontent.com/19277849/50063640-397c5200-01e8-11e9-9984-504b9ed48336.png)
![00030 results](https://user-images.githubusercontent.com/19277849/50063649-40a36000-01e8-11e9-8002-e3f0f8b4b155.png)
![01590 results](https://user-images.githubusercontent.com/19277849/50063654-4731d780-01e8-11e9-9f67-4f24012ce095.png)
the results you upload actually good.

**Comment by Endless-Hao** [comment]
@cardwing  but i can not get these. Do you have any little  change in your code you forget it ?

**Comment by cardwing** [comment]
@Endless-Hao, everything is ok in my local server, including debugging and running (I download the codes and perform testing). I also check the uploaded codes and find nothing is wrong. The main difference between your generated probability maps and mine is the position of detected lanes. You may have to re-train the model and check the performance then.

**Comment by Endless-Hao** [comment]
@cardwing  i also find a strange condition. Every time i test the pictures, the same model and the same code will get the different results. The differences are a little big.

**Comment by cardwing** [comment]
@Endless-Hao, it is weird. You should check the code carefully since it is impossible to get different outputs using the same input and same model.

**Comment by Endless-Hao** [comment]
@cardwing  this is what  i am so strange. If  this can not solve, i think i will also get not good results to use the model that  i train my own . I continue to check the code. Thinks. If i get the new condition, i would talk with you. Thank you for your help.

**Comment by cardwing** [comment]
^_^

**Comment by KevinWalkerFan** [comment]
@Endless-Hao can u share the test code that u use to test the visual performance just on the pic?

**Comment by BoSeal** [comment]
> 
> 
> @cardwing i also find, when i test it. If there is no line in the picture, the exist.txt also 1 1 1 1. This is also strange thing.

Hello, I have the same problem as you. How did you solve this problem?

**Comment by BoSeal** [comment]
> 
> 
> @cardwing  i also find, when i test it. If there is no line in the picture, the exist.txt also 1 1 1 1. This is also strange thing.
@Endless-Hao ,Hello, I have the same problem as you. How did you solve this problem?
