### ISSUE TITLE
SCNN for semantic segmentation tasks on Cityscapes

### ISSUE THREAD

**Issue by BoSeal** [cardwing/Codes-for-Lane-Detection#210]
你好，请问，我remove the lane existence prediction branch 之后，train_lanenet.py中的这部分代码我是不是也需要remove？
![图片](https://user-images.githubusercontent.com/39556913/71444858-a4436000-274f-11ea-8080-8a8188b54bd3.png)
![图片](https://user-images.githubusercontent.com/39556913/71445628-1028c700-2756-11ea-9a24-07c1b3a6b2eb.png)

**Comment by cardwing** [comment]
这段代码是算mIoU的，不需要删。
