### ISSUE TITLE
about code problem

### ISSUE THREAD

**Issue by BoSeal** [cardwing/Codes-for-Lane-Detection#211]
想要将SCNN适用于Cityscapes进行图像语义分割，以下代码是否只需要修改“1”处即可？还是说decode_logits_reshape和binary_label_reshape，两处也需要修改？因为我不清楚decode_logits_reshape和binary_label_reshape里面的shape参数为什么写成这样的形式，假如换为Cityscapes做语义分割实验，是否会有影响？
![图片](https://user-images.githubusercontent.com/39556913/71446043-3486a280-275a-11ea-93c4-63041cfcac6a.png)

**Comment by cardwing** [comment]
改这一处应该就可以了。对模型的输出做shape变换是为了使用class weight，你可以看一下在tensorflow里面怎么使用class weight就知道这边为什么这么写了。
