### ISSUE TITLE
compute_mIoU for SCNN 

### ISSUE THREAD

**Issue by BoSeal** [cardwing/Codes-for-Lane-Detection#212]
@cardwing 您好！请问在Cityscapes上使用SCNN进行语义分割时，如何计算模型的精度，即IOU？是否需要我新建一个py文件，在里面计算IOU？还是说可以直接在SCNN代码中进行少量的代码修改，就可以直接计算出IOU？

**Comment by cardwing** [comment]
目前的代码就可以实现计算mIoU的功能。只需要写一个循环计算每一类的IoU，然后平均一下就好了。

**Comment by BoSeal** [comment]
好的，多谢！
