### ISSUE TITLE
how to train the model with other data 

### ISSUE THREAD

**Issue by Mement858** [cardwing/Codes-for-Lane-Detection#213]
i would like to train the model with using my images whose sizes are the same as CULane datasets. When i use my images, should i change another thing too other than train.sh? Thank you.

**Comment by Mement858** [comment]
the error:


data created
data loaded
data created
data loaded
init trainer
training
=> Training epoch # 1
 | Epoch: [1][1/7][1]  Time 7.95  LR 0.01000  Err1 0.57091 (0.57091)  Err2 0.06514 (0.06514) Err3 0.00000 (0.00000) Err4 0.00000 (0.00000)
 | Epoch: [1][2/7][2]  Time 0.34  LR 0.01000  Err1 0.24492 (0.40792)  Err2 0.06398 (0.06456) Err3 0.00000 (0.00000) Err4 0.00000 (0.00000)
 | Epoch: [1][3/7][3]  Time 0.45  LR 0.01000  Err1 0.21598 (0.34394)  Err2 0.06065 (0.06326) Err3 0.00000 (0.00000) Err4 0.00000 (0.00000)
 | Epoch: [1][4/7][4]  Time 0.45  LR 0.01000  Err1 0.18577 (0.30439)  Err2 0.05713 (0.06173) Err3 0.00000 (0.00000) Err4 0.00000 (0.00000)
 | Epoch: [1][5/7][5]  Time 0.45  LR 0.01000  Err1 0.19109 (0.28173)  Err2 0.05214 (0.05981) Err3 0.00000 (0.00000) Err4 0.00000 (0.00000)
 | Epoch: [1][6/7][6]  Time 0.45  LR 0.01000  Err1 0.11498 (0.25394)  Err2 0.04802 (0.05784) Err3 0.00000 (0.00000) Err4 0.00000 (0.00000)
/home/ubuntu/torch/install/bin/luajit: ...u/torch/install/share/lua/5.1/cunn/DataParallelTable.lua:617: bad argument #1 to 'copy' (sizes do not match at /home/ubuntu/torch/extra/cutorch/lib/THC/THCTensorCopy.cu:31)
stack traceback:
	[C]: in function 'copy'
	...u/torch/install/share/lua/5.1/cunn/DataParallelTable.lua:617: in function '_concatTensorRecursive'
	...u/torch/install/share/lua/5.1/cunn/DataParallelTable.lua:597: in function '_concatTensorRecursive'
	...u/torch/install/share/lua/5.1/cunn/DataParallelTable.lua:584: in function '_concat'
	...u/torch/install/share/lua/5.1/cunn/DataParallelTable.lua:202: in function 'forward'
	./train.lua:69: in function 'train'
	main.lua:51: in main chunk
	[C]: in function 'dofile'
	...untu/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50

**Comment by cardwing** [comment]
The training script does not need any modification. The error may be caused by the batch size. It seems that the number of training images is not divisible by the batch size.

**Comment by Mement858** [comment]
thank you for your reply. 
the number of images for train is 75 , for validation is 5 and i set the batchsize to 5.
However, it doesn't work well. Do you have any solution? Thank you.
