### ISSUE TITLE
ENet-label input view does not match desired view

### ISSUE THREAD

**Issue by czming** [cardwing/Codes-for-Lane-Detection#216]
![image](https://user-images.githubusercontent.com/16664600/71453444-38500e80-27c6-11ea-82d9-ab6d60284c99.png)

Hi, I tried running the ENet-label code with CULane dataset input and I seem to be getting an error as shown in the image above. The error seems to be with the model file, which I downloaded from the README in the ENet-label folder, ENet-label-new.t7. I tried changing the code in dataset/laneTest.lua in preprocess. I changed the t.scaleWH in elseif self.split == 'val' from 800,288 to 980,220 and it managed to run without error, but the output appears warped and is of a different size from the SCNN output size of 800,288, so I suspect this might be a wrong method to solve the issue

![image](https://user-images.githubusercontent.com/16664600/71453573-d3e17f00-27c6-11ea-8e90-6054c87233e7.png)

Any help is appreciated. Thanks

**Comment by cardwing** [comment]
You should use the codes of this repo instead of SCNN. There are some modifications to the original SCNN code.

**Comment by czming** [comment]
Thanks for the reply, but the code seems to give a similar error when I ran the original numbers from ENet-label in this repo as well which led me to try changing these numbers. With the original numbers from this repo in ENet-label folder, this was the output instead.

![image](https://user-images.githubusercontent.com/16664600/71456249-8d465180-27d3-11ea-9270-b50b163cb823.png)

Thanks
