### ISSUE TITLE
Restoring of checkpoint failed.

### ISSUE THREAD

**Issue by creisner** [cardwing/Codes-for-Lane-Detection#22]
Hi.

I try to get the model to run according to README. Apparently there is a problem with the checkpoint file. Is the file broken or am I doing something wrong?

`python test_lanenet.py --weights_path model_culane-71-3/culane_lanenet_vgg_2018-12-01-14-38-37.ckpt-10000.index --image_path images.txt
`
...
`
INFO:tensorflow:Restoring parameters from model_culane-71-3/culane_lanenet_vgg_2018-12-01-14-38-37.ckpt-10000.index
I1215 22:58:33.538790 7892 tf_logging.py:82] Restoring parameters from model_culane-71-3/culane_lanenet_vgg_2018-12-01-14-38-37.ckpt-10000.index
Traceback (most recent call last):
  File "/home/crr/miniconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/home/crr/miniconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1306, in _run_fn
    status, run_metadata)
  File "/home/crr/miniconda3/envs/tensorflow/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/crr/miniconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: Tensor name "lanenet_loss/inference/encode/dense_1/kernel" not found in checkpoint files model_culane-71-3/culane_lanenet_vgg_2018-12-01-14-38-37.ckpt-10000.index
         [[Node: save/RestoreV2_84 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_84/tensor_names, save/RestoreV2_84/shape_and_slices)]]
`

**Comment by creisner** [comment]
@cardwing 
Thank you for your prompt help. I got the model to work. Additionally I had to make some code changes to open the test images. Unfortunately I don't get the expected prediction yet, but I'm still working on it. I expected similar output images to MaybeShewill-CV/lanenet-lane-detection implementation.

**Comment by YilmazOrkun** [comment]
@creisner What changes in the code did you implement to open the test images?

**Comment by Chao-Xiong** [comment]
Why I can not find the checkpoint files in the mode_culane-71-3.zip?
just found three files
1. - culane_lanenet_vgg_2018-12-01-14-38-37.ckpt-10000.data-00000-of-00001
2. - culane_lanenet_vgg_2018-12-01-14-38-37.ckpt-10000.index
3. - culane_lanenet_vgg_2018-12-01-14-38-37.ckpt-10000.meta

**Comment by cardwing** [comment]
@Chao-Xiong, You can load the model from these files using Tensorflow.

**Comment by Chao-Xiong** [comment]
Thanks. I will try, I just know load model from checkpoints before. I will learn the new way.






At 2019-04-04 12:57:54, "HOU Yuenan" <notifications@github.com> wrote:


@Chao-Xiong, You can load the model from these files using Tensorflow.
