### ISSUE TITLE
Data loss: Unable to open table file /home/gpu/codes/MSD/scnn_tf_1/scnn_tf/weights/culane_lanenet_vgg_2018-12-01-14-38-37.ckpt-10000.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator? 	 [[node save/RestoreV2 (defined at /codes/MSD/scnn_tf_1/scnn_tf/lanenet.py:67) ]]

### ISSUE THREAD

**Issue by masouduut94** [cardwing/Codes-for-Lane-Detection#221]
This is the code I used to test the pretrained models:

    # -*- coding: utf-8 -*-
    # @Time    : 18-5-23 上午11:33
    # @Author  : Luo Yao
    # @Site    : http://icode.baidu.com/repos/baidu/personal-code/Luoyao
    # @File    : lanenet_test.py
    # @IDE: PyCharm Community Edition
    """
    测试LaneNet模型
    """
    import os
    import os.path as ops
    import argparse
    import math
    import tensorflow as tf
    # import glog as log
    # import cv2
    
    try:
        from cv2 import cv2
    except ImportError:
        pass
    
    from lanenet_model.lanenet_merge_model import LaneNet
    from config import global_config
    from data_provider import lanenet_data_processor_test
    
    CFG = global_config.cfg
    VGG_MEAN = [103.939, 116.779, 123.68]
    
    
    def init_args():
        """
    
        :return:
        """
        parser = argparse.ArgumentParser()
        parser.add_argument('--image_path', type=str, help='The image path or the src image save dir',
                            default='/home/gpu/codes/MSD/scnn_tf_1/scnn_tf/text_file/a.txt')
        parser.add_argument('--weights_path', type=str, help='The model weights path',
                            default='/home/gpu/codes/MSD/scnn_tf_1/scnn_tf/weights/culane_lanenet_vgg_2018-12-01-14-38-37.ckpt-10000.data-00000-of-00001')
        parser.add_argument('--is_batch', type=str, help='If test a batch of images', default='false')
        parser.add_argument('--batch_size', type=int, help='The batch size of the test images', default=8)
        parser.add_argument('--save_dir', type=str, help='Test result image save dir', default='/home/gpu/codes/MSD/scnn_tf_1/scnn_tf/predicts')
        parser.add_argument('--use_gpu', type=int, help='If use gpu set 1 or 0 instead', default=1)
    
        return parser.parse_args()
    
    
    def test_lanenet(image_path, weights_path, use_gpu, image_list, batch_size, save_dir):
        """
        :param image_path:
        :param weights_path:
        :param use_gpu:
        :return:
        """
    
        test_dataset = lanenet_data_processor_test.DataSet(image_path, batch_size)
        input_tensor = tf.placeholder(dtype=tf.string, shape=[None], name='input_tensor')
        imgs = tf.map_fn(test_dataset.process_img, input_tensor, dtype=tf.float32)
        phase_tensor = tf.constant('test', tf.string)
    
        net = LaneNet()
        binary_seg_ret, instance_seg_ret = net.test_inference(imgs, phase_tensor, 'lanenet_loss')
        initial_var = tf.global_variables()
        final_var = initial_var[:-1]
        saver = tf.train.Saver(final_var)
        # Set sess configuration
        if use_gpu:
            sess_config = tf.ConfigProto(device_count={'GPU': 1})
        else:
            sess_config = tf.ConfigProto(device_count={'GPU': 0})
        sess_config.gpu_options.per_process_gpu_memory_fraction = CFG.TEST.GPU_MEMORY_FRACTION
        sess_config.gpu_options.allow_growth = CFG.TRAIN.TF_ALLOW_GROWTH
        sess_config.gpu_options.allocator_type = 'BFC'
        sess = tf.Session(config=sess_config)
        with sess.as_default():
            sess.run(tf.global_variables_initializer())
            saver.restore(sess=sess, save_path=weights_path)
            for i in range(math.ceil(len(image_list) / batch_size)):
                print(i)
                paths = test_dataset.next_batch()
                instance_seg_image, existence_output = sess.run([binary_seg_ret, instance_seg_ret],
                                                                feed_dict={input_tensor: paths})
                for cnt, image_name in enumerate(paths):
                    print(image_name)
                    parent_path = os.path.dirname(image_name)
                    directory = os.path.join(save_dir, 'vgg_SCNN_DULR_w9', parent_path)
                    if not os.path.exists(directory):
                        os.makedirs(directory)
                    file_exist = open(os.path.join(directory, os.path.basename(image_name)[:-3] + 'exist.txt'), 'w')
                    for cnt_img in range(4):
                        cv2.imwrite(os.path.join(directory,
                                                 os.path.basename(image_name)[:-4] + '_' + str(cnt_img + 1) + '_avg.png'),
                                    (instance_seg_image[cnt, :, :, cnt_img + 1] * 255).astype(int))
                        if existence_output[cnt, cnt_img] > 0.5:
                            file_exist.write('1 ')
                        else:
                            file_exist.write('0 ')
                    file_exist.close()
        sess.close()
        return
    
    
    if __name__ == '__main__':
        # init args
        args = init_args()
        # print(os.path)
        if args.save_dir is not None and not ops.exists(args.save_dir):
            # log.error('{:s} not exist and has been made'.format(args.save_dir))
            os.makedirs(args.save_dir)
    
        save_dir = os.path.join(args.image_path, 'predicts')
        if args.save_dir is not None:
            save_dir = args.save_dir
    
        img_name = []
        with open(str(args.image_path), 'r') as g:
            for line in g.readlines():
                img_name.append(line.strip())
    
        test_lanenet(args.image_path, args.weights_path, args.use_gpu, img_name, args.batch_size, save_dir)

And this is the directory root:

-  config
  - -  global_config.py
- data
- data_provider
  - -  lanenet_data_processor.py
  - -  lanenet_data_processor_test.py
- demo_file
- encoder_decoder_model
  - - cnn_basenet.py
  - - vgg_encoder.py
- images
  - - 1.jpg
  - - 2.jpg
- lanenet_model
  - - __init__.py
  - - lanenet_merge_model.py
- text_file
  - - a.txt
- tools
  - - lanenet.py
  - - train_lanenet.py
- weights
  - - culane_lanenet_vgg_2018-12-01-14-38-37.ckpt-10000.data-00000-of-00001
  - - culane_lanenet_vgg_2018-12-01-14-38-37.ckpt-10000.index
  - - culane_lanenet_vgg_2018-12-01-14-38-37.ckpt-10000.meta
- __init__.py
- lanenet.py

After using this code I get this error:
Traceback (most recent call last):
  File "/home/gpu/codes/MSD/scnn_tf_1/scnn_tf/lanenet.py", line 128, in <module>
    test_lanenet(args.image_path, args.weights_path, args.use_gpu, img_name, args.batch_size, save_dir)
  File "/home/gpu/codes/MSD/scnn_tf_1/scnn_tf/lanenet.py", line 79, in test_lanenet
    saver.restore(sess=sess, save_path=weights_path)
  File "/home/gpu/anaconda3/envs/tf_gpu_36/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1286, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/gpu/anaconda3/envs/tf_gpu_36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/gpu/anaconda3/envs/tf_gpu_36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/gpu/anaconda3/envs/tf_gpu_36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/home/gpu/anaconda3/envs/tf_gpu_36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.DataLossError: 2 root error(s) found.
  (0) Data loss: Unable to open table file /home/gpu/codes/MSD/scnn_tf_1/scnn_tf/weights/culane_lanenet_vgg_2018-12-01-14-38-37.ckpt-10000.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
	 [[node save/RestoreV2 (defined at /codes/MSD/scnn_tf_1/scnn_tf/lanenet.py:67) ]]
	 [[save/RestoreV2/_149]]
  (1) Data loss: Unable to open table file /home/gpu/codes/MSD/scnn_tf_1/scnn_tf/weights/culane_lanenet_vgg_2018-12-01-14-38-37.ckpt-10000.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
	 [[node save/RestoreV2 (defined at /codes/MSD/scnn_tf_1/scnn_tf/lanenet.py:67) ]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'save/RestoreV2':
  File "/codes/MSD/scnn_tf_1/scnn_tf/lanenet.py", line 128, in <module>
    test_lanenet(args.image_path, args.weights_path, args.use_gpu, img_name, args.batch_size, save_dir)
  File "/codes/MSD/scnn_tf_1/scnn_tf/lanenet.py", line 67, in test_lanenet
    saver = tf.train.Saver(final_var)
  File "/anaconda3/envs/tf_gpu_36/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 825, in __init__
    self.build()
  File "/anaconda3/envs/tf_gpu_36/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 837, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/anaconda3/envs/tf_gpu_36/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 875, in _build
    build_restore=build_restore)
  File "/anaconda3/envs/tf_gpu_36/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 508, in _build_internal
    restore_sequentially, reshape)
  File "/anaconda3/envs/tf_gpu_36/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 328, in _AddRestoreOps
    restore_sequentially)
  File "/anaconda3/envs/tf_gpu_36/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 575, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/anaconda3/envs/tf_gpu_36/lib/python3.6/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1696, in restore_v2
    name=name)
  File "/anaconda3/envs/tf_gpu_36/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/anaconda3/envs/tf_gpu_36/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/anaconda3/envs/tf_gpu_36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/anaconda3/envs/tf_gpu_36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()

What have I done wrong!?

**Comment by AmazingRoad** [comment]
Hey, I saw the answer from anthor forum. 
The "weights_path" parameter should be used like this:
"--weights_path culane_lanenet_vgg_2018-12-01-14-38-37.ckpt-10000", without ".data-00000-of-00001"
