### ISSUE TITLE
Traceback (most recent call last):   File "test_erfnet.py", line 13, in <module>     from models import sync_bn  raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")

### ISSUE THREAD

**Issue by masouduut94** [cardwing/Codes-for-Lane-Detection#222]
https://github.com/cardwing/Codes-for-Lane-Detection/blob/8a04dd40b0fd53fe5348529af060871d401ee987/ERFNet-CULane-PyTorch/test_erfnet.py#L13

running `sh ./test_erfnet.sh` leaves me with mentioned error

**Comment by cardwing** [comment]
Is the version of your PyTorch 0.3.0? If not, please install PyTorch 0.3.0.
