### ISSUE TITLE
SCNN code problem

### ISSUE THREAD

**Issue by BoSeal** [cardwing/Codes-for-Lane-Detection#225]
![图片](https://user-images.githubusercontent.com/39556913/71558455-931b8b80-2a8e-11ea-9576-ecc18e72c14c.png)

@cardwing ,for SCNN on CULane，请问，第一个问号处，为什么要除以“8”？这里的“8”是指batch_size=8 ？，第二个问号处，这三行代码为什么要这么写？这样写的好处或者说起到了什么作用？如果我把这三行删了，会对结果有影响么？

**Comment by cardwing** [comment]
这里的8是指图片经过网络缩小了8倍。因为代码写得比较久了，所以代码的具体功能需要你自行摸索了。
