### ISSUE TITLE
SCNN issues

### ISSUE THREAD

**Issue by BoSeal** [cardwing/Codes-for-Lane-Detection#229]
@cardwing ,您好，我想问您两个问题：1、我在SCNN中加入了Atteiton机制，那么我训练的时候，可以在您的SCNN的**pre-trained model：model_culane-71-3** ，进行训练么？2、如果我的batch_size = 2, 在这种情况下，是否可以使用：**pre-trained model：model_culane-71-3**？

**Comment by cardwing** [comment]
1. 可以。
2. batch_size是2的话预训练模型可以载入，但是训练的时候记得把BN固定住。
