### ISSUE TITLE
SCNN for training

### ISSUE THREAD

**Issue by BoSeal** [cardwing/Codes-for-Lane-Detection#230]
@cardwing 请问，在对SCNN进行训练时，出现以下情况，这对最终的模型性能有影响么？ 还是说，模型存在问题？
![图片](https://user-images.githubusercontent.com/39556913/71780872-d2078f00-3002-11ea-966c-088a9ee50c33.png)

**Comment by cardwing** [comment]
出现NAN应该是模型训练出问题了，最终模型应该很难训出来吧。你可以查一下看看哪里出问题了。
