### ISSUE TITLE
Testing for SCNN

### ISSUE THREAD

**Issue by BoSeal** [cardwing/Codes-for-Lane-Detection#231]
@cardwing ,在SCNN上进行测试时，这个global_config.py里面的batch_size 都设置为4，但从测试过程中打印出的信息来看，仍是每次对8张图片进行测试，那么请问你之前遇到过这种问题么？

**Comment by cardwing** [comment]
这是因为在测试的时候，global_config.py里的batch_size没有被用到。你可以稍微修改一下测试文件。
