### ISSUE TITLE
About the result of the evaluation using ENet-Label-Torch

### ISSUE THREAD

**Issue by Mement858** [cardwing/Codes-for-Lane-Detection#236]
Hi.
I used my set of images and its annotation for training a model of ENet-Label-Torch and for testing the model.  From the result of the implementation of "sh run.sh", however, i found that precision was -1. I would like to know the solution for that. 

raw_annotation
![Screenshot 2020-01-09 at 23 19 18](https://user-images.githubusercontent.com/51474588/72077033-ec5ea700-3339-11ea-980a-b184bb8ac901.png)

detected annotation
![Screenshot 2020-01-09 at 23 43 14](https://user-images.githubusercontent.com/51474588/72077063-f8e2ff80-3339-11ea-9c18-b34ba9be78da.png)

**Comment by cardwing** [comment]
What is the size of your input image? ENet-Label-Torch performs cropping on the input image and that may be the reason why the performance is so bad. Please read the codes carefully and modify certain parts before testing it using your own images.
