### ISSUE TITLE
Where is models/vgg.lua for ENet-Label-Torch

### ISSUE THREAD

**Issue by maym86** [cardwing/Codes-for-Lane-Detection#237]
If I train from scratch init.lua tries to load vgg.lua yet it is not found in the repo.

Can you provide the file that you used?

Thanks,

Mike

**Comment by cardwing** [comment]
I think maybe what you want is vgg.t7. You can find it [here](https://drive.google.com/file/d/12RLXY6o8gaGMY1K1g6d447Iby9ewVIyV/). It is put in [SCNN-Torch](https://github.com/XingangPan/SCNN).
