### ISSUE TITLE
CULane dataset image size/ augmentation: (208X976) instead of  288×800

### ISSUE THREAD

**Issue by yanconglin** [cardwing/Codes-for-Lane-Detection#238]
Hi, I want to ask the data pre-processing on CULane dataset. Could you please tell me: 
1. why the image size differs from the one mentioned in paper (208X976 instead of 288×800)?
2. The data augmentation contains several procedures: scaling, cropping, rotation, normalization. I am curious about the hyperparameter setting in this part  (e.g., Scale(size=(0.595, 0.621),Rotation(degree=(-1, 1)). Could you please explain a bit? Also I would lke to know how much the data augmentation contributes to the final results.
Thanks in advance!

**Comment by cardwing** [comment]
1. Since there are no lanes in the upper part of the image, we perform cropping on the input image.
2. The setting is the same as SCNN. We have not performed experiments on evaluating the effect of data augmentation on the final performance.
