### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by BoSeal** [cardwing/Codes-for-Lane-Detection#240]
@cardwing , 在基于Cityscapes训练模型时，我是否可以对模型修改后，直接使用彩色图像作为labels？如下所示：
![图片](https://user-images.githubusercontent.com/39556913/72682240-e3be5b80-3b05-11ea-9f57-edbb507f98c7.png)

**Comment by cardwing** [comment]
你需要将3通道的color map转化为单通道的number map(由0,1,2,...,组成)。
