### ISSUE TITLE
Multi-GPU training

### ISSUE THREAD

**Issue by BoSeal** [cardwing/Codes-for-Lane-Detection#243]
@cardwing @yujincheng08 ,On CULane for SCNN，我想使用2个gpu进行训练，因此我按照你给出的方法，如下所示：
Multi-GPU training has been supported. Just change BATCH_SIZE and GPU_NUM in global_config.py, and then use CUDA_VISIBLE_DEVICES="0,1,2,3" python file_name.py. Thanks @ yujincheng08.
在使用1个gpu时，设置为：BATCH_SIZE = 3 and GPU_NUM = 1 in global_config.py，正常执行训练
在使用2个gpu时，设置为：BATCH_SIZE = 6 and GPU_NUM = 2 in global_config.py，这时会报出：资源用尽，OOM 等信息。
我之后又看了下添加的Multi-GPU 这块代码，我觉得当使用Multi-GPU（如，2块gpu） 时，in global_config.py，只需要修改GPU_NUM = 2即可，不需要修改BATCH_SIZE = 6. 
但我不确定我的理解是否正确，希望您可以为我解答疑惑，谢谢！

**Comment by cardwing** [comment]
Your modification is right. It should not raise the OOM error. When you use two GPUs, have you monitored the memory usage of two GPUs before OOM?

**Comment by BoSeal** [comment]
@cardwing ,你好，你说我的修改是right，这里的修改指的是哪一种？
1、在使用2个gpu时，设置为：BATCH_SIZE = 6 and GPU_NUM = 2 in global_config.py。
2、在使用2个gpu时，设置为：只修改GPU_NUM = 2，BATCH_SIZE = 3保持不变，从而total batch size=2 x 3=6 in global_config.py

**Comment by yujincheng08** [comment]
The latter one. `BATCH_SIZE` is for each GPU.
