### ISSUE TITLE
Getting_error while testing 

### ISSUE THREAD

**Issue by rampyyadav** [cardwing/Codes-for-Lane-Detection#244]
File "/content/ERFNet-CULane-PyTorch/test_erfnet.py", line 85, in main
    validate(test_loader, model, criterion, 0, evaluator)
  File "/content/ERFNet-CULane-PyTorch/test_erfnet.py", line 116, in validate
    directory = 'predicts/vgg_SCNN_DULR_w9' + img_name[cnt]
TypeError: must be str, not Tensor

**Comment by rampyyadav** [comment]
must be str, not Tensor ?

**Comment by cardwing** [comment]
Please print the `img_name` to debug.

**Comment by rampyyadav** [comment]
hello @cardwing  mine output is to much bad .. its showing blurry thing only black black things only

**Comment by cardwing** [comment]
That's weird. You may debug by yourself since everything works well on my local server.
