### ISSUE TITLE
Problem with CUDA 10.1

### ISSUE THREAD

**Issue by IntanP** [cardwing/Codes-for-Lane-Detection#246]
Hi, 

I tried with CUDA 10.1 and Ubuntu 18.04, but I keep getting the same error "ImportError: libcusolver.so.8.0: cannot open shared object file: No such file or directory". I don't want to downgrade the CUDA version. Is there a way to run your codes with CUDA 10.1?

Kind regards, 
Intan

**Comment by cardwing** [comment]
You may install CUDA 8.0 in your system (installing two versions of CUDA is ok and you just need to specify which CUDA to use when running codes) and run the codes.

**Comment by IntanP** [comment]
Ok, I'll try. Thank you for the fast reply! (:

**Comment by IntanP** [comment]
Can I run the codes just with CPU?
