### ISSUE TITLE
L2 loss mentioned in SAD branch of the paper

### ISSUE THREAD

**Issue by khiemkhanh98** [cardwing/Codes-for-Lane-Detection#247]
Hi cardwing

I am wondering if the L2 error mentioned in your paper is the Mean squared error. Correct me if i am wrong but i think that L2 loss is used as a regularization loss to prevent the model overfitting rather than for distillation purpose?  MSE would make more sense in terms of forcing earlier layer to mimic latter layers in the SAD part.

Thank you

**Comment by cardwing** [comment]
Yes. The L2 loss can indeed act as a regularizer. The selection of L2 loss is the same as the paper titled as "paying more attention to attention".
