### ISSUE TITLE
Meaning of 4 outputs

### ISSUE THREAD

**Issue by IntanP** [cardwing/Codes-for-Lane-Detection#249]
Hi, 
it's me again. I run successfully the codes with CPU only and got 4 outputs of each input image. What is the meaning of those outputs? Has each output difference method?
I read the codes now and trying to figure it out. It would be helpful if you could explain it. 
Thank you in advance.

**Comment by cardwing** [comment]
The four outputs are the probability maps of four lanes. You can refer to the original SCNN paper for more details.
