### ISSUE TITLE
how to calculate mAP in your ENet-SAD-Simple code for unsupervised_llamas dataset?

### ISSUE THREAD

**Issue by zhangjy2008327** [cardwing/Codes-for-Lane-Detection#252]
in the fellowing links:
https://github.com/cardwing/unsupervised_llamas/tree/master/ENet-SAD-Simple
you provide the code for llamas dataset, the result is:

Name                   | mAP | ap BG | ap L1 | ap L0 | ap R0 | ap R1 

ENet-SAD-Simple | 0.635 | .999 | 0.266 | 0.896 | 0.880 | 0.498 |

here question is how to calculate mAP?(according to the values of "ap BG | ap L1 | ap L0 | ap R0 | ap R1")? look forward to your favourable reply,
thank you very much!

**Comment by cardwing** [comment]
The evaluation codes are available in this [repo](https://github.com/karstenBehrendt/unsupervised_llamas/tree/8a7836faa55ee7d90b385da11a521b515bce6fc7/evaluation). However, since LLAMAS has not provided the ground-truth labels for the testing set, you have to submit the results to their server. Detailed instruction can be found in their official website.

**Comment by zhangjy2008327** [comment]
thank you for your favourable reply, i still don't know how to calculate mAP. l think l know your meanings. we can get ap BG | ap L1 | ap L0 | ap R0 | ap R1 from the https://github.com/karstenBehrendt/unsupervised_llamas/tree/8a7836faa55ee7d90b385da11a521b515bce6fc7/evaluation
, but it doesn't tell us how to calculate mAP from them. if i am not sure the result of my algorithm is higher than the published results, i think it's best not to be submitted to the server. if the computing method for mAP is be known by us, we can make sure whether our results should be submitted to server. l would like to further respond to this question. thank you very much!

**Comment by cardwing** [comment]
MAP is just an average of the AP of each lane class. If you do not want to submit the results to the server, you may follow the dataset partitions of our CVPR 2020 paper which will be released soon. In that paper, we split the original validation set into two sets, one for validation (10, 029 images) and one for testing (10, 815 images).

**Comment by zhangjy2008327** [comment]
thank you very much, then l will learn from your paper
