### ISSUE TITLE
Question about the prob maps

### ISSUE THREAD

**Issue by EmmanouelP** [cardwing/Codes-for-Lane-Detection#254]
Hellow and thanks for your great work.....When I test the SCNN model on the test dataset all my ".exist.txt" have the output "1 1 1 1" meaning that it's detecting four lanes at all-time in the images. Is it correct? Shouldn't it be more something like float values in the interval [0, 1]. Thanks in advance.

**Comment by cardwing** [comment]
See the codes [here](https://github.com/cardwing/Codes-for-Lane-Detection/blob/master/ENet-Label-Torch/testLane.lua#L124).
