### ISSUE TITLE
SCNN

### ISSUE THREAD

**Issue by BoSeal** [cardwing/Codes-for-Lane-Detection#255]
@cardwing , 你好，我按照您给出的tensorflow—SCNN代码跑了下程序，迭代次数设置为60k，使用4块gpu，其余参数与SCNN论文中的也都保持一致，但最终的结果却差强人意，只达到了64%多，所以我想知道是否您使用了其他一些技巧来训练SCNN网络？
另一个问题是，当我使用单gpu进行训练时，得到的结果却比多gpu条件下的要高，我不清楚原因，你可以解释下这种情况么？

**Comment by cardwing** [comment]
我当时的训练次数是120K到150K，你可以训练久一些。还有就是warmup pretraining也比较重要，即用一个较小的学习率先预训练一下网络，再正常训练。如果你是想在CULane上刷performance，你可以试一下这个repo里面的ERFNet-CULane-PyTorch，训练速度快效果也更好。

**Comment by vanilla000** [comment]
> 
> 
> @cardwing , 你好，我按照您给出的tensorflow—SCNN代码跑了下程序，迭代次数设置为60k，使用4块gpu，其余参数与SCNN论文中的也都保持一致，但最终的结果却差强人意，只达到了64%多，所以我想知道是否您使用了其他一些技巧来训练SCNN网络？
> 另一个问题是，当我使用单gpu进行训练时，得到的结果却比多gpu条件下的要高，我不清楚原因，你可以解释下这种情况么？

你好，我想问下你tensorflow下面gpu能直接启用吗？我一直都是只能用CPU跑，GPU启动不了
