### ISSUE TITLE
Lane / road marking / vanishing point dataset

### ISSUE THREAD

**Issue by SeokjuLee** [cardwing/Codes-for-Lane-Detection#258]
[VPGNet](https://arxiv.org/abs/1710.06288) dataset is available.
It contains around 21K images with human-annotated lane, road markings, and vanishing point labels.
For more details, please check our project [page](https://github.com/SeokjuLee/VPGNet#vpgnet-dataset).

**Comment by cardwing** [comment]
Thanks for your sharing. I will have a look at the released dataset. ^_^

**Comment by samhank** [comment]
Hello @cardwing , I wanted to the test the performance of ENet-Label on VPGNet dataset. What kind of modifications would be required ?

**Comment by cardwing** [comment]
I have not used this dataset. Maybe you can have a try and share your experience with us.
