### ISSUE TITLE
ERFNet For Tusimple dataset

### ISSUE THREAD

**Issue by spatial4d-bench** [cardwing/Codes-for-Lane-Detection#260]
作者您好！我想问下您在用ERFNet来训练CULane时是否用到了什么训练技巧，我在用ERFNet训练Tusimple数据集时，训练了60k，但结果总是不是很理想，训练集和测试集得出iou之间相差很大，训练集上iou达到0.96，但测试集只有0.47，我的学习速率和weight_decay这些参数设置都与您设置的一样

**Comment by cardwing** [comment]
你可以参考一下这个[issue](https://github.com/cardwing/Codes-for-Lane-Detection/issues/208)。

**Comment by yinhai86924** [comment]
您好 请问一下论文中提的ENet-SAD 指的是ERFNet？ERFNet-CULane-PyTorch add SAD？

**Comment by cardwing** [comment]
ENet和ERFNet是不同的模型。
