### ISSUE TITLE
About the ERFNet trained model

### ISSUE THREAD

**Issue by zy1817104** [cardwing/Codes-for-Lane-Detection#263]
the ERFNet trained model is invalid
Please provide another
Thanks!!!

**Comment by cardwing** [comment]
It runs well on my local server. What error do you get when loading the trained model?

**Comment by zy1817104** [comment]
Thanks for your reply.I have solved this problem.And I have 2 questions. 
1. what does the parameter(npb) mean in test_erfnet.sh? 
2. what does 'from models import sync_bn' mean in test_erfnet.py?
Thanks!

**Comment by cardwing** [comment]
The parameter is to control whether using sync bn. The original code is based on PyTorch 0.3.0 (not support sync bn) and we have to write the sync bn module by ourselves and import it. You can find the sync bn module in 8a04dd4.
