### ISSUE TITLE
test error in ERFNet

### ISSUE THREAD

**Issue by fongdier** [cardwing/Codes-for-Lane-Detection#265]
Hi cardwing, thanks for your sharing.
when i test the ERFNet, there is an error:
$ sh test_erfnet.sh 

Traceback (most recent call last):
  File "test_erfnet.py", line 13, in <module>
    from models import sync_bn
ImportError: cannot import name 'sync_bn'

and i found there is no sync_bn.py in the models ，how can i get it

**Comment by yassinekebbati** [comment]
Same problem here?! but i think this module is not needed and should be commented as there is no mention of it in the test_erfnet code! after commenting that import line I am receiving this error instead!

![image](https://user-images.githubusercontent.com/49916054/78413766-32fe2d80-7619-11ea-8ced-a91833cec518.png)

there is no mention of these arguments in the readme file though! could you guide me on this issue Mr cardwing?

**Comment by cardwing** [comment]
The original code is in this commit (8a04dd4). I have not tested the latest code and please debug it by yourself.

**Comment by daeunni** [comment]
@cardwing  how to solve it? Do I just modify to original version of this commit (https://github.com/cardwing/Codes-for-Lane-Detection/commit/8a04dd40b0fd53fe5348529af060871d401ee987) codes?
