### ISSUE TITLE
ERFNet-CULane-PyTorch model question

### ISSUE THREAD

**Issue by yoga-0125** [cardwing/Codes-for-Lane-Detection#266]
Can the ERFNet-CULane-PyTorch model be used to train TuSimple dataset?

**Comment by cardwing** [comment]
Yes. Just replace the original image list with the new one and modify the output channels of the model.

**Comment by yoga-0125** [comment]
May I ask that the pre-trained weight is only for ERFNet-CULane-Pytorch model or all of models? How can they share one pre-trained data with different structure?

**Comment by yoga-0125** [comment]
> Yes. Just replace the original image list with the new one and modify the output channels of the model.

May I ask that the pre-trained weight is only for ERFNet-CULane-Pytorch model or all of models? How can they share one pre-trained data with different structure?

In addition, why there are six "1" each lane (all 1s) for test dataset in ENet-TuSimple-Torch/list/list_test_new.txt? No any 0?

**Comment by cardwing** [comment]
1. Different models have different pre-trained weights (ENet and ERFNet are different models).
2. Just ignore the "1" in the list_test_new.txt. The six "1" are only added to facilitate evaluation using the same script.
