### ISSUE TITLE
关于bdd100k的评测方式

### ISSUE THREAD

**Issue by dxjundersky** [cardwing/Codes-for-Lane-Detection#269]
你好
我在ENet-BDD100K-Torch/train.lua中看到
Trainer:computeAccuracy里有一句注释：
-- This is not the final evaluation code.
-- This only gives primal evaluation for segmentation.
请问有提供final版本的评测代码么？

“The labels generated by our method are provided here (train and val). ”
这里生成的bdd车道线的二元标签，我解压之后看了下，或许因为bdd本身标注的质量，似乎很难把这些车道线实例化之后用SCNN的评测方式去评测。

**Comment by cardwing** [comment]
ENet-BDD100K-Torch里面包含了最终评测的代码。BDD100K的车道线标注确实不好用SCNN的评测方式去评测。
