### ISSUE TITLE
Is this Lanenet or SCNN?

### ISSUE THREAD

**Issue by hristo-vrigazov** [cardwing/Codes-for-Lane-Detection#27]
The repo says that this is an implementation of the "Spatial as Deep" paper: https://arxiv.org/abs/1712.06080, but it seems to implement Lanenet, which is this paper: https://arxiv.org/pdf/1807.01726.pdf
Moreover, this seems to be an unofficial fork of the Lanenet implementation available here: https://github.com/MaybeShewill-CV/lanenet-lane-detection

So, my question is, what exactly is the purpose of this fork, what model does it aim to implement?

**Comment by yujincheng08** [comment]
It's SCNN and modified from Lanenet. README of this repo says it clearly.

**Comment by cardwing** [comment]
Exactly.

**Comment by hristo-vrigazov** [comment]
Oh, sorry, my bad! Thanks for the clarification, don't know how I missed the acknowledgement. Keep up the good work!
