### ISSUE TITLE
training with bdd100k  dataset

### ISSUE THREAD

**Issue by feritte** [cardwing/Codes-for-Lane-Detection#273]
the script that you generate train and val is publicly available ? How you convert two line labels into one line labels ?

**Comment by cardwing** [comment]
`(From the ICCV paper) The lanes of BDD100K are labeled by two lines. Training the networks using the provided labels is tricky. Therefore, based on these two lines, we calculate the center lines as new targets.` The script is not released. However, just average the coordinates of two points and use a curve-fitting algorithm to generate one line from two lines. Please use the BDD100K lane generating script and do the modification mentioned above.

**Comment by feritte** [comment]
thanks a lot for your answer. even for Bezier curves, averaging works ? I`ll try it directly with the original script.

**Comment by cardwing** [comment]
Yes. You can have a try.
