### ISSUE TITLE
A question during training the CULane using the "SCNN tensorflow"

### ISSUE THREAD

**Issue by snowflake119** [cardwing/Codes-for-Lane-Detection#275]
hello,I am a newer ,I follow the advice in your net  one step by one step ,but there are some errors like this ,
1.I have installed cuda-10.1 ,is  the instruction "conda create -n tensorflow_gpu pip python=3.5
source activate tensorflow_gpu
pip install --upgrade tensorflow-gpu==1.3.0
pip3 install -r lane-detection-model/requirements.txt" and input " CUDA_VISIBLE_DEVICES="0" python tools/train_lanenet.py --net  /data/vgg16.npy  --image_path /demo_file/train_gt.txt /demo_file/val_gt.txt"right?
2..ModuleNotFoundError: No module named 'config'

**Comment by cardwing** [comment]
Please add `export PYTHONPATH=/path/to/Codes-for-Lane-Detection/SCNN-Tensorflow/lane-detection-model` in your .bashrc (use your path).
