### ISSUE TITLE
SCNN test error

### ISSUE THREAD

**Issue by souhasouha** [cardwing/Codes-for-Lane-Detection#276]
hello, i have some broblems when i try  testing your code 
(tensorflow) C:\Users\souhayla\Desktop\Codes\Codes\SCNNTensorflow\lane>python test_lanenet.py --weights_path C:\\Users\\souhayla\\Desktop\\Codes\\Codes\\SCNNTensorflow\\lane\\model\\culane_lanenet_vgg_2018-12-01-14-38-37.ckpt-10000 --image_path C:\\Users\\souhayla\\Desktop\\Codes\\Codes\\SCNNTensorflow\\lane\\demo_file\\1.jpg --save_dir C:\\Users\\souhayla\\Desktop\\Codes\\Codes\\SCNNTensorflow\\lane\\save
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

W0522 12:58:58.895710 12700 lazy_loader.py:50]
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

Traceback (most recent call last):
  File "test_lanenet.py", line 118, in <module>
    for line in g.readlines():
  File "C:\Users\souhayla\Anaconda3\envs\tensorflow\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 241: character maps to <undefined>

do you have any idea about this ???

**Comment by souhasouha** [comment]
i fixed the brobleme by adding '''''encoding='cp437'  '''''' when i want to open the file but i have another error 
Traceback (most recent call last):
  File "test_lanenet.py", line 121, in <module>
    test_lanenet(args.image_path, args.weights_path, args.use_gpu, img_name, args.batch_size, save_dir)
  File "test_lanenet.py", line 58, in test_lanenet
    test_dataset = lanenet_data_processor_test.DataSet(image_path, batch_size)
  File "C:\Users\souhayla\Desktop\Codes\Codes\SCNNTensorflow\lane\lanenet_data_processor_test.py", line 30, in __init__
    self._img_list = self._init_dataset()
  File "C:\Users\souhayla\Desktop\Codes\Codes\SCNNTensorflow\lane\lanenet_data_processor_test.py", line 48, in _init_dataset
    img_list.append(info_tmp[0][1:])
IndexError: list index out of range

**Comment by cardwing** [comment]
You can print the length of the list and current index to debug.

**Comment by souhasouha** [comment]
i fixed it thanks but finnly i have another one that the checkpoint are not
valid i didn't understand why !!!
