### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by experiencor** [cardwing/Codes-for-Lane-Detection#28]
awesome work, do you mind producing a demo on a random dashcam video

**Comment by cardwing** [comment]
@experiencor, this is the [demo video](https://drive.google.com/open?id=1cAB_DCzhQqp3Y07bP0YBiLD6QRzS-CEJ) which records the performance of SCNN-Tensorflow on a consecutive sequence of video frames. Since SCNN-Tensorflow is trained on image-based datasets, the performance is unstable.

**Comment by KevinWalkerFan** [comment]
Can u share the matlab code to do the performance of SCNN-Tensorflow on a consecutive sequence of video frames?

**Comment by cardwing** [comment]
@KevinWalkerFan, just go to [SCNN](https://github.com/XingangPan/SCNN) and do the evaluation using the matlab code it provides.

**Comment by YilmazOrkun** [comment]
Dear @cardwing 
How did you inference the video? Do you have any suggestions on how to inference with real time recording from a webcam or a video file?
