### ISSUE TITLE
Evaluate test result issue run.sh using ERFNet-CULane-PyTorch for TuSimple data

### ISSUE THREAD

**Issue by yoga-0125** [cardwing/Codes-for-Lane-Detection#280]
------------Configuration---------
anno_dir: ./segGT6/0601/
detect_dir: ./tools/prob2lines/output/vgg_SCNN_DULR_w9/clips/0601/
im_dir: ./clips/0601/
list_im_file: ./list/test_img.txt
width_lane: 30
iou_threshold: 0.3
im_width: 1640
im_height: 590
-----------------------------------
Evaluating the results...
tp: 0 fp: 0 fn: 0
no positive detection
no ground truth positive
finished process file
precision: -1
recall: -1
Fmeasure: -1
----------------------------------

Any advice? 
Thank you very much.

**Comment by cardwing** [comment]
It seems that both labels and model predictions are not correctly read. Please check the path of predictions and labels.
