### ISSUE TITLE
how to convert scnn pytorch model to caffe model?

### ISSUE THREAD

**Issue by snowflake119** [cardwing/Codes-for-Lane-Detection#282]
Dear sir :
     I have trained the scnn net ,now I want to convert the scnn pytorch model to caffe model ,I have no idea ,can you give me some advice ,thank you

**Comment by cardwing** [comment]
See [this link](https://github.com/xxradon/PytorchToCaffe).

**Comment by snowflake119** [comment]
Thank you very much

**Comment by snowflake119** [comment]
Does this link work?

**Comment by cardwing** [comment]
I have not used that code. You can have a try.

**Comment by snowflake119** [comment]
thank you 




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"HOU Yuenan"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月3日(星期三) 上午9:53
收件人:&nbsp;"cardwing/Codes-for-Lane-Detection"<Codes-for-Lane-Detection@noreply.github.com&gt;;
抄送:&nbsp;"葛恒赫"<380768194@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cardwing/Codes-for-Lane-Detection] how to convert scnn pytorch model to caffe model? (#282)





 
I have not used that code. You can have a try.

**Comment by snowflake119** [comment]
have you tried any network from pytorch model to caffemodel ,I have tried the tool you recommend to me last week ,but I have met many errors ,can you help me or some advice ,the detail problem I can provide ,it is so long
