### ISSUE TITLE
ONE PROBLEM in the evaluation method for CULane in ERFNet-CULane-PyTorch

### ISSUE THREAD

**Issue by yoga-0125** [cardwing/Codes-for-Lane-Detection#290]
Hi, I have one question regarding to the CULane evaluation method. My thought may be not correct, but please read it and give me some suggestions if possible, thank you. 

- In CULane, different images may have different lane end point labelling (eg. **280**, **410** ...)
- When extracting lane points from prob maps, the number of points determine the end point of lanes (eg. **m**=15 points result in the end points of lanes are **310**)
- Predicted lane (310) can be shorter than ground truth (280) **["estimation is not enough"]** or longer than ground truth (410) **["over estimation"]**
- As the attached figure shown, I thought lane fitting is evaluated with almost same length, but here, different length of prediction and ground truth also affects on false positive and false negative

![Capture](https://user-images.githubusercontent.com/57866841/84536909-cf4d4c00-acbc-11ea-94d8-656374151574.PNG)

**Comment by cardwing** [comment]
That's true. Evaluating the lanes with the same length is wrong. You can have a look at the codes to learn how it performs evaluation.
