### ISSUE TITLE
DL vs CV

### ISSUE THREAD

**Issue by Mouiad-JRA** [cardwing/Codes-for-Lane-Detection#291]
Hi there, my project is a comparison between computer vision and deep learning for self-driving cars and i'm using your model for DL.
The problem  I'm currently facing is when I compare the two parts (DL vs CV) together through IoU and F-measure , the datasets labels (imagename.line.txt) which  contains the lines coordinates (the end points) are usually  three or  Four lines of points in the line.txt files, this labels are very good for the SCNN but for the CV its very bad, to improve that, the labels must be 2  lines of points not four for each image.
How Can i do that? and if that possible , it will effect badly for the SCNN?

**Comment by cardwing** [comment]
What is the CV approach? I understand that DL methods adopt CNN to perform lane detection. Does the CV approach only predict two lines in the image? If yes, you can just force SCNN to predict two lines as well.

**Comment by Mouiad-JRA** [comment]
The structure of the computer vision that I use is in the following 
 (https://github.com/sujaybabruwad/Advanced-Lane-Detection)
The CV does not draw two lines, but rather draws the path along the entire Road, but I have already applied your idea, i.e.  force the CV to predict only two lines, but the problem lies with which two lines must I predict with, because CV output (after modification) is two lines Coordinates, but compared to labels , this output cannot be known, sometimes Unrecognizable of any of these lines Coordinates, Meaning these two lines (cv output) maybe match to the first two line in the labels or the second and the third line or the first and the third line....etc
Do you have an idea to solve this problem?
