### ISSUE TITLE
Testing on own data

### ISSUE THREAD

**Issue by asarkar1** [cardwing/Codes-for-Lane-Detection#292]
I am trying to test the algorithm for my own data. Is it possible? Apparently, it looks like the code is built to run on specified datasets. Can you please help me to edit and run this on custom data.

**Comment by cardwing** [comment]
You can just prepare the data in the same manner as CULane or similar datasets. Then, simply making the codes run on your own data and carefully debug the codes if the performance is unsatisfactory.
