### ISSUE TITLE
broken ERFNet_trained.tar of ERFNet-CULane-PyTorch

### ISSUE THREAD

**Issue by seeingwu** [cardwing/Codes-for-Lane-Detection#293]
Any new version? Thanks !!!!!!

**Comment by cardwing** [comment]
The file looks fine. Just download the trained model and put it in the desired folder. Do not extract files from the .tar file.

**Comment by seeingwu** [comment]
Thanks, I want to test my images by the trained model, 
when I ran the **python test_erfnet.py** in anaconda prompt, the error was
_"Traceback (most recent call last):
  File "test_erfnet.py", line 13, in <module>
    from models import sync_bn
ImportError: cannot import name 'sync_bn' from 'models' "_
Then I omitted the " from models import sync_bn" in test_erfnet.py;
But I still have no idea how to get right test results. Can you show some details about the test? Thanks so much!

**Comment by jujujuxb** [comment]
> 谢谢，我想通过训练有素的模型来测试我的图像，
> 当我在anaconda提示符下运行**python test_erfnet.py**时，错误是
> _“ Traceback（最近一次调用最后一次）： 文件“ test_erfnet.py”，第13行， 来自模型import sync_bn ImportError：无法从'models'中导入名称'sync_bn'“_
> 然后我在test_erfnet.py中省略了” from models import sync_bn“;
> 但是我仍然不知道如何获得正确的测试结果。您可以显示有关测试的一些详细信息吗？非常感谢！

请问你使用预训练模型测试自己的图像成功了吗

**Comment by foxkw** [comment]
> 
> 
> Thanks, I want to test my images by the trained model,
> when I ran the **python test_erfnet.py** in anaconda prompt, the error was
> _"Traceback (most recent call last): File "test_erfnet.py", line 13, in from models import sync_bn ImportError: cannot import name 'sync_bn' from 'models' "_
> Then I omitted the " from models import sync_bn" in test_erfnet.py;
> But I still have no idea how to get right test results. Can you show some details about the test? Thanks so much!

Have you solved it? I met the same question
