### ISSUE TITLE
What will happen after removing exist_loss?

### ISSUE THREAD

**Issue by garryz94** [cardwing/Codes-for-Lane-Detection#294]
Hi @cardwing , first I want to thank you for sharing your excellent work, it really helps!
I want to train erfnet-sad on my own data, but the number of lanes in my custom data varies a lot. So clearly, I don't have exist_file for my own data and it is hardly possible for me to calculate it. So what will happen when I remove the exist loss from the network?

**Comment by cardwing** [comment]
If you remove the exist loss, you may not use the F1-measure as the evaluation criterion since it needs to differentiate each lane instance (or you can use the clustering module to help differentiate lane instances). And I think the removal of exist loss won't greatly affect the pixel-level accuracy. You can have a try.

**Comment by garryz94** [comment]
> If you remove the exist loss, you may not use the F1-measure as the evaluation criterion since it needs to differentiate each lane instance (or you can use the clustering module to help differentiate lane instances). And I think the removal of exist loss won't greatly affect the pixel-level accuracy. You can have a try.

Thanks for your quick reply! I will try it.
Different from CULane and TuSimple, my own data only have semantic-segmentation-style ground truth. In other words, when some obstacles occludes the lane line or when it comes to dash-style lane line , the imaginary lane is not labelled which is different from the above lane detection dataset. So should I do something to preprocess my data?

**Comment by cardwing** [comment]
You just need to check the size of your input images and make sure that data augmentation is rational.

**Comment by garryz94** [comment]
> You just need to check the size of your input images and make sure that data augmentation is rational.

In this way, SAD will act more like a semantic segmentation algorithm than a lane detection model? Am I right?

**Comment by cardwing** [comment]
Yes.

**Comment by garryz94** [comment]
> Yes.

Thanks for your reply.
