### ISSUE TITLE
Where is the distillation loss in ERFNet-CULane-Pytorch?

### ISSUE THREAD

**Issue by garryz94** [cardwing/Codes-for-Lane-Detection#296]
Hi @cardwing 
I am reviewing the code of ERFNet-CULane-Pytorch, but I can't find distillation_loss in the code. It seems that when I run train_erfnet.py I only train ERFNet without any self-distillation process. I am so confused, can you help me with this problem? It will be very appreciated!

**Comment by cardwing** [comment]
Please add the distillation loss by yourself.

**Comment by garryz94** [comment]
> Please add the distillation loss by yourself.

This makes more sense to me, thanks.

**Comment by wangzeyu135798** [comment]
@cardwing ,your answer is interesting.

**Comment by wangzeyu135798** [comment]
@garryz94 Hi, have you finished the code with SAD?
