### ISSUE TITLE
GPU无法使用

### ISSUE THREAD

**Issue by vanilla000** [cardwing/Codes-for-Lane-Detection#297]
大佬你好，我想问下我这边用的tensorflow训练的时候，gpu一直启用不了，config里面也设置了一个，但是跑的时候一直是使用的cpu，是不是我还有哪个位置没有设置呢？能否解答一下，谢谢！

**Comment by cardwing** [comment]
你可以先检查一下GPU版的Tensorflow是否正确安装。如果正确安装了，再根据官网上的GPU使用教程看看哪里出错了。
