### ISSUE TITLE
Confidence about results

### ISSUE THREAD

**Issue by yushengyushengb** [cardwing/Codes-for-Lane-Detection#298]
Is there any data from results about confidence about results ? I mean how to measure the confidence of results ?

**Comment by cardwing** [comment]
What do you mean by the confidence about results? Does it mean the model confidence about the prediction?

**Comment by yushengyushengb** [comment]
If i use the model to detect lanes in one video, and i will get some detection results based on every image. If there are some wrong detection results in few images, and i need smooth them.
One idea is if i know the confidence about the detection results in every image, maybe i can skip the wrong detection results.
The confidence results are the Credibility of the results.

**Comment by cardwing** [comment]
Maybe you can refer to this paper "Addressing Failure Prediction by Learning Model Confidence".
