### ISSUE TITLE
Label  new data

### ISSUE THREAD

**Issue by SuperPengXue** [cardwing/Codes-for-Lane-Detection#30]
could you tell me Which annotation tool do you use?,I want label my data. thinks.

**Comment by SuperPengXue** [comment]
the ground truth in <laneseg_label_w16>,  the gray value of most left lane  is 1 , and left lane  is 2, right lane is 3, most right lane  is 4.   right？

**Comment by cardwing** [comment]
@SuperPengXue, I use popular lane detection datasets to perform experiments and do not annotate the images myself. As to the ground-truth labels of CULane, your understanding is right and 0 denotes background.
