### ISSUE TITLE
Lane width of BDD100K

### ISSUE THREAD

**Issue by melondd** [cardwing/Codes-for-Lane-Detection#300]
Hi, I understand that you set the pixel thickness of BDD100K to 8 pixels during training. But why did you set the thickness to 2 pixels in the validation and test set?

I wonder if this is a fair comparison. Doesn't the test set also have to be 8 pixels for accurate comparison?

**Comment by cardwing** [comment]
If I remember it correctly, 2 pixels are the original width of lanes in BDD100K. Ideally, we should keep lanes unchanged during both training and testing. However, using lanes with 2-pixel width is hard to make models learn to detect these lanes accurately. Increasing the width of lanes during training is to help models better detect lanes.

**Comment by melondd** [comment]
Thanks for the answer, 
but since you used pixel accuracy and IOU for evaluation, isn't it correct for the test set to also use 8 pixel wide lanes as GT labels? 
The reason why the IOU and pixel accuracy is low in the paper is that the GT label is 2 pixels thick, but the model outputs 8 pixels thick lane, right?
