### ISSUE TITLE
ERFNet-CULane-Pytorch testing on custom images

### ISSUE THREAD

**Issue by nisha1729** [cardwing/Codes-for-Lane-Detection#304]
Hi,  

Do you have the implementation to test this model on a custom image which is not part of any dataset? As far as I understand, ```test_erfnet.py``` needs labels. Thanks!

**Comment by cardwing** [comment]
`test_erfnet.py` does not need the label since it merely performs inference on the input images using the trained model.

**Comment by nisha1729** [comment]
When I run it without labels, I get the following error: 

```
=> loading checkpoint 'trained/ERFNet_trained.tar'
Traceback (most recent call last):
  File "D:/.../Codes-for-Lane-Detection/ERFNet-CULane-PyTorch/test_erfnet.py", line 257, in <module>
    main()
  File "D:/.../Codes-for-Lane-Detection/ERFNet-CULane-PyTorch/test_erfnet.py", line 71, in main
    getattr(ds, args.dataset.replace("CULane", "VOCAug") + 'DataSet')(data_list=args.val_list, transform=torchvision.transforms.Compose([
  File "D:...\Codes-for-Lane-Detection\ERFNet-CULane-PyTorch\dataset\voc_aug.py", line 20, in __init__
=> loaded checkpoint 'False' (epoch 10)
    self.label_list.append(dataset_path.replace('/list/', '') + line.strip().split(" ")[1])
IndexError: list index out of range

Process finished with exit code 1
```
Right now, I'm using it by putting some dummy values as labels, for example: ``` /driver_161_90frame/06030819_0755.MP4/IMG_4603_cr3.JPG /laneseg_label_w16/driver_161_90frame/06030819_0755.MP4/00000.png 1 1 1 1 ```

**Comment by cardwing** [comment]
I see. The error comes from the dataloader. Your practice is a potential solution.
