### ISSUE TITLE
ERFNet-CULane-PyTorch

### ISSUE THREAD

**Issue by foxkw** [cardwing/Codes-for-Lane-Detection#308]
I see "Please follow list to put CULane in the desired folder."

I have downloaded the CULane .

(1)should I put CULane into diretory"dataset"
 (2)CULane have many files ,  but the above list just show    test_img.txt 、train_gt.txt、val_gt.txt 
I don't know how to  follow list to put CULane in the desired folder.
I will be grateful if u can answer

**Comment by nisha1729** [comment]
1. No, ```dataset``` folder contains the data loader
2.  You have to see the directory written in these .txt files and put the CULane folders accordingly. For example, ```train_gt.txt``` has ```/driver_23_30frame/05151649_0422.MP4/00000.jpg /laneseg_label_w16/driver_23_30frame/05151649_0422.MP4/00000.png 1 1 1 1
``` so you need to put the folder ```driver_23_30frame``` (and ```laneseg_label_w16``` for the labels) in your working directory. You can put the folders for train, val and test in the working directory and it should work.

**Comment by cardwing** [comment]
You can just refer to the files in [this folder](https://github.com/cardwing/Codes-for-Lane-Detection/tree/master/ERFNet-CULane-PyTorch/list).
