### ISSUE TITLE
./test.sh: 8: ./test.sh: th: not found

### ISSUE THREAD

**Issue by foxkw** [cardwing/Codes-for-Lane-Detection#309]
Question about **ENet-TuSimple-Torch**

May I ask why I get error"sh ./laneExp/ENet-model/test.sh
./laneExp/ENet-model/test.sh: 8: ./laneExp/ENet-model/test.sh: th: not found " 
  When I run the code `cd $ENet_TuSimple_ROOT
sh ./laneExp/ENet-model/test.sh` . 

I do have that directory"./laneExp/ENet-model/test.sh"

**Comment by cardwing** [comment]
It seems that either Torch is not properly installed or the path to your Torch has not been added to the .bashrc.
