### ISSUE TITLE
BDD100K Lane preprocessing

### ISSUE THREAD

**Issue by ghost** [cardwing/Codes-for-Lane-Detection#310]
> BDD100K just records the coordinates of the lane points as annotations. Hence, to calculate the centerline, you just average the coordinates of two neighboring points and the averaged value is just the coordinate of the lane point for the centerline. For the testing set, I also do the same operation. And I will upload the scripts of processing the annotations of BDD100K soon.

Can you share the implementation details of preprocessing the lanes as the process of combining two lines to form a centerline is not clear?

_Originally posted by @know-one-1 in https://github.com/cardwing/Codes-for-Lane-Detection/issues/127#issuecomment-737245029_

**Comment by cardwing** [comment]
You just average the coordinates of each point in two neighbouring lines and then connect these averaged coordinates to form the center line. You can refer to the processed labels for more details.
