### ISSUE TITLE
Some questiones on tensorflow version on CULane

### ISSUE THREAD

**Issue by hustcc19860606** [cardwing/Codes-for-Lane-Detection#312]
Following the README， i can get:

anno_dir: /home/cc/SCNN-Tensorflow/data/CULane/
detect_dir: /home/cc/SCNN-Tensorflow/data/CULane/result-matlab/scnncastedBGR/vgg_SCNN_DULR_w9/data/CULane/
im_dir: /home/cc/SCNN-Tensorflow/data/CULane/
list_im_file: /home/cc/SCNN-Tensorflow/data/CULane/test.txt
width_lane: 30
iou_threshold: 0.5
im_width: 1640
im_height: 590
Evaluating the results...
tp: 76970 fp: 34736 fn: 27916
finished process file
precision: 0.689041
recall: 0.733844
Fmeasure: 0.710737

My questiones have two:

1.The gap between 0.710737 and 71.3 i s caused by tensorflow?
2.If i want to reproduce the result by a new training, do i need to modify the VGG_MEAN = [123.68, 116.779, 103.939] into VGG_MEAN = [103.939, 116.779, 123.68] in lanenet_data_processor.py?

@cardwing

**Comment by cardwing** [comment]
1. Maybe yes. You can refer to previous issues for more details.
2. You can test both variants.

**Comment by hustcc19860606** [comment]
From question 81#，i find“My original model can achieve around 69.5 when training from scratch.” from your answer. However, i only get 68.164 on F1-measure. And the training takes 90000 epoches as the your setting. Do you take some tricks on the original model?
@cardwing

**Comment by akshatbhutra** [comment]
@cardwing, I have a question regarding how the probability maps are saved.
I have only one probability map for each image in which all the lane markings are together. But it seems that I need to separate that into many probability maps each having a single lane only. How to do that? 
Thanks.
