### ISSUE TITLE
segLabelGen0生成label.png图 全黑

### ISSUE THREAD

**Issue by weijian555** [cardwing/Codes-for-Lane-Detection#313]
我使用了segLabelGen0的代码，创建tusimple数据集的instance-label,但是结果。png显示全黑。请问是什么原因呢？正常的结果图是灰度图然后用不同的灰度表示不同的实例吗？
![image](https://user-images.githubusercontent.com/54135879/102089974-d9acf600-3e57-11eb-970d-141ffd47c05e.png)

**Comment by weijian555** [comment]
上图确实存在不同灰度标注的车道线，人眼不容易看到。
另外，我想请教一下问题，我使用SCNN-tensorflow时，训练过程如下：
![image](https://user-images.githubusercontent.com/54135879/102164365-37782700-3ec6-11eb-94c9-358786eed4c3.png)
accuracy=0,accuracy_back=1。不知道是什么原因造成。

**Comment by cardwing** [comment]
你可以把标签图的值打印出来看看，理论上应该就是0-4之间。至于SCNN-Tensorflow的问题，你可以翻翻之前的issue，看看有没有人问过这个问题。

**Comment by miao02830** [comment]
> 我使用了segLabelGen0的代码，创建tusimple数据集的instance-label,但是结果。png显示全黑。请问是什么原因呢？正常的结果图是灰度图然后用不同的灰度表示不同的实例吗？ ![image](https://user-images.githubusercontent.com/54135879/102089974-d9acf600-3e57-11eb-970d-141ffd47c05e.png)



> 我使用了segLabelGen0的代码，创建tusimple数据集的instance-label,但是结果。png显示全黑。请问是什么原因呢？正常的结果图是灰度图然后用不同的灰度表示不同的实例吗？ ![image](https://user-images.githubusercontent.com/54135879/102089974-d9acf600-3e57-11eb-970d-141ffd47c05e.png)

请问您是把segLabelGen0.py跑通了吗？我这里遇到一个问题，想请教您怎么解决的，谢谢您。
TypeError: sort() takes no positional arguments

when running the line: lanes.sort(lane_cmp).

def lane_cmp(a, b): ......
