### ISSUE TITLE
What's the accuracy and mIoU of your weight on train and val part of CUlane dataset?

### ISSUE THREAD

**Issue by hustcc19860606** [cardwing/Codes-for-Lane-Detection#314]
I want to reproduce the outcome of your weight shared in this projection.
Can you share the the accuracy and mIoU of your weight 'culane_lanenet_vgg_2018-12-01-14-38-37.ckpt-10000' on train and val part of CUlane dataset?
In previous issues, you tell us the accuracy of your weight on train part of CUlane dataset is around 0.95.
@cardwing

**Comment by cardwing** [comment]
On CULane, we mainly report the f1-measure. I think the pretrained weight can achieve 71.3 f1 on CULane.
