### ISSUE TITLE
Where is the distillation loss reflected in your code？

### ISSUE THREAD

**Issue by Jiawen-huang** [cardwing/Codes-for-Lane-Detection#315]
Where is the distillation loss reflected in your code？
The total is : loss_tot = loss + loss_exist * 0.1. I fail to find the distillation loss. 
in https://github.com/cardwing/Codes-for-Lane-Detection/blob/a224eb4d38cf3294ea80b2d4181f8afe028d801e/ERFNet-CULane-PyTorch/train_erfnet.py#L151

**Comment by cardwing** [comment]
The self distillation loss is not added in the pytorch code. You need to add it on your own.

**Comment by Jiawen-huang** [comment]
can you show me an example of how to add the self distillation loss in the pytorch code？

**Comment by cardwing** [comment]
You can refer to the [torch code](https://github.com/cardwing/Codes-for-Lane-Detection/blob/master/ENet-Label-Torch/models/init.lua#L58).

**Comment by miao02830** [comment]
请问您添加成功了吗

**Comment by Debugerss** [comment]
。。。。
