### ISSUE TITLE
./train_erfnet.sh: 5: ./train_erfnet.sh: --resume: not found

### ISSUE THREAD

**Issue by foxkw** [cardwing/Codes-for-Lane-Detection#316]
Hi,cardwing!  I met such errors when I run train_erfnet.py in  ERFNet-CULane-PyTorch .  
1) miou /loss/acc didn't change 
2)--resume: not found.
 => loading checkpoint './pretrained/ERFNet_pretrained.tar'
#reused param: 302
=> loaded checkpoint 'False' (epoch 16)

but I try to change path to absolute path in `train_erfnet.sh`, but it still doesn't work 
do you know why . thanks you so much!

`  
Test: [0/1210]	Time 9.200 (9.200)	Loss 1.9601 (1.9601)	Pixels Acc 0.103	mIoU 0.029
Test: [1/1210]	Time 0.161 (4.681)	Loss 1.9305 (1.9453)	Pixels Acc 0.103	mIoU 0.029
Test: [2/1210]	Time 0.161 (3.174)	Loss 1.9759 (1.9555)	Pixels Acc 0.103	mIoU 0.029
Test: [3/1210]	Time 0.161 (2.421)	Loss 1.9295 (1.9490)	Pixels Acc 0.103	mIoU 0.029
Test: [4/1210]	Time 0.182 (1.973)	Loss 1.8976 (1.9387)	Pixels Acc 0.100	mIoU 0.028
 .....
.....
Test: [1208/1210]	Time 0.193 (0.228)	Loss 1.9116 (1.9595)	Pixels Acc 0.106	mIoU 0.031
Test: [1209/1210]	Time 0.451 (0.228)	Loss 1.9140 (1.9595)	Pixels Acc 0.106	mIoU 0.031
Testing Results: Pixels Acc 0.106	mIoU 0.031 (0.0312)	Loss 1.95952
./train_erfnet.sh: 5: ./train_erfnet.sh: --resume: not found
`

**Comment by foxkw** [comment]
> Hi,cardwing! I met such errors when I run train_erfnet.py in ERFNet-CULane-PyTorch .
> 
>     1. miou /loss/acc didn't change
>        2)--resume: not found.
>        => loading checkpoint './pretrained/ERFNet_pretrained.tar'
>        #reused param: 302
>        => loaded checkpoint 'False' (epoch 16)
> 
> 
> but I try to change path to absolute path in `train_erfnet.sh`, but it still doesn't work
> do you know why . thanks you so much!
> 
> ` Test: [0/1210] Time 9.200 (9.200) Loss 1.9601 (1.9601) Pixels Acc 0.103 mIoU 0.029 Test: [1/1210] Time 0.161 (4.681) Loss 1.9305 (1.9453) Pixels Acc 0.103 mIoU 0.029 Test: [2/1210] Time 0.161 (3.174) Loss 1.9759 (1.9555) Pixels Acc 0.103 mIoU 0.029 Test: [3/1210] Time 0.161 (2.421) Loss 1.9295 (1.9490) Pixels Acc 0.103 mIoU 0.029 Test: [4/1210] Time 0.182 (1.973) Loss 1.8976 (1.9387) Pixels Acc 0.100 mIoU 0.028 ..... ..... Test: [1208/1210] Time 0.193 (0.228) Loss 1.9116 (1.9595) Pixels Acc 0.106 mIoU 0.031 Test: [1209/1210] Time 0.451 (0.228) Loss 1.9140 (1.9595) Pixels Acc 0.106 mIoU 0.031 Testing Results: Pixels Acc 0.106 mIoU 0.031 (0.0312) Loss 1.95952 ./train_erfnet.sh: 5: ./train_erfnet.sh: --resume: not found`



I just solved it by change   `p=1`in .sh ,  but I get such error .  need to modify the network layer ？？
`=> loading checkpoint 'pretrained/ERFNet_pretrained.tar'
Traceback (most recent call last):
  File "train_erfnet.py", line 292, in <module>
    main()
  File "train_erfnet.py", line 67, in main
    model.load_state_dict(checkpoint['state_dict'])
  File "/home/ubuntu-502/xiong/lane/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DataParallel:
	Missing key(s) in state_dict: "module.lane_exist.layers.0.weight", "module.lane_exist.layers.1.weight", "module.lane_exist.layers.1.bias", "module.lane_exist.layers.1.running_mean", "module.lane_exist.layers.1.running_var", "module.lane_exist.layers_final.1.weight", "module.lane_exist.layers_final.1.bias", "module.lane_exist.linear1.weight", "module.lane_exist.linear1.bias", "module.lane_exist.linear2.weight", "module.lane_exist.linear2.bias". 
	size mismatch for module.encoder.output_conv.weight: copying a param with shape torch.Size([37, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([5, 128, 1, 1]).
	size mismatch for module.encoder.output_conv.bias: copying a param with shape torch.Size([37]) from checkpoint, the shape in current model is torch.Size([5]).
	size mismatch for module.decoder.output_conv.weight: copying a param with shape torch.Size([16, 37, 2, 2]) from checkpoint, the shape in current model is torch.Size([16, 5, 2, 2]).
	size mismatch for module.decoder.output_conv.bias: copying a param with shape torch.Size([37]) from checkpoint, the shape in current model is torch.Size([5]).
`

**Comment by cardwing** [comment]
Can you print the resume path? I think the problem is not difficult to fix.
