### ISSUE TITLE
use docker to run the Code-for-Lane-Detection show ResourceExhaustedError 

### ISSUE THREAD

**Issue by bluseking** [cardwing/Codes-for-Lane-Detection#317]
when I use docker to train the model, it shows the flowing error:

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[8,72,200,256]
         [[Node: tower_0/lanenet_loss/inference/encode/conv3_1/conv/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](tower_0/lanenet_loss/inference/encode/pool2, lanenet_loss/inference/encode/conv3_1/conv/W/read)]]
         [[Node: tower_1/lanenet_loss_1/Mean_1/_1033 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_47253_tower_1/lanenet_loss_1/Mean_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

E0109 03:10:55.412494 171 tf_logging.py:74] Exception in QueueRunner: Enqueue operation was cancelled
         [[Node: batch/fifo_queue_enqueue = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, data_augmentation/Sub/_49, data_augmentation/Cast_1/_51, data_augmentation/Cast_2/_53)]]
E0109 03:10:55.415374 171 tf_logging.py:74] Exception in QueueRunner: Enqueue operation was cancelled
         [[Node: prefetch_queue/fifo_queue_enqueue = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](prefetch_queue/fifo_queue, batch, batch:1, batch:2)]]

thanks for your help

**Comment by cardwing** [comment]
What's your GPU type and memory size? The SCNN model is very cumbersome and you may need to reduce the batch size or the image size if you do not have enough GPU memory.
