### ISSUE TITLE
the script which draw the dataset LLAMAS json label to image for 5 classification

### ISSUE THREAD

**Issue by noobliang** [cardwing/Codes-for-Lane-Detection#318]
Hi, author, I encountered a problem.  How do I get the llamas image label for 5 classification. There hava a script seem to obtain binary segmentation image or multi_class_segmentation_label (l1, l0, r0, r1), whirch are 3-channel image.  How to get  1-channel label like the CULane label.   Thanks very much.

**Comment by cardwing** [comment]
You can just use the argmax function to get the index of the maximum activation in each pixel of the multi-class label.

**Comment by noobliang** [comment]
> You can just use the argmax function to get the index of the maximum activation in each pixel of the multi-class label.

thank for your reply

**Comment by noobliang** [comment]
> You can just use the argmax function to get the index of the maximum activation in each pixel of the multi-class label.

作者你好，我还碰到了ERFnet+sad在TuSimple 数据集上精度提不上，一直在95.3% 左右和ENet+sad的96.64%差距有点大，试了deep supervision也没用，而且我训练的是6条车道线。是不是线条的数量也有影响。作者能给什么建议吗。
