### ISSUE TITLE
您好 请问如何解决

### ISSUE THREAD

**Issue by HejhGitHub** [cardwing/Codes-for-Lane-Detection#319]
您好 我是一个小白。运行sh ./test_erfnet.sh
Traceback (most recent call last):
  File "test_erfnet.py", line 13, in <module>
    from models import sync_bn
ImportError: cannot import name 'sync_bn'
请问该如何解决

**Comment by cardwing** [comment]
你可以找一下之前的commit。目前版本的sync bn我没有测试过。

**Comment by daeunni** [comment]
@cardwing  how to solve it? Do I just modify to original version of this commit (https://github.com/cardwing/Codes-for-Lane-Detection/commit/8a04dd40b0fd53fe5348529af060871d401ee987) codes?
