### ISSUE TITLE
Which paper is ERFNet-CULane-PyTorch based on?

### ISSUE THREAD

**Issue by nisha1729** [cardwing/Codes-for-Lane-Detection#321]
Hi, could you tell which paper you used for the codes in ERFNet-CULane-Pytorch? I believe the underlying model is this: [ERFNet: Efficient Residual Factorized ConvNet for Real-time Semantic Segmentation](http://www.robesafe.es/personal/eduardo.romera/pdfs/Romera17tits.pdf). Can you explain how you modified it for lane detection? Thanks!

**Comment by cardwing** [comment]
Basically, we take the ERFNet as the segmentation backbone(Encoder + Decoder) and add the lane existence prediction branch following the original SCNN paper. More details can be found in the model definition of ERFNet-CULane-PyTorch. Note that some preprocessing operations and training strategies also matter.

**Comment by nisha1729** [comment]
Thank you!
