### ISSUE TITLE
关于bdd100k标签生成疑问

### ISSUE THREAD

**Issue by Cverlpeng** [cardwing/Codes-for-Lane-Detection#322]
作者您好，
感谢你提供这么优秀的开源项目！

关于bdd100k标注生成我存在一些疑问，如何从没有标记成对儿车道线中确定其为一组车道线呢，可以分享具体的做法吗？如果可以能提供一下脚本吗？非常感谢！

**Comment by cardwing** [comment]
处理得到的车道线在这个[repo](https://github.com/cardwing/Codes-for-Lane-Detection/tree/master/ENet-BDD100K-Torch)。具体做法可以参考我们的论文的描述。

**Comment by jyang68qq** [comment]
@cardwing Hello. 请问你们是如何从json文件中提取[1 1 1 1]格式的probability map的GT的信息呢？我用的llamas数据集。我能看到你们在官方的repo中有这个的gt。

**Comment by cardwing** [comment]
这个可以直接通过判断标签图里有没有相应车道线 (例如1, 2, 3, 4) 的pixel来生成prob map。
