### ISSUE TITLE
How can we test the model using CPU device?

### ISSUE THREAD

**Issue by Chirag1997aggarwal** [cardwing/Codes-for-Lane-Detection#323]
If testing with a CPU device is possible, How can we perform that?
Is resizing  of images is required for using the data from Tusimple test dataset?

I have tried below command -
**`python tools/test_lanenet.py --weights_path /mnt/usmidet/projects/FORD-DAT/8-Users/GT_Validation_Team/Chirag/CGQ-2485/Codes-for-Lane-Detection-master/weights/model_culane-71-3/culane_lanenet_vgg_2018-12-01-14-38-37.ckpt-10000 --image_path /mnt/usmidet/projects/FORD-DAT/8-Users/GT_Validation_Team/Chirag/CGQ-2485/Codes-for-Lane-Detection-master/img.txt --save_dir /mnt/usmidet/projects/FORD-DAT/8-Users/GT_Validation_Team/Chirag/CGQ-2485/Codes-for-Lane-Detection-master/output_pre/ --use_gpu 0`**

get the below output on terminal - 
![image](https://user-images.githubusercontent.com/55729702/114029161-de7a3780-9896-11eb-9b5c-54d102cfddf5.png)

As you can see I have not got any error on terminal but yet not found the output images in output folder.

Kindly help.

**Comment by cardwing** [comment]
It seems that the code works normally. Can you go to places where variable save_dir is used and check the details? I think the bug is not difficult to fix.
