### ISSUE TITLE
关于Ground truth

### ISSUE THREAD

**Issue by foxkw** [cardwing/Codes-for-Lane-Detection#325]
你好，我想问下CULane中标签图片在人眼看来是全黑的。 如何处理可以让不同车道线像素点有不同的颜色呢？就像论文中实验部分Fig7的一样。
![图片](https://user-images.githubusercontent.com/57212196/117540816-86745380-b043-11eb-9e6f-e4d25031d4b7.png)

**Comment by cardwing** [comment]
你可以直接根据ground-truth的label (HxW)，得到不同车道线的mask ((label == i ) * 1)，然后根据这个mask去得到不同颜色的车道线 (HxWx3)。你可以参考cityscapes里的label2color脚本。

**Comment by foxkw** [comment]
> 
> 
> 你可以直接根据ground-truth的label (HxW)，得到不同车道线的mask ((label == i ) * 1)，然后根据这个mask去得到不同颜色的车道线 (HxWx3)。你可以参考cityscapes里的label2color脚本。

你好博主，关于ERFNet-CULane_pytorch项目，我写了个可视化代码，可以上传到repo里吗，效果挺好的。

**Comment by easternbun** [comment]
> 你好博主，关于ERFNet-CULane_pytorch项目，我写了个可视化代码，可以上传到repo里吗，效果挺好的。


你好，可以发一份可视化代码给我吗？谢谢了。easternbun@yahoo.com

**Comment by akshatbhutra** [comment]
@cardwing can you please explain the logic behind line 35 of [https://github.com/cardwing/Codes-for-Lane-Detection/blob/master/ENet-TuSimple-Torch/evaluate/lane.py](url).
Thanks.
