### ISSUE TITLE
bdd100k数据集预处理

### ISSUE THREAD

**Issue by bingkunj** [cardwing/Codes-for-Lane-Detection#326]
作者您好，感谢你提供如此优秀的开源项目！

bdd100k车道线标注形式不太明白，poly2d形式标注怎么转化为线条，可以分享做法吗？如果方便可以提供一下你预处理的脚本吗，非常感谢！

例如：
"poly2d": [
                        [
                            305.268154,
                            449.929388,
                            "C"
                        ],
                        [
                            209.389704,
                            468.664488,
                            "C"
                        ],
                        [
                            106.898947,
                            468.664488,
                            "C"
                        ],
                        [
                            0,
                            469.766552,
                            "L"
                        ]
                    ]

"c"类型的点是什么意思？

**Comment by cardwing** [comment]
对于双实/虚线，我是直接取的两条线的中间线，即对坐标对取平均。
