### ISSUE TITLE
about the number of lane

### ISSUE THREAD

**Issue by legendary111** [cardwing/Codes-for-Lane-Detection#329]
I use the erfnet code.
What should I do if I want to detect no less than four lanes?

**Comment by cardwing** [comment]
You can just change the number of output channels to detect more lanes.

**Comment by legendary111** [comment]
Thanks for your reply! I'll give it a try. But I also saw an article yesterday about the erFnet network, it is also a 5 channel output, but it also detects more lines, maybe the post processing part is different? I'll look into the differences between your method and his.
