### ISSUE TITLE
BDD100K数据集label区分实例

### ISSUE THREAD

**Issue by ZZZENG** [cardwing/Codes-for-Lane-Detection#331]
作者您好~
请问按照您这边的方法，生成label的时候每条车道线实例有办法区分开吗~

**Comment by cardwing** [comment]
目前的做法是没有分开的，因为我们做的是binary segmentation。不过在生成label的时候应该可以分开，因为BDD100K里是对每一个车道线实例做的标注，具体做法你需要看BDD100K的脚本。

**Comment by ZZZENG** [comment]
> 目前的做法是没有分开的，因为我们做的是binary segmentation。不过在生成label的时候应该可以分开，因为BDD100K里是对每一个车道线实例做的标注，具体做法你需要看BDD100K的脚本。

谢谢您的回复~，我去看看官方的脚本
