### ISSUE TITLE
demofile训练问题

### ISSUE THREAD

**Issue by zhj695918236** [cardwing/Codes-for-Lane-Detection#332]
windows下敲入：python tools/train_lanenet.py --net /data/vgg16.npy --dataset_dir /demo_file/train_gt.txt /demo_file/val_gt.txt
usage: train_lanenet.py [-h] [--dataset_dir DATASET_DIR] [--net NET]
                        [--weights_path WEIGHTS_PATH]
train_lanenet.py: error: unrecognized arguments: /demo_file/val_gt.txt

有人说这个只需要写到目录即可，但是还是报错
python tools/train_lanenet.py --net /data/vgg16.npy --dataset_dir /demo_file
Traceback (most recent call last):
  File "tools/train_lanenet.py", line 336, in <module>
    train_net(args.dataset_dir, args.weights_path, net_flag=args.net)
  File "tools/train_lanenet.py", line 164, in train_net
    assert ops.exists(train_dataset_file)
AssertionError

demo_file中的train_gt.txt文件中内容（CULane-dataset是在lane-dectetion-model目录下的）：
/CULane-dataset/driver_23_30frame/05151649_0422.MP4/00000.jpg /CULane-dataset/laneseg_label_w16/driver_23_30frame/05151649_0422.MP4/00000.png 1 1 1 1

请问这个是哪里出了问题呢？谢谢回复!

**Comment by cardwing** [comment]
这个应该是路径问题，你可以把那个完整的路径打印出来看看。
