### ISSUE TITLE
关于制作自己的数据集问题

### ISSUE THREAD

**Issue by miao02830** [cardwing/Codes-for-Lane-Detection#337]
您好，想请教您个问题。
想请教您list6.txt这个txt文件是怎样生成的？
![image](https://user-images.githubusercontent.com/27732256/139609303-334cb85c-532f-4a86-b477-d4ba63ee7cdc.png)
这后面的01是代表车道线是否存在吗？这个是一一手动生成的吗？
我想制作自己的数据集，我运行了您提供的segLabelGen0.py这个代码，只生成了车道线的灰度图。
谢谢您，期待您的回复！

**Comment by cardwing** [comment]
是的，只需要判断当前分割图里是否有某条车道线就好了，根据这个去产生0/1的标签。
