### ISSUE TITLE
meaning of .lanes.txt annotations file in CULane

### ISSUE THREAD

**Issue by arijitcodespace** [cardwing/Codes-for-Lane-Detection#338]
I have been trying to figure this out for a while now. But I don't seem to get exactly is the meaning of the annotations file in the CULane dataset because at first, I thought those points represent the coordinates of the key points in the lane but the coordinates more often than not are beyond the sizes of the image. If the images have been resized to some new standard size then it is not mentioned on the official page of CULane nor can I find some standard size of the image. How can I interpret/retrieve the actual coordinates of the lanes? 

Any ideas?

**Comment by cardwing** [comment]
The original annotation is indeed the coordinates of the key points in the original image. Using the official scripts of CULane can generate the segmentation maps automatically.
