### ISSUE TITLE
Evaluation metrics on lane dectection

### ISSUE THREAD

**Issue by shenhuqiji** [cardwing/Codes-for-Lane-Detection#339]
Firstly, thank you for better work. I am a new hand for lane detection and have some questions about the metrics (TP ,FP and FN). These metrics are not similar to evaluation results based on pixels that are quite lower. Now, I have these prediction images and corresponding labels images and I am confused to calculate the metrics on lane. So, whether you can give me a help and provide a calculation code (Python ) of these metrics for me to study. I will appreciate it if you are convenient to do this. Thank you so much.

**Comment by cardwing** [comment]
You can refer to [this code](https://github.com/cardwing/Codes-for-Lane-Detection/blob/master/ENet-TuSimple-Torch/evaluate/lane.py).
