### ISSUE TITLE
1800 episodes for Tusimple but SAD introduced in 40k episodes

### ISSUE THREAD

**Issue by pmgautam** [cardwing/Codes-for-Lane-Detection#340]
In the paper, it says that Tusimple was trained for 1800 episodes. However, SAD is only introduced after 40k episodes. For Tusimple there are results for both ENet and ENet-SAD. Can someone explain if there are discrepancies or am I missing something here?

**Comment by cardwing** [comment]
Here, 40K is for CULane. On TuSimple, SAD is added in 1200 episodes.
