### ISSUE TITLE
Changing the TuSimple output format to CULane format 

### ISSUE THREAD

**Issue by GJ-AT** [cardwing/Codes-for-Lane-Detection#341]
Hi, is there a way to reformat the TuSimple .json file output to  be in .txt CULane format.

I am trying to visualize lines that are drawn based on predicted points. I do it with CUlane format no problem, but when I test on TuSimple I get output in official TuSimple format for lane anotations.

I am wondering is there are a script that allows me to do this because I dont know how I would do it on my own.

I need TuSimple .json  output format to be changed in  CULane .txt format.

Any ideas?

**Comment by cardwing** [comment]
If I understand it correctly, you want to train the model on TuSimple the same way as that on CULane. You can just use the list [here](https://github.com/cardwing/Codes-for-Lane-Detection/tree/master/ENet-TuSimple-Torch/list6).
