### ISSUE TITLE
蒸馏问题

### ISSUE THREAD

**Issue by Kea1b0Om** [cardwing/Codes-for-Lane-Detection#342]
不好意思 我只能看懂pytorch的代码 所以只看了culane的检测实现 想问您一下 代码中的蒸馏的温度设置 蒸馏损失计算等代码在哪里呢

**Comment by cardwing** [comment]
可以参考[ENet-SAD_Pytorch](https://github.com/InhwanBae/ENet-SAD_Pytorch).
