### ISSUE TITLE
Question about the futher testing to get curve lines and calculate precision, recall and F1-measure

### ISSUE THREAD

**Issue by KevinWalkerFan** [cardwing/Codes-for-Lane-Detection#36]
I just follow your test steps and get the probability maps from the model. U mentioned 'To get the final performance, you need to follow SCNN to get curve lines from probability maps as well as calculate precision, recall and F1-measure'. The problem is that I run your code in windows but the original SCNN testing is running in Linux. Does is it run succesfully in Windows? Do u get the test result in Windows?

**Comment by KevinWalkerFan** [comment]
Ok. Thank u so much.

**Comment by cardwing** [comment]
^_^

**Comment by KevinWalkerFan** [comment]
Oh. I have one more question. i just use only one GPU(Nvidia 1060) to train. And because of memory problem I have to modify the batch size from 8 to 4. Is it ok for training？

**Comment by cardwing** [comment]
@KevinWalkerFan, one GPU with 12 GB is sufficient for the training (batch size = 8). Modifying the batch size from 8 to 4 will degrade the performance a little.
