### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by pengyiwu** [cardwing/Codes-for-Lane-Detection#39]
感谢大佬分享，请问一下，如果在culane上训练的话需要选取ROI删除引擎盖区域吗，不这样的话换自己拍摄的视频来测试训练好的模型是否会效果不佳

**Comment by cardwing** [comment]
@pengyiwu，只要保证两个场景差不多（道路类型，摄像头型号，光线强度等），在culane上面train好的模型应该可以在你自己采的数据集上面跑的比较好。如果效果差一些，再fine tune一下就好了。

**Comment by cardwing** [comment]
^_^
