### ISSUE TITLE
How to generate the json file needed for evaluation?

### ISSUE THREAD

**Issue by 131404060321** [cardwing/Codes-for-Lane-Detection#4]
@cardwing  Hi,  If I want to evaluate SCNN on TuSimple Lane Detection Challenge dataset, how can I generate the json file needed for evaluation?（pred_file.json）

**Comment by cardwing** [comment]
@131404060321 , the attached file is used to generate the pred_file.json. However, this file assumes the probability maps are generated in the manner of [test_lanenet.py](https://github.com/cardwing/Codes-for-Lane-Detection/blob/master/SCNN-Tensorflow/lane-detection-model/tools/test_lanenet.py). In other words, you need to train the model using [train_lanenet.py](https://github.com/cardwing/Codes-for-Lane-Detection/blob/master/SCNN-Tensorflow/lane-detection-model/tools/train_lanenet.py) and test the model using [test_lanenet.py](https://github.com/cardwing/Codes-for-Lane-Detection/blob/master/SCNN-Tensorflow/lane-detection-model/tools/test_lanenet.py).
[pred_json.zip](https://github.com/cardwing/Codes-for-Lane-Detection/files/2622686/pred_json.zip)

**Comment by 131404060321** [comment]
Thank you very much!
