### ISSUE TITLE
请问下lanenet Scnn两种网络哪个视觉上检测效果更好呀

### ISSUE THREAD

**Issue by PenghuahuaPeng** [cardwing/Codes-for-Lane-Detection#42]

**Comment by cardwing** [comment]
@PenghuahuaPeng，因为SCNN和Lanenet相比多了一个message passing模块和一个lane existence预测模块，所以理论上SCNN是比LaneNet要好的，你可以试一下SCNN-Tensorflow，看一下效果。

**Comment by cardwing** [comment]
@MaybeShewill-CV   ^_^
