### ISSUE TITLE
Question about the evaluation

### ISSUE THREAD

**Issue by KevinWalkerFan** [cardwing/Codes-for-Lane-Detection#44]
Is it ok to use run.sh in windows when doing evaluation? just to follow the original steps?
![image](https://user-images.githubusercontent.com/26733530/51448050-b4440a00-1d5e-11e9-9a6b-5e2806a31879.png)

**Comment by KevinWalkerFan** [comment]
Do I need to install opencv(c++)?

**Comment by cardwing** [comment]
@KevinWalkerFan, yes. You can install opencv using python or building from source to check if the evaluation process can run normally.

**Comment by KevinWalkerFan** [comment]
And do I need to install MinGW to be able to use 'make'? did u do the evaluation on Linux or on windows?

**Comment by cardwing** [comment]
@KevinWalkerFan, I have not used MinGW before so I can not give my advice. I perform the evaluation in Linux.

**Comment by KevinWalkerFan** [comment]
Do u have the output file after runing run.sh？

**Comment by cardwing** [comment]
@KevinWalkerFan, following the instruction provided by [SCNN](https://github.com/XingangPan/SCNN), you can obtain the F1-measure of the pre-trained model. Also, if you have poor results, please refer to [this issue](https://github.com/cardwing/Codes-for-Lane-Detection/issues/38).
