### ISSUE TITLE
关于训练模型问题

### ISSUE THREAD

**Issue by Cverlpeng** [cardwing/Codes-for-Lane-Detection#45]
按照readme准备了数据集，使用2块GPU   训练模型时报错如下：
我的  tensorflow = 1.12.0 它提示API已经弃用。是这个原因儿找不到对的文件吗？

W0121 15:26:00.527571 23387 tf_logging.py:125] From tools/train_lanenet.py:249: start_queue_runners (from tensorflow.python.training.queue_runner_impl) **is deprecated and will be removed in a future version.**
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
2019-01-21 15:26:02.450372: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at whole_file_read_ops.cc:114 : Not found: laneseg_label_w16/driver_23_30frame/05160929_0487.MP4/00015.png; No such file or directory
2019-01-21 15:26:02.450372: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at whole_file_read_ops.cc:114 : Not found: driver_23_30frame/05160929_0487.MP4/00015.jpg; No such file or directory
E0121 15:26:02.450782 23387 tf_logging.py:105] Exception in QueueRunner: laneseg_label_w16/driver_23_30frame/05160929_0487.MP4/00015.png; No such file or directory
	 [[{{node data_augmentation/ReadFile_1}} = ReadFile[_device="/job:localhost/replica:0/task:0/device:CPU:0"](data_augmentation/input_producer/GatherV2_1)]]
	 [[{{node data_augmentation/DecodeJpeg/_53}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_17_data_augmentation/DecodeJpeg", tensor_type=DT_UINT8, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

**Comment by MaybeShewill-CV** [comment]
@Cverlpeng 那是个warning不是error，这个api会在未来被弃用.Error出在找不到文件:)

**Comment by Cverlpeng** [comment]
> @Cverlpeng 那是个warning不是error，这个api会在未来被弃用.Error出在找不到文件:)
好的，谢谢，我去下好的数据集中，能够找到提示找不到的文件。问题出在哪里了呢？

**Comment by MaybeShewill-CV** [comment]
@Cverlpeng 可能是相对路径不对，可以仔细检查下:)

**Comment by cardwing** [comment]
@Cverlpeng, @MaybeShewill-CV  好的，谢谢 ^_^
