### ISSUE TITLE
Does one message passing procedure share the same one conv module?

### ISSUE THREAD

**Issue by harryhan618** [cardwing/Codes-for-Lane-Detection#48]
In [vgg_encoder.py](https://github.com/cardwing/Codes-for-Lane-Detection/blob/master/SCNN-Tensorflow/lane-detection-model/encoder_decoder_model/vgg_encoder.py), it seems that one message passing procedure (say top down) share one conv module.

But in the paper [SCNN](https://arxiv.org/pdf/1712.06080.pdf), it seems that conv modules are different in one message passing procedure. (According to Equation (1) in Page 3)

BTW, in Xingang Pan's [souce code](https://github.com/XingangPan/SCNN/blob/master/experiments/models/SCNN-gen.lua#L66), it seems in one message passing procedure, 'conv:clone' is done. I'm not quite sure whether this `clone` procedure is a deep clone in lua torch. Maybe you could give me a definite answer. Much appreciated!

**Comment by harryhan618** [comment]
Emm, sorry, stupid question.  The [paper](https://arxiv.org/pdf/1712.06080.pdf) has made it every clear.

> Note that the convolution kernel weights are shared across
all slices, thus SCNN is a kind of recurrent neural network

Another question, have you tried tanh rather than relu as the activation function in message passing? For the reasons that relu doesn't have negative activation and recurrent network is mentioned.

**Comment by cardwing** [comment]
@harryhan618, I have not tried other activation functions. I think you are right and replacing relu with tanh or leaky relu may improve the message passing process.
