### ISSUE TITLE
关于实例标签

### ISSUE THREAD

**Issue by Cverlpeng** [cardwing/Codes-for-Lane-Detection#50]
您好！您能提供生成文件夹laneseg_label_w16下，实例分割标签png文件的python脚本吗？我想调整一下线宽，另外程序为什么没有在sess.run()的时候feed  input  和 label数据呢？还有就是在dataset类中，我该如何使用numpy函数出来tensor呢？希望 您能解答，谢谢！

**Comment by Cverlpeng** [comment]
我想在获取batch 数据的类中对数据做一些图像的预处理，需要使用opencv，但是它提示我  “src is not a numpy array, neither a scalar  ”,我该如何将tensor转换成numpy或者其他方式使用CV2函数呢。

**Comment by xuefengxiaoyang** [comment]
@Cverlpeng 生成分割标签png的代码在SCNN仓库里，采用placeholder输入才需要feed,作者的代码采用的是多线程，如果要处理图像，只能用tf自带的库，作者是用tf读取的数据。

**Comment by Cverlpeng** [comment]
> @Cverlpeng 生成分割标签png的代码在SCNN仓库里，采用placeholder输入才需要feed,作者的代码采用的是多线程，如果要处理图像，只能用tf自带的库，作者是用tf读取的数据。
谢谢您的解答！
