### ISSUE TITLE
generating label_data.json

### ISSUE THREAD

**Issue by masterLearning** [cardwing/Codes-for-Lane-Detection#52]
Hello @cardwing 

I am currently trying to train the lanenet model with my own dataset but i missing some files.
M current status:
- I trained successfully the network with the 6 images which are in traning data example directory 
Now i need to train it with my own dataset (I generated images from a simulation program) 
In order to train the network i need additionaly the gt_images_instance and the gt_image_binary of each image.

For that i can use the generate_tusimple_dataset.py file in the tools directory and my files need to be structured as in the tuSimple directory, but my problem is i can not run the file because i dont have the label_data.json . How can i generate the json file with all all the attributes 
- "lanes" 
- "h_samples"
- "raw_file" 
and, am i doing something wrong or is there perhaps a better way to train the network ?

I thank you in advance for any answer.

**Comment by cardwing** [comment]
Actually, you can generate the label_data.json according to the instruction of TuSimple dataset (manually generate the file). Since I am not familiar with the label generation process, you can seek help in lanenet repo.

**Comment by masterLearning** [comment]
First of all, thank you very much for your response. 

What instruction do you mean? In the lane_demo they already use two json files.
- https://github.com/TuSimple/tusimple-benchmark/blob/master/example/lane_demo.ipynb 
and  in the lane detection secion in tuSimple, they are writing about the structure of the json file but not how to generate a file for yourself.
- https://github.com/TuSimple/tusimple-benchmark/tree/master/doc/lane_detection

The label file that i mean is ls located in the guidlines section.
 https://github.com/TuSimple/tusimple-benchmark/blob/master/doc/lane_detection/guideline.md

Did you train the network with your own dataset? If yes, how did you solve the problem?

**Comment by cardwing** [comment]
I have not trained the network with my own dataset. The json file is used to generate the labels (i.e., semantic segmentation maps which are comprised of 1,2,3...). You can refer to [this issue](https://github.com/cardwing/Codes-for-Lane-Detection/issues/4) and generate the json file from instance segmentation outputs.

**Comment by masterLearning** [comment]
Is it possible with this pred_json.py file to generate a json file which i can  use to generate the gt_images_instance and the gt_image_binary of each image?
In this file a pred_test_SCNN_02_0001_02_6_e01_full.json file is required which i do not have. What is this file ?

Its really important for me to train the network with my own dataset.I appreciate you trying to help me.

**Comment by cardwing** [comment]
pred_json.py is used to generate the corresponding json file from segmentation maps. pred_test_SCNN_02_0001_02_6_e01_full.json is just the output file.

**Comment by masterLearning** [comment]
@cardwing What do you mean with segmanetation maps?
And do you know why in the label_files in tuSimple only the path of the last picture was specified? 
What with the pictures 1..19? Does one entry ( "lanes", "h_sample", "raw_file") refer to all 20 pictures in the directory?  Please help i am confused.

**Comment by cardwing** [comment]
Segmentation maps are comprised of 1,2,3,... and each number denotes one class.
