### ISSUE TITLE
light-weight model

### ISSUE THREAD

**Issue by pengyiwu** [cardwing/Codes-for-Lane-Detection#53]
Hello,happy new year! 如果有的话能分享一下轻量化模型（ENet-SAD）的代码吗，感谢^~^

**Comment by cardwing** [comment]
新年好，我们暂时还不能公开代码，等论文结果出来了才可以放。

**Comment by pengyiwu** [comment]
恩恩，静候佳音啊

**Comment by pengyiwu** [comment]
顺便问一哈，message passing模块用在enet哪一层比较好，stage3后面吗？有哪些需要注意的地方，想把这个模块加在lanenet的掩码分支上试下，感谢

**Comment by cardwing** [comment]
一般是加在encoder的最后一层的输出上。我没有加过，你可以试一下。

**Comment by pengyiwu** [comment]
感谢回复，请教一下 w1 = tf.get_variable('W1', [1, 9, 128, 128],
                                 initializer=tf.random_normal_initializer(0, math.sqrt(2.0 / (9 * 128 * 128 * 5))))
初始化中标准差为啥这样计算？最后一个5是num-class吗，我改成了9*128*128*2， 我训练了一下，还没跑完，还有relu要不要改成和enet一样的prelu，这个模块后面要不要dropout再decoder。。。。调参经验不足，可以给点建议不，感谢。

**Comment by cardwing** [comment]
5是num-class。初始化的过程好像是按照恺明的论文来做的。至于encoder之后要不要加dropout，我不是很清楚。之前我有试过将message passing加到ENet的模型上面，效果没有提升很多。至于经验的话，你可以用dilated convolution，FPN等。

**Comment by pengyiwu** [comment]
好的，感谢回复^~^
