### ISSUE TITLE
 Assign requires shapes of both tensors to match. lhs shape= [2560,128] rhs shape= [4500,128]

### ISSUE THREAD

**Issue by jjzhu** [cardwing/Codes-for-Lane-Detection#55]
any idea while loading the checkpoint?

thanks,
-Vioto

**Comment by jjzhu** [comment]
using ../model/model_culane-71-3/culane_lanenet_vgg_2018-12-01-14-38-37.ckpt-10000

**Comment by cardwing** [comment]
What is the size of your input image? The code (pre-trained  model) requires that the input image is 288 x 800.

**Comment by jjzhu** [comment]
thanks for your quick response, cardwing. I changed the input image to 288x800. It is interesting the output is 512x256. I am testing a video input here is the code:

input_tensor = tf.placeholder(dtype=tf.float32, shape=[1, 288, 800, 3], name='input_tensor')
image = cv2.resize(image, (800, 288), interpolation=cv2.INTER_LINEAR)
instance_seg_image, existence_output = sess.run([binary_seg_ret, instance_seg_ret],
                                                            feed_dict={input_tensor: [image]})

noticed the instance_seg_image is [512x256]

any idea?

**Comment by jjzhu** [comment]
here is the visualization code:

for i in range(4):
                instance_seg_image[0][:, :, i] = minmax_scale(instance_seg_image[0][:, :, i])
            embedding_image = np.array(instance_seg_image[0], np.uint8)

  cv2.imshow("capture",image)
  cv2.imshow("embedding",embedding_image[:,:,(2,1,0)])

**Comment by cardwing** [comment]
Everything is fine in my local server. Please read the code carefully and find out the problem yourself.
