### ISSUE TITLE
模型下载问题

### ISSUE THREAD

**Issue by zqnnn** [cardwing/Codes-for-Lane-Detection#56]
您好，我这边的网络下载不了你提供的VGG.npy和pretrained model, 请问是否可以提供其他下载方式

**Comment by cardwing** [comment]
我过几天弄个百度云的链接。

**Comment by zqnnn** [comment]
赞~

**Comment by cardwing** [comment]
链接: https://pan.baidu.com/s/1tMxFS6t4m0djJFg4cM2OKg 提取码: ebi9
