### ISSUE TITLE
Question about your  pre-trained model for testing

### ISSUE THREAD

**Issue by xuefengxiaoyang** [cardwing/Codes-for-Lane-Detection#57]
@cardwing Hello,i download your pre-trained model for testing,and i found this pre-trained model not be trained by the code of this repository. Can you share what operations need to supplement to  reproduce the results as your pre-trained model?

**Comment by cardwing** [comment]
The code has been revised to support multi-gpu training. You can either re-train the model or use the old code which is before Dec 19, 2018.

**Comment by xuefengxiaoyang** [comment]
Thank you!
