### ISSUE TITLE
您好，问下根据您提供的预训练权重，运行test culane代码：

### ISSUE THREAD

**Issue by PenghuahuaPeng** [cardwing/Codes-for-Lane-Detection#59]
每张原图的运行结果是两个输出：车道线存在性exist.txt:1,1,1,1;和可视化的四张黑白图像，但其中一张是全黑的，另外三张依次代表一条车道线，那这样exist.txt不应该是：0，1，1，1吗？另外您卷积resize出来的预测概率是怎样变成test里可视化的四张黑白图像的呢？期待您的答复。

**Comment by cardwing** [comment]
lane existence prediction branch可能有误检。test_lanenet.py里有预测概率是怎样变成test里可视化的四张黑白图像，就是过一个softmax然后再smooth一下。

**Comment by PenghuahuaPeng** [comment]
看到了，多谢。
