### ISSUE TITLE
About  the raw test data and tesing evaluation

### ISSUE THREAD

**Issue by Endless-Hao** [cardwing/Codes-for-Lane-Detection#61]
Hello，I want to ask a question about the results. Such as the results in shadow is not good. I looked and compared with the raw data gt and the testing result. I find there are many files were empty. But from the picture, we can see the lane and the testing results also got the lanes. But the gt files were nothing. I think this problem may let the evaluation not accuracy about the real testing results. 
![00000](https://user-images.githubusercontent.com/19277849/53229558-87697680-36bf-11e9-8f5c-b73347c0a047.jpg)
The above picture has lanes but gt file is nothing.
![00000 results](https://user-images.githubusercontent.com/19277849/53229612-ae27ad00-36bf-11e9-9a68-f26bcd7aaa81.png)
The above is the testing result.
IF  there is no gt, this evaluation is not really about the ability of the algorithm.

**Comment by cardwing** [comment]
@Endless-Hao, there are indeed some problems with the labels. Maybe that is why the algorithm has large FP.
