### ISSUE TITLE
准确度判定问题

### ISSUE THREAD

**Issue by MurphyChengIsMe** [cardwing/Codes-for-Lane-Detection#64]
你好，我想跟您讨论一下论文中的F1 score计算问题，论文中提到如果模型输出跟ground truth的IoU > 0.5，则属于TP，那么FN跟FP要怎么判定呢？ 如果说0.5是判断有没有剪测出的标准，那么当我的IoU值为0.5 > IoU > 0应该算是未检出，属于FN(ground truth是车道，但被我判定为背景)，但论文中写这个是FP(ground truth是背景，但被我判定为车道)，所以我有点不太明白这是怎么计算，如何分辨FP跟FN，谢谢您。

**Comment by cardwing** [comment]
@MurphyChengIsMe，这里FP和FN是这样来判定的：首先通过比较IoU是否大于0.5，我可以得到TP的lane的数目（IoU大于0.5），那么FP=num_of_detected_lanes - TP，FN=num_of_ground_truth_lanes - TP。SCNN-Torch的后处理代码（counter.cpp）里有写。

**Comment by MurphyChengIsMe** [comment]
@cardwing 好的，我明白了，谢谢您仔细的回覆，一开始没有想到是这样的计算方式，非常谢谢您。
