### ISSUE TITLE
模型处理速度问题

### ISSUE THREAD

**Issue by MurphyChengIsMe** [cardwing/Codes-for-Lane-Detection#65]
您好，我在测试代码里面尝试加入时间的计算，在我的1080Ti上面运行，平均每张图片耗时约0.3秒，不知道您是否有尝试测试过该模型的处理速度，是不是也约略在这个处理速度上下，我推测可能是前端VGG16本身参数就多加上后端SCNN模型，使向前传播速度快不上来，也有可能是我测试有问题，想跟您讨论是否有尝试过类似的测试，谢谢您。

**Comment by cardwing** [comment]
@MurphyChengIsMe, the feedforward time of SCNN-Torch is around 130 ms. I have not tested the inference time of SCNN-tensorflow.

**Comment by MurphyChengIsMe** [comment]
那您所使用的GPU也同样是1080Ti吗？还是其他规格的GPU呢？谢谢您。

**Comment by cardwing** [comment]
TITAN X.

**Comment by MurphyChengIsMe** [comment]
好的，谢谢。
