### ISSUE TITLE
请问一下训练时loss的超参是怎么调整的？

### ISSUE THREAD

**Issue by Derteanoo** [cardwing/Codes-for-Lane-Detection#67]
代码中的loss=segmenatation_loss+0.1*existence_loss，由于两个task中后一个task要依赖于前一个task的精度，有没有必要先单独训练segmentation部分，然后再freeze segmentation部分的参数训练existence的参数？或是调整两个loss占比的超参？

**Comment by cardwing** [comment]
The two branches are trained jointly. And in the final stage, you can set the coefficient of the existence prediction loss as zero and boost the segmentation branch.
