### ISSUE TITLE
Questions about message passing and testing existence results

### ISSUE THREAD

**Issue by jamie0618** [cardwing/Codes-for-Lane-Detection#68]
Hello, I have some questions after tracing and running your code

1. In "down to top" and "right to left" of message passing in vgg_encoder.py, what's the meaning of the number 8 in  length = int(CFG.TRAIN.IMG_WIDTH / 8) - 1 ?

2. I used some testing frames in CULane dataset with your trained model. Results of segmentation images are great, however, almost all of the existence_output are larger than 0.95 even there is no lane in the image. Is this correct?

Thanks!

**Comment by cardwing** [comment]
8 denotes that the size of the output feature map is 1/8 of the original image. And the lane existence prediction branch should not always output values larger than 0.95. Please check your code.

**Comment by jamie0618** [comment]
Ok, I will check my code again.
Thanks for your reply!
