### ISSUE TITLE
**About your pre-training model questions

### ISSUE THREAD

**Issue by hawjnsafdjlk** [cardwing/Codes-for-Lane-Detection#70]
![图片1](https://user-images.githubusercontent.com/36946777/54193887-f46d7080-44f5-11e9-8c14-213cc371c40d.png)
When you use the pre-training model you provided for evaluation, F1 can reach 70. Your pre-training model uses bgr three-channel when reading images with opencv during training, so we also need to use bgr mode for reading Images during testing , and subtract three mean values.
As shown above, does the pre-training model parameters you provided are obtained by training 10,000 steps? The author mentioned in the original text that the training iterated 60K step!!!

**Comment by cardwing** [comment]
@hawjnsafdjlk, the model is trained for 90K steps (I use 8 as batch size while original paper uses 12) and finetuned using another 10K steps. That is the reason why the checkpoint "shows" that the training steps are 10K.
