### ISSUE TITLE
关于论文中的测试问题

### ISSUE THREAD

**Issue by MurphyChengIsMe** [cardwing/Codes-for-Lane-Detection#71]
你好我想请教你一下，请问这个模型在我的理解上，是不是主要用来完成影像分割(image segmentation)的任务? 因为我就论文中的比较方式而言，我实现了简单的VGG影像分割网路(FCN) ，使用作者的测试方式所得到的F1-score分数仅有50，远远不如论文中所提及的63.2，但单看效果而言是比论文中呈现的图片分割状况要好的，想问问看你的看法，或许是我的测试方式有问题。另外论文中Table.5所注记的「Table 5: Comparison with other methods, with IoU threshold=0.5. For crossroad, only FP are shown」中，For crossroad, only FP are shown这句我感觉不是非常明白他的意思，希望能请教你一下，谢谢你。

**Comment by cardwing** [comment]
只用VGG-16的话在简单的道路情况下效果应该还可以，但是在稍微复杂（光线不好，弯道等）的情况下效果应该比较差。For crossroad, only FP are shown 是说对于交叉路口（定义为没有车道线的情况），只统计模型的车道线的误检数目。

**Comment by MurphyChengIsMe** [comment]
想再请教一下关于论文中的车道线分类状况，在论文中作者针对这些不同情况的车道线的F1-score进行计算（Normal、Crowded、Night、No line、Shadow、Arrow、Dazzle light、Curve），但在我下载下来的数据集上好像看不到这些分类，还是作者有特别标住哪几个档案是包含在这里面的呢？ 谢谢你。

**Comment by cardwing** [comment]
那个是testing set上面的分类，training set上面没有对路况进行分类。

**Comment by MurphyChengIsMe** [comment]
好的，非常谢谢你。
