### ISSUE TITLE
tensorflow version

### ISSUE THREAD

**Issue by zguo008** [cardwing/Codes-for-Lane-Detection#72]
Hi,
May I know why are u using tensorflow 1.3 here instead of other high version? 
Best regards,
ZX

**Comment by cardwing** [comment]
My code is based on [this repo](https://github.com/MaybeShewill-CV/lanenet-lane-detection) which uses tf 1.3.

**Comment by zguo008** [comment]
@cardwing hi,I have spent some time training CUlane with Lanenet as well and I think Lanenet is based on CUDA9 and tensorflow==1.10.0? 

Cuz if the model is to be deployed for real time use I guess a higher version of tensorflow and CUDA may be more suitable?

**Comment by cardwing** [comment]
Using a higher version of tf and cuda is indeed appropriate.
