### ISSUE TITLE
 Testing problem

### ISSUE THREAD

**Issue by BoSeal** [cardwing/Codes-for-Lane-Detection#74]
When I ran the code on the test dataset, the following problems occurred，and Do you know the reason and how to solve it?

1607
CULane/driver_193_90frame/06051606_0728.MP4/04680.jpg
CULane/driver_193_90frame/06051606_0728.MP4/04770.jpg
CULane/driver_193_90frame/06051606_0728.MP4/04860.jpg
CULane/driver_193_90frame/06051606_0728.MP4/04950.jpg
CULane/driver_193_90frame/06051606_0728.MP4/05040.jpg
CULane/driver_193_90frame/06051606_0728.MP4/05130.jpg
1608
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1350, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1329, in _run_fn
    status, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Expected image (JPEG, PNG, or GIF), got empty file
         [[Node: map/while/DecodeJpeg = DecodeJpeg[acceptable_fraction=1, channels=3, dct_method="", fancy_upscaling=true,ratio=1, try_recover_truncated=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](map/while/ReadFile)]]
         [[Node: map/while/ResizeBicubic/_201 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_337_map/while/ResizeBicubic", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](^_cloopmap/while/ExpandDims/_176)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/test_lanenet.py", line 121, in <module>
    test_lanenet(args.image_path, args.weights_path, args.use_gpu, img_name, args.batch_size, save_dir)
  File "tools/test_lanenet.py", line 84, in test_lanenet
    feed_dict={input_tensor: paths})
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1128, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1344, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1363, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Expected image (JPEG, PNG, or GIF), got empty file
         [[Node: map/while/DecodeJpeg = DecodeJpeg[acceptable_fraction=1, channels=3, dct_method="", fancy_upscaling=true,ratio=1, try_recover_truncated=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](map/while/ReadFile)]]
         [[Node: map/while/ResizeBicubic/_201 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_337_map/while/ResizeBicubic", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](^_cloopmap/while/ExpandDims/_176)]]

Caused by op 'map/while/DecodeJpeg', defined at:
  File "tools/test_lanenet.py", line 121, in <module>
    test_lanenet(args.image_path, args.weights_path, args.use_gpu, img_name, args.batch_size, save_dir)
  File "tools/test_lanenet.py", line 60, in test_lanenet
    imgs = tf.map_fn(test_dataset.process_img, input_tensor, dtype=tf.float32)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/functional_ops.py", line 409, in map_fn
    swap_memory=swap_memory)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2934, in while_loop
    result = loop_context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2720, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2662, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/functional_ops.py", line 399, in compute
    packed_fn_values = fn(packed_values)
  File "/home/ubuntu/MyFiles/BoSeal/code/Codes-for-Lane-Detection-master/SCNN-Tensorflow/lane-detection-model/data_provider/lanenet_data_processor_test.py", line 58, in process_img
    img_decoded = tf.image.decode_jpeg(img_raw, channels=3)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_image_ops.py", line 645, in decode_jpeg
    name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3160, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1625, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Expected image (JPEG, PNG, or GIF), got empty file
         [[Node: map/while/DecodeJpeg = DecodeJpeg[acceptable_fraction=1, channels=3, dct_method="", fancy_upscaling=true,ratio=1, try_recover_truncated=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](map/while/ReadFile)]]
         [[Node: map/while/ResizeBicubic/_201 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_337_map/while/ResizeBicubic", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](^_cloopmap/while/ExpandDims/_176)]]

**Comment by cardwing** [comment]
"Expected image (JPEG, PNG, or GIF), got empty file". Please check the path of your input image.

**Comment by BoSeal** [comment]
@cardwing 你好，考虑到时间问题，我只用了部分测试集来进行测试。我把图片路径打印出来，看了下，并没有出错，我试了很多方法，仍是出现上述的问题：运行到第1525 batch时，可以看到打印出的“paths”内容是正确的，但就是报出如下错误：
CULane/driver_193_90frame/06051606_0728.MP4/04050.jpg
CULane/driver_193_90frame/06051606_0728.MP4/04140.jpg
CULane/driver_193_90frame/06051606_0728.MP4/04230.jpg
CULane/driver_193_90frame/06051606_0728.MP4/04320.jpg
CULane/driver_193_90frame/06051606_0728.MP4/04410.jpg
CULane/driver_193_90frame/06051606_0728.MP4/04500.jpg
1524
paths: ['CULane/driver_193_90frame/06051606_0728.MP4/04590.jpg', 'CULane/driver_193_90frame/06051606_0728.MP4/04680.jpg', 'CULane/driver_193_90frame/06051606_0728.MP4/04770.jpg', 'CULane/driver_193_90frame/06051606_0728.MP4/04860.jpg', 'CULane/driver_193_90frame/06051606_0728.MP4/04950.jpg', 'CULane/driver_193_90frame/06051606_0728.MP4/05040.jpg']
CULane/driver_193_90frame/06051606_0728.MP4/04590.jpg
CULane/driver_193_90frame/06051606_0728.MP4/04680.jpg
CULane/driver_193_90frame/06051606_0728.MP4/04770.jpg
CULane/driver_193_90frame/06051606_0728.MP4/04860.jpg
CULane/driver_193_90frame/06051606_0728.MP4/04950.jpg
CULane/driver_193_90frame/06051606_0728.MP4/05040.jpg
1525
paths: ['CULane/driver_193_90frame/06051606_0728.MP4/05220.jpg', 'CULane/driver_193_90frame/06051606_0728.MP4/05310.jpg', 'CULane/driver_193_90frame/06051609_0729.MP4/00000.jpg', 'CULane/driver_193_90frame/06051609_0729.MP4/00090.jpg', 'CULane/driver_193_90frame/06051609_0729.MP4/00180.jpg', 'CULane/driver_193_90frame/06051609_0729.MP4/00270.jpg']
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1350, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1329, in _run_fn
    status, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Expected image (JPEG, PNG, or GIF), got empty file
         [[Node: map/while/DecodeJpeg = DecodeJpeg[acceptable_fraction=1, channels=3, dct_method="", fancy_upscaling=true,ratio=1, try_recover_truncated=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](map/while/ReadFile)]]
         [[Node: map/while/Identity/_187 = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_317_map/while/Identity", _device="/job:localhost/replica:0/task:0/device:GPU:0"](map/while/Identity/_186)]]

During handling of the above exception, another exception occurred:

**Comment by BoSeal** [comment]
@cardwing “ Now, you get the probability maps from our model. To get the final performance, you need to follow SCNN to get curve lines from probability maps as well as calculate precision, recall and F1-measure.”
你的这句话的意思是：这个tensorflow版本的代码，只能得到概率图，如果想要得到“precision, recall and F1-measure”，还要使用原作者的SCNN代码。我理解的意思对么？

**Comment by cardwing** [comment]
Yes.

**Comment by PenghuahuaPeng** [comment]
@cardwing 您好，从概率图中可视化是不是以每20行为单位，搜索这里面是车道线概率最大的点？您每个像素点是否是车道线的概率是存放在  encoder部分里面的ret函数里了吗？

**Comment by PenghuahuaPeng** [comment]
![image](https://user-images.githubusercontent.com/46223350/54523691-0e51fc00-49ab-11e9-92a2-e8c0bbb2e8b0.png)
 @cardwing 在tool/test.py里，这个instance_seg_image代表是否是车道线的损失吗？shape是[:,280,800,:]第一个维度和最后的维度是什么意思？谢谢

**Comment by jamie0618** [comment]
我的理解是 :
instance_seg_image 代表預測出來的 probability map，值的範圍在 0~1 之間，乘上 255 還原成黑白圖片 (值越大表示該 pixel 有車道線的機率越高)
shape 280, 800 是原始資料集的照片尺寸

**Comment by PenghuahuaPeng** [comment]
@jamie0618 谢谢，instance_seg_image含义是代表每张图片（cnt）每个坐标点（200，800），分别是（1-4）车道线的概率吗？

**Comment by jamie0618** [comment]
不是，單純是 1->有車道、0->沒有車道，這個是 pixel-wise 的值
至於是 1~4 哪個車道，則是用 existence_output 的值去判斷
existence_output 輸出四個機率值，例如 0.1, 0.1, 0.99, 0.95 表示車道 3、4 有很高機率有標線

**Comment by hellosher** [comment]
@jamie0618，我想请问一下，用代码中给的训练好的模型进行测试，我这里得到的测试结果生成在了测试数据里，而且重点是每张图片对应4张车道图，这是正确的吗，我想得到每张图对应的车道线综合的图应该怎么调整代码呢？谢谢

**Comment by jamie0618** [comment]
@hellosher 每一張圖對應一個車道的結果，要綜合的話在 for loop 裡面把 4 個車道的 instance_seg_image 疊加在一起輸出照片就可以了

**Comment by hellosher** [comment]
@jamie0618非常感谢，不过能不能再打扰您一下，能告诉我那两句代码应该怎么写吗，我还不太会，爆哭。。

**Comment by jamie0618** [comment]
@hellosher 
`for cnt_img in range(4):
    if cnt_img == 0:
        total_img = (instance_seg_image[cnt, :, :, cnt_img + 1] * 255).astype(int)
    else:
        total_img += (instance_seg_image[cnt, :, :, cnt_img + 1] * 255).astype(int)`
大概是這樣，最後再把 total_img 輸出成圖片

**Comment by hellosher** [comment]
@jamie0618 非常非常非常感谢您
