### ISSUE TITLE
AssertionError问题

### ISSUE THREAD

**Issue by hellosher** [cardwing/Codes-for-Lane-Detection#78]
你好，我在进行训练时遇到了这样的问题，训练数据存放路径为/home/dl/文档/SCNN/SCNN-Tensorflow/lane-detection-model/dataset/train/，但在输入命令python tools/train_lanenet.py --dataset_dir /dataset/train/时，提示错误为Traceback (most recent call last):
  File "tools/train_lanenet.py", line 336, in <module>
    train_net(args.dataset_dir, args.weights_path, net_flag=args.net)
  File "tools/train_lanenet.py", line 164, in train_net
    assert ops.exists(train_dataset_file)
AssertionError
我觉得比较诧异，是我的路径不对吗，应该怎样输入呢？

**Comment by hellosher** [comment]
我把上面的路径修改成绝对路径之后又遇到了新的问题，tensorflow.python.framework.errors_impl.NotFoundError: driver_23_30frame/05170920_0732.MP4/04790.jpg
	 [[Node: data_augmentation_1/ReadFile = ReadFile[_device="/job:localhost/replica:0/task:0/cpu:0"](data_augmentation_1/input_producer/Gather)]]
很多个这种错误提示，请问有碰到过吗？

**Comment by cardwing** [comment]
Please check you image path carefully.
