### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: driver_100_30frame/05251517_0433.MP4/00000.jpg

### ISSUE THREAD

**Issue by hellosher** [cardwing/Codes-for-Lane-Detection#79]
problem 1:
NotFoundError (see above for traceback): driver_100_30frame/05251517_0433.MP4/00000.jpg
	 [[Node: map/while/ReadFile = ReadFile[_device="/job:localhost/replica:0/task:0/cpu:0"](map/while/TensorArrayReadV3)]]
	 [[Node: map/while/ResizeBicubic/_263 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_4154_map/while/ResizeBicubic", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"](^_cloopmap/while/ExpandDims/_176)]]

problem 2:
tensorflow.python.framework.errors_impl.NotFoundError: driver_100_30frame/05251517_0433.MP4/00000.jpg
	 [[Node: map/while/ReadFile = ReadFile[_device="/job:localhost/replica:0/task:0/cpu:0"](map/while/TensorArrayReadV3)]]
	 [[Node: map/while/ResizeBicubic/_263 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_4154_map/while/ResizeBicubic", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"](^_cloopmap/while/ExpandDims/_176)]]

Sorry to say this,the two problems are difficult to me ,do you know how to solve them?

**Comment by YilmazOrkun** [comment]
@hellosher You need to use the absolute path in the test.txt file. In my case I had to use an additional '/'.

like this: 

//home/nvidia/dataset/driver_100_30frame/05251517_0433.MP4/00000.jpg

**Comment by hellosher** [comment]
Should I modify all the data in test.txt file?maybe thousands of data in test.txt?

**Comment by YilmazOrkun** [comment]
Yes you have to modify the paths of every line in test.txt.
You should write a python script to change the paths.

**Comment by hellosher** [comment]
Is that the same for the training part,such as train_gt.txt and val_gt.txt?

**Comment by YilmazOrkun** [comment]
I did not use the training part yet. Hence I don't know about that.

**Comment by hellosher** [comment]
Ok,thank you very much! I will try this method!!
