### ISSUE TITLE
Testing of SCNN model

### ISSUE THREAD

**Issue by chokkarapu** [cardwing/Codes-for-Lane-Detection#8]
HI,

Wanted to do inference and plot the detected lanes onto image.
You mentioned need that to follow SCNN to get curve lines from probability maps.

In your inference code you are not storing the probabilities maps, so can I kindly know how to save those probability (in what format) and then how to pass it through MATLAB code for generation of lines from probability map.

kindly provide your inputs, Look forward.

**Comment by cardwing** [comment]
@chokkarapu , the inference is done in [test_lanenet.py](https://github.com/cardwing/Codes-for-Lane-Detection/blob/master/SCNN-Tensorflow/lane-detection-model/tools/test_lanenet.py). Please have a look. As to the generation of lane points, please refer to [SCNN](https://github.com/XingangPan/SCNN).

**Comment by cardwing** [comment]
@chokkarapu , yes, we only store the existence of each lane. What do you mean by marking those lanes? If you only need the coordinates of lanes, please refer to the instructions [here](https://github.com/XingangPan/SCNN). The coordinates can be obtained by using [this code](https://github.com/XingangPan/SCNN/blob/master/tools/prob2lines/main.m) which is provided by [SCNN](https://github.com/XingangPan/SCNN).
