### ISSUE TITLE
There is a problem with the evaluation results

### ISSUE THREAD

**Issue by hawjnsafdjlk** [cardwing/Codes-for-Lane-Detection#81]
I trained this model from scratch, the number of training steps is the same as yours, and I evaluated it after the test. But F1-measure is 67.39, which is much lower than the original paper and the result of your fine-tuning. **I want to ask how you fine-tuned 10,000 steps?**
Ps. When training and testing, the input picture has been subtracted by three mean values (vgg_mean), and the image channel is BGR.

**Comment by cardwing** [comment]
My original model can achieve around 69.5 when training from scratch. The fine-tune tricks can be found in [this issue](https://github.com/cardwing/Codes-for-Lane-Detection/issues/5). You can also add data augmentation like horizontal flipping and random cropping to boost the performance.

**Comment by hawjnsafdjlk** [comment]
Okay, thank you!
