### ISSUE TITLE
should getting lane mask via python be possible? 

### ISSUE THREAD

**Issue by zguo008** [cardwing/Codes-for-Lane-Detection#83]
Hi:)

I am thinking whether lane_mask can be obtained using python implementation. Since it would be more convenient. I am not sure why the author of the paper use matlab to plot the mask. Can you help me explain this?

Also, comparing lanenet with SCNN, the binary ret both refers to pixel wise lane existence probability in my opinion. If the code from Lanenet can plot the mask using python, i believe it's also possible in SCNN right?

**Comment by cardwing** [comment]
Both python and matlab can get lane mask easily.

**Comment by zguo008** [comment]
thanks!!

have a nice day:)

**Comment by daeunni** [comment]
@guozixunnicolas Hi, do you have python version codes? :)
