### ISSUE TITLE
PROBLEMS IN Training:tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled 	 [[Node: batch_1/fifo_queue_enqueue = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch_1/fifo_queue, data_augmentation_1/Sub/_89, data_augmentation_1/Cast_1/_91, data_augmentation_1/Cast_2/_93)]]

### ISSUE THREAD

**Issue by hellosher** [cardwing/Codes-for-Lane-Detection#84]
GeForce GTX 1070 Ti
major: 6 minor: 1 memoryClockRate (GHz) 1.683
pciBusID 0000:01:00.0
Total memory: 7.92GiB
Free memory: 7.56GiB
There are two errors.
1.tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled
	 [[Node: batch_1/fifo_queue_enqueue = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch_1/fifo_queue, data_augmentation_1/Sub/_89, data_augmentation_1/Cast_1/_91, data_augmentation_1/Cast_2/_93)]]
2.tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[8,288,800,64]
	 [[Node: tower_0/gradients/zeros_80 = Fill[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"](tower_0/gradients/Shape_81, tower_0/gradients/zeros_80/Const)]]
	 [[Node: tower_3/truediv/_1819 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_97611_tower_3/truediv", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Does anybody know how to solve these two problems?Thank you in advance!

**Comment by cardwing** [comment]
Please fix the problem by yourself since I have not met this problem before.

**Comment by yujincheng08** [comment]
OOM, you should decrease your batch size.
