### ISSUE TITLE
Missing "image_name" in test_lanenet.py

### ISSUE THREAD

**Issue by hnbharathreddy** [cardwing/Codes-for-Lane-Detection#9]
"test_lanenet(args.image_path, args.weights_path, args.use_gpu, image_name, args.batch_size)"
NameError: name 'image_name' is not defined.
Can you please fix this..?

**Comment by cardwing** [comment]
@hnbharathreddy , I have corrected the wrong variable name. It should be "img_name". Thanks for pointing it out.

**Comment by hnbharathreddy** [comment]
Hi @cardwing,
Thanks for the correction, But when I tried to run the code 'TypeError: object() takes no parameters' can you please identify the error. 
Thanks in advance.


This is the command I used to run 

CUDA_VISIBLE_DEVICES="0" python test_lanenet.py --weights_path /home/bharath/testing/Codes-for-Lane-Detection-master/SCNN-Tensorflow/lane-detection-model/test-model-68-8/culane_lanenet_vgg_2018-11-27-16-03-42.ckpt-76000 --image_path /home/bharath/testing/Codes-for-Lane-Detection-master/SCNN-Tensorflow/lane-detection-model/testimage.txt
Traceback (most recent call last):
  File "test_lanenet.py", line 138, in <module>
    test_lanenet(args.image_path, args.weights_path, args.use_gpu, img_name, args.batch_size)
  File "test_lanenet.py", line 61, in test_lanenet
    test_dataset = lanenet_data_processor_test.DataSet(image_path)
TypeError: object() takes no parameters


And my testimage.txt file contains
/data/epoc_input/image/testbench/00001.jpg
/data/epoc_input/image/testbench/00002.jpg
/data/epoc_input/image/testbench/00003.jpg
/data/epoc_input/image/testbench/00004.jpg
/data/epoc_input/image/testbench/00005.jpg

**Comment by cardwing** [comment]
@hnbharathreddy , please refer to [this blog](https://stackoverflow.com/questions/23176597/python-object-takes-no-parameters-error) and see if it is helpful to you. In my local environment, this error does not happen.

**Comment by MaybeShewill-CV** [comment]
@hnbharathreddy Maybe you're supposed to change the image path from it's relative path to it's absolute path:)
