### ISSUE TITLE
how to identify different types of lanes？double yellow, solid white, dotted white, etc

### ISSUE THREAD

**Issue by SuperPengXue** [cardwing/Codes-for-Lane-Detection#91]
I'm trying to make the model  be able to identify different types of lanes (double yellow, solid white, dotted white, etc.). Do you have any suggestions for this? thanks.

**Comment by zguo008** [comment]
Output tensor has 5 dimensions, 0:background,1-4:4 different lanes. Use the line generator script(they used matlab) from the original scnn repo(Lua implementation), you can get 4 instances.

But the result sometimes is not very promising. See my result/ thinking from #89 for details, basically sometimes there are mixing lane points for a single lane. I search all lane points altogether and did clustering.

**Comment by zguo008** [comment]
Hi @cardwing it would be very kind of you if you can share some insight on my question in #89 as well:) thanks in advance!

**Comment by SuperPengXue** [comment]
@zguo008  thank you for your reply.    I encountered similar problems, the most left lane and  left lane are sometimes not clear, will be mixed together.

**Comment by SuperPengXue** [comment]
Hi  @cardwing  I think it is hard to  identify different types of lanes and identify different position of lanes，That's going to be multi-label network。Do you have any suggestions for this? thanks.

**Comment by cardwing** [comment]
@SuperPengXue, maybe you can refer to [VPGNet](https://arxiv.org/pdf/1710.06288.pdf).
