### ISSUE TITLE
what's training set used in your pre-trained model ?

### ISSUE THREAD

**Issue by gokiri** [cardwing/Codes-for-Lane-Detection#93]

**Comment by cardwing** [comment]
CULane training set.

**Comment by gokiri** [comment]
thanks a lot for your response!   
Another question is how do you find the pixel belonging to the lane pixel in probability map?

**Comment by cardwing** [comment]
"During testing, we still need to go from probmaps to curves. As shown in Fig.5 (b), for each lane marking whose existence value is larger than 0.5, we search the corresponding probmap every 20 rows for the position with the highest response. These positions are then connected by cubic splines, which are the final predictions." (from SCNN paper) The highest response is the lane point and these points are connected to form the final lane prediction.
