### ISSUE TITLE
Training problem with gpu

### ISSUE THREAD

**Issue by BoSeal** [cardwing/Codes-for-Lane-Detection#94]
When I train the lane dataset, I use the hardware configuration： one Tesla K20 GPU with 5G memory. This causes OOM！To solve this problem, I reduce the batch size to 4 ，but still happen“OOM”.
So I don't know if I'm going to keep reducing the batch size? If I continue to reduce the batch size, I worry that it will affect the accuracy of the results and not reach the accuracy obtained in original SCNN paper.
Can you give me some advice?

**Comment by cardwing** [comment]
Reducing the batch size to 4 will inevitably degrade the performance. You may need to resize the input image to test if it will degrade the performance significantly.
