### ISSUE TITLE
A code problem of ntpath.py

### ISSUE THREAD

**Issue by wzd1360** [cardwing/Codes-for-Lane-Detection#95]
When i run the train_lanenet.py, it reminds an error in another py file named ntpath.py, which is located in the folder of lib of anaconda. 
Error line: path=os.fspath(path)
TypeError: expected str, bytes, or os.PathLike object, not NoneType.
I'm struggling for quite a while. Does this project need to be done in Lunix? 
Expecting any possible solutions. Thanks!

**Comment by cardwing** [comment]
You can print the variable 'path' to debug the code.
