### ISSUE TITLE
Dilated convolution

### ISSUE THREAD

**Issue by zguo008** [cardwing/Codes-for-Lane-Detection#96]
Hi,

I have been playing around with the model for some time, just want to clarify one thing, in the encoder stage 5_1 to 5_4 dilated convolution is used while in 5_5 a normal convolution is used again.

May I know the reason of using dilated convolution here and why a normal convolution is added afterwards?

Best regards,

ZX

**Comment by zguo008** [comment]
Also as far as I know VGG encoder's last encode stage is conv_5_3 before it's connected to FC layer, could you please tell me why you have conv_5_4 and conv_5_5 before message passing?

Thanks!

**Comment by cardwing** [comment]
Dilated convolution is used to increase the receptive field size. Conv_5_4 and conv_5_5 are used to remap the number of channels to 128 so as to reduce the overall feedforward time. Conv_5_4 has a dilation rate of 4 so I guess it is used to obtain more contextual info.

**Comment by zguo008** [comment]
Thank you!
