### ISSUE TITLE
result 

### ISSUE THREAD

**Issue by BoSeal** [cardwing/Codes-for-Lane-Detection#97]
When I train the dataset, the intermediate results were as follows:
![image](https://user-images.githubusercontent.com/39556913/56945717-a3274800-6b5a-11e9-9b17-5d0b04c5145b.png)
Why is it happen？

**Comment by cardwing** [comment]
Please print the variable 'accuracy' to debug the code.

**Comment by zguo008** [comment]
@BoSeal @cardwing  you can refer to my issue at #101

**Comment by BoSeal** [comment]
@cardwing 你好，我在一台带有一个K20gpu的服务器上训练CULane数据集，在训练过程中，批大小设置为2，但每次都在epoch大约为120时，服务器就会重新进行内存配置并重启，导致训练过程中断！！！
请问你知道原因以及解决方法么？

**Comment by cardwing** [comment]
Please debug by yourself since I have not met this problem before.
